### ISSUE TITLE
Stacked graphs

### ISSUE THREAD

**Issue by duprasf** [wet-boew/wet-boew#4466]
@duboisp Est-ce qu'il y a une façon de faire des "stacked graph" avec WET comme avec le plugin jquery.flot.stack.js? Présentement nos lignes apparaissent une derrière l'autre (vue par défaut pour stacked)

(Aussi, la plupart des liens de cette page retournent des 404: http://wet-boew.github.io/wet-boew/docs/ref/charts/charts-en.html)

**Comment by danpoleary** [comment]
I to am having the same issue. The init of any flot plugin added using the above example is never called.

How do we add flot plugins?

**Comment by danpoleary** [comment]
I have dug deeper into this issue, and you can repeat it on the sample charts/charts-en.html sample page.

Take the above code, and add it to the page, but instead of stacked, use flot.navigate and flot.navigateControl.

Apply the following to the bar table example on the charts-en.html page:
data-flot='{ "zoom": { "interactive": true }, "pan": {"interactive": true}, 
            "navigationControl": {
	    "display": true,
            "homeRange": {"xmin":-10,"xmax":10,"ymin":-10,"ymax":10},
            "panAmount": 100,
            "zoomAmount": 1.5,
            "position": {"left": "20px", "top": "20px"}
        
    }}'

When you run the page, the bar chart will have navigation controls as expected.

Now, comment all the other charts except for the bar chart and re-run the page. No navigation will be loaded for the bar chart. 

Now add an empty chart table entry anywhere else on the page (KEY):
<table class="wb-charts wb-charts-area table"></table>

Re-run the page... Surprise, the bar chart now has navigation again.

It appears that there is an error in wet-boew.js, creating a race condition. Here is what I was able to trace so far for both conditions.

1. Only the bar chart table exists - No navigation generated.
    a. wet-boew - Modernizr.load = function () { yepnope.apply(window, [  ].slice.call(arguments, 0))}
           Called 3 times, base load, for the built in flot plugins, and for prettify
    b. wet-boew - modernizer.load() is called.
    c. (a.) is called again for the flot.navigate and flot.navigationControl plugins.
    d. jquery.flot - initPlugins is called with only pie, canvas, and orderBars.
    e. flot.navigate and flot.navigationControl are loaded and push'd to the plugins.
    Page is loaded, but no navigation controls.

2. The bar chart table exists and one empty chart table as per (KEY) above - navigation generated.
    a. wet-boew - Modernizr.load = function () { yepnope.apply(window, [  ].slice.call(arguments, 0))}
           Called 4 times, base load, for the built in flot plugins twice, and for prettify
    b. wet-boew - modernizer.load() is called.
    c. (a.) is called again for the flot.navigate and flot.navigationControl plugins.
    d. flot.navigate and flot.navigationControl are loaded and push'd to the plugins.
    e. wet-boew - modernizer.load() is called.
    f. jquery.flot - initPlugins is called with pie, canvas, orderBars, navigate, and navigationControl.
    g. both flot.navigate and flot.navigationControl init functions called.
    Page is loaded, with navigation controls.

Dan

**Comment by LaurentGoderre** [comment]
The code mentioned by @duboisp is not asynchronously safe and will only work if the plugin finished loading after the parsing of the table is complete (which rarely occurs). We are looking at a new plugin structure to facilitate this but in the meantime, there will be a need to add functionality to specify additional plugins.

**Comment by LaurentGoderre** [comment]
@duprasf @danpoleary @benhurqc @JammG my pull requests addresses this issues. To use you only need the following:

```html
<script>
(function() {
	window[ "wb-charts" ] = {
		plugins: [
			"site!deps/jquery.flot.navigate.js",
			"site!deps/jquery.flot.navigationControl.js"
		]
	};
})();
</script>
```
