### ISSUE TITLE
Zebra striping-Firefox 28-laptop

### ISSUE THREAD

**Issue by nrustand92** [wet-boew/wet-boew#5400]
Weird bug..horizontal lines don't appear.  The striping works fine though & its ok with other browsers as well

![image](https://cloud.githubusercontent.com/assets/5949078/2906415/8d0179a4-d610-11e3-8a2e-9d155121ac4e.png)

**Comment by hsrudnicki** [comment]
@nrustand92 @duboisp : Can be this issue closed ?

**Comment by pjackson28** [comment]
The latest Chrome and Firefox seem to behave the same (so may have been an issue with Firefox 28 which is now out of the support window).

One question before we close, Should the zebra striping and hover effect be so subtle? I had to look really closely to even notice it was there. @thomasgohard Thoughts?

Also might be a good idea to to be clearer about what is the expected result for "Multiple Group" since it is nowhere near as clear a description as for the other examples.

New issues could be spawned for each of these new points if they are actually issues (so I'll close this issue).
