### ISSUE TITLE
Lightbox - Next/Back can be too far away

### ISSUE THREAD

**Issue by rubinahaddad** [wet-boew/wet-boew#5429]
From HE: https://github.com/wet-boew/wet-boew-styleguide/issues/7

Problem: In a wide screen the Next and Back controls can be far from the image. They can be missed, and/or the distance to the controls increases the probability of clicking on the background, closing the image.

Suggestion: Have the Next and Back controls stay close to the image.

**Comment by hsrudnicki** [comment]
@rubinahaddad @pjackson28 : Are you ready to close this issue ?

**Comment by pjackson28** [comment]
It is related to #5430. The problem we are facing is there is no clear way to implement such a fix. The next and previous buttons are in the same container as the actual image (which that container is the full width of the screen), so there seems to be no easy easy way to make the buttons reliably and consistently positioned near the image (since the buttons are absolutely positioned). Would have been easier if Magnific Popup includde the next/previous buttons in the image container, but that is not the case.

**Comment by hsrudnicki** [comment]
Based on last comment from @pjackson28, this issue with the other referenced issue have been labeled "Going Stale" if not further status updates, then this issue with the other one can be closed.

**Comment by hsrudnicki** [comment]
Due to no clear issue problem and no further discussion/status updates, this issue has been closed.
