### ISSUE TITLE
Required Class on Strong tag not working

### ISSUE THREAD

**Issue by CalvinRodo** [wet-boew/wet-boew#6417]
According to @pjackson28  in Issue #6281 the only tag in a label that needs a required class is the strong tag around the text (Required) like so: 

````html
<div class="form-group">
  <label for="bar">
    Foo <strong class="required">(required)</strong>
  </label>
  <input id="bar" type="text" required="true" aria-required="true" />
</div>
````

however you need to have the class on the label for the red and italicizing to work like so:

````html
<div class="form-group has-error">
  <label class="required" for="bar">
    Foo <strong>(required)</strong>
    <span class="label label-danger">Error #:  Error Message</span>
  </label>
  <input id="bar" type="text" required="true" aria-required="true" />
</div>
````

You can test this by going to http://wet-boew.github.io/v4.0-ci/demos/formvalid/formvalid-en.html viewing the source in something like firebug/chrome developer tools and removing the required class on the label, the strong tag will still have it and the styling goes away.

**Comment by pjackson28** [comment]
Looks like you are right. Not sure why it requires a "required" class on the label (might have been because of the reuse of existing SCSS nesting). Here is the code in questions: https://github.com/wet-boew/wet-boew/tree/master/src/base/forms#L13-L28

If this doesn't make sense then that SCSS could always be changed to remove the label.required requirement for strong.required.

**Comment by melodyma** [comment]
Would it be more appropriate to put the <strong> styling in a class instead? This will separate the styling from the structure.

**Comment by CalvinRodo** [comment]
I'm really just basing this bug off of what you mentioned in issue #6281 
If the requirement is that you have the class required on both the label and the strong tag then so be it. it might be a bit confusing to have to add the class twice but if that's what's required to make *required* work then so be it.

**Comment by pjackson28** [comment]
I suspect that it was an inadvertent consequence of reusing existing SCSS nesting in that SCSS file. It could easily be simplified to strong.required but is there a risk of that not being specific enough (so running into other uses of strong.required)? The big thing we would need to avoid is changing the class name or adding additional markup requirements that weren't there before as that would mean a breaking change. At this point we can safely simplify (if it is worth the effort) since there is no documented support of that CSS outside of form validation and it wouldn't break existing use.

**Comment by melodyma** [comment]
I suggest that the strong tag be changed to a span tag and update the SCSS accordingly. The SCSS nesting may be deeper than necessary too. 

```html
<div class="form-group">
  <label for="bar">
    Foo <span class="required">(required)</span>
  </label>
  <input id="bar" type="text" required="true" aria-required="true" />
</div> 
```

**Comment by pjackson28** [comment]
The strong tag is being used for its semantic meaning and not just for visual effect. The semantics would be lost with a span tag.

Looking at the SCSS some more, it looks like "required" needs to stay on the label element as it is needed to apply the red asterisk at the start of the label.

**Comment by melodyma** [comment]
@pjackson28 Agreed! Thanks.

**Comment by CalvinRodo** [comment]
@pjackson28 Does it need to stay on the strong tag as well or is it fine to have it on just the label. If it has to be on both I can close this issue.

**Comment by pjackson28** [comment]
@CalvinRodo It has to be on the strong element as well since there are other valid uses of strong in a label element.

**Comment by CalvinRodo** [comment]
Then I'll close this issue as working as expected and make the change in the other issue.
