### ISSUE TITLE
Tabbed interface: using row class within tab makes horizontal scrollbar appear

### ISSUE THREAD

**Issue by crichard** [wet-boew/wet-boew#6425]
When using `<div class="row">` within a tabbed interface detail, the horizontal scroll bar appears even if no content is clipped.  Scroll bar disappears if row class margin-right is removed (line 1243 of wet-boew.css).

You can test at this url: http://webdev.multimediaservices.ca/en/centres/findarecruiter-110

**Comment by CalvinRodo** [comment]
I'm just curious but why are you using rows if all you are doing is using a 12 column, what benefit does that provide? 

To solve this issue you could just add a class to the tabs that has 

````css
overflow-x: hidden !important; 
````

that *should* fix this issue. 

The scroll bar is coming from this css

````css
.wb-tabs [role="tabpanel"] {
    overflow-x: auto;
}
````

**Comment by crichard** [comment]
I use rows because I have a lot of content that needs to be positioned.  If you go to this page http://webdev.multimediaservices.ca/en/centres/findarecruiter-110 and select Quebec / All Cities and click search, you will see the results in the first tab.  If you view the source code there, you will see that I position my results using rows.

I will use your suggestion with the no-overflow-x class if you feel that is the best solution.

Thanks.

**Comment by pjackson28** [comment]
The margins come from Bootstrap as "row" is intended to be a child of a "container" element. The problem is that the approach you are taking is that "row" by default is wider than a tabpanel. The scrollbar is just a symptom of that and playing with overflow-x is not a safe fix as no scrollbar will appear when the content actually clips (which would be a failure of WCAG 2.0 up to 200% text size). So you shouldn't play with the tabpanel CSS, instead focus on fixing the horizontal space that your content is taking up.

The simplest fix is to put class="container-fluid" on the parent element (the section element in this case) as you should not be using a "row" without a "container" as a parent (against Bootstrap recommendations).

**Comment by CalvinRodo** [comment]
I just noticed you aren't using a container for your rows so just add a container-fluid class to the section containing the rows and it should fix your problem.

**Comment by CalvinRodo** [comment]
Oh just noticed @pjackson28 already answered the same thing.
