### ISSUE TITLE
Inconsistant Alert box display across browsers.

### ISSUE THREAD

**Issue by josephbr** [wet-boew/wet-boew#6429]
I have created an alert box and for some reason, Chrome is displaying an extra drop-down arrow with the word "Details" beside it. This is not in the actual markup so I have no idea where it is coming from. This happens in both the latest stable and development release of WET.

In Firefox, it looks like this:
![Firefox Alert Box](http://i.imgur.com/NFGTe7j.png)

...but in Chrome, I get this:
![Chrome Alert Box](http://i.imgur.com/HwVWjGl.png)

The markup for the box is this:
```
<details class="alert alert-danger" id="alert-danger" open="open">
<h1 style="margin:0;font-size:120%">Welcome to the new CCOHS.ca</h1>
<p>We are updating our website so you can find the workplace health and safety information and tools you need faster, from your desktop, tablet and mobile devices. Here are some <a href="#" class="alert-link">Quick Tips</a> to help you get the most from the improved, streamlined navigation. Please <a href="/ccohs/contacting.html" class="alert-link">contact us</a> with your feedback and suggestions as we complete the redesign in the coming weeks.</p>
</details>
```

Any ideas what could be wrong?

**Comment by pjackson28** [comment]
You are missing the summary element (which should be wrapped around the heading) which is why you are getting the issue. Also you should use the h* classes (e.g., class="h3") on the summary and heading element to change the size (at least on the summary element if you choose to leave the heading element at the original size).

**Comment by pjackson28** [comment]
As a side-note, should you be using a "danger" alert for "Welcome to the new CCOHS.ca"? Normally that is reserved for errors and critical issues. An "info" alert seems more appropriate in this case.

**Comment by josephbr** [comment]
Better than before but now it looks like this:
![Chrome Alert Box](http://i.imgur.com/9VfglD9.png)

The reason I am using a "danger" alert here is for that green exclamation mark (which is what the designer had wanted).

**Comment by pjackson28** [comment]
The arrow is supposed to be there since it is a collapsible alert. If you don't want it to be collapsible then use the non-collapsible alert markup (so without details/summary).

Isn't one of the h* classes close enough? You should avoid using the style attribute because it can cause a lot of issues (particular for end users who want to override colours/sizes for accessibility reasons). Also note that there is a risk to using icons for different purposes. For instance your using the "danger" icon for an "info" will not only confuse the meaning of the icon (so muddying the effect) but some people with colour deficiencies won't be able to tell that it is green and not red which could lead to more confusion.

**Comment by hsrudnicki** [comment]
@josephbr @pjackson28 : Can this issue be closed?

**Comment by pjackson28** [comment]
Yes as the initial issue was due to missing markup and the triangle is the intended result for the given markup.
