### ISSUE TITLE
v4.0.9: Horizontal scrollbar within Tabs if table-bordered or form-horizontal used

### ISSUE THREAD

**Issue by hub-c** [wet-boew/wet-boew#6439]
Within a tabbed interface panel, if table-bordered option is used on a datatable, or form-horizontal is applied to a form with div.form-group, then a horizontal scrollbar appears within that tab even though contents should fit just fine in available width.

The datatables scrollbar bug only seems to happen in Firefox, but the form-horizontal scrollbar bug also appears in Chrome, Safari (didn't get to testing IE).

I replicated the issue (screenshots below) by replacing the main content of the WET distro demo's xcontent-en.html and content-secmenu-en.html with the following code (tried for v4.0.8-1 too, but bug only happens in v4.0.9).

```
<section>
<div class="wb-tabs" id="wb-tabsDev">
<div class="tabpanels">
<details id="details-panel1">
<summary>Datatable example</summary>
<p>
	<table class="wb-tables table table-bordered" id="blah">
		<thead>
			<tr>
				<th>col 1</th>
				<th>col 2</th>
				<th>col 3</th>
			</tr>
		</thead>
		<tbody>
			
				<tr>
					<td>
						col1
					</td>		
					<td>
						col 2
					</td>
					<td>
						col 3
					</td>
				</tr>
			
		</tbody>
	</table>
</p>
</details>
<details id="details-panel2" open="open">
<summary>form-group example</summary>
<p>			
	<form action="nowhereEither" method="post" class="form-horizontal">
		
		<div class="form-group">
			<label class="col-sm-3 control-label" for="input1">Input label</label>
			<div class="col-sm-8">
				<input type="text" name="input1" value="someValue" class="form-control"  />
			</div>
		</div>
		
	</form>

</p>
</details>

</section>
```

![datatables scroll](https://cloud.githubusercontent.com/assets/8657007/5711799/396702d4-9a7b-11e4-8d21-c2535e34bc67.jpg)
![form-horizontal scroll](https://cloud.githubusercontent.com/assets/8657007/5711803/3fa43946-9a7b-11e4-9d94-772c3139894a.jpg)

**Comment by pjackson28** [comment]
I can't reproduce the issue with the table (can't get a scrollbar no matter how much I shrink the browser width).

I can reproduce with the form but that is not a surprise since <code>.form-horizontal .form-group</code> introduces negative left and right margins of -15px (exactly like the <code>row</code> class, effectively making it greater than 100% width (hence the scrollbar). The reason why it didn't add the scrollbar pre-v4.0.9 is that the content was being clipped (so no matter how wide the content got there would be no scrollbar). So the pre-v4.0.9 result is the correct one. To get rid of the scrollbar, you would need to counteract the negative margin, bringing the effective width back to 100%. The easiest way is to add <code>container-fluid</code> to the form element's class attribute (just like you would do for the <code>row</code> class). That introduces a left and right padding of 15px which counteracts the negative margin of 15px.

**Comment by hub-c** [comment]
Thanks, adding `container-fluid` class to the form removed the horizontal scroll. It also fixed the datatable after I enclosed it in a `<div class="fluid-container">`
