### ISSUE TITLE
Support for Blackberry

### ISSUE THREAD

**Issue by DHaslip** [wet-boew/wet-boew#6443]
This is related to issue #6341 What browsers/versions are officially supported by wet 4.x?.

We are also using WET for internal web applications.  Internal users have Blackberry as their mobile device.  Are there any plans for WET to officially support the Blackberry?

**Comment by pjackson28** [comment]
Official support is dependent upon the % of visits to web sites which BlackBerry accounts for a very low percentage. Nonetheless, BlackBerry browsers over the past few years have had pretty good standards support which results in good results under WET (thanks in large part to BlackBerry switching to WebKit in BBOS 6.0). Their very old browsers that didn't respect standards (much like IE6 and IE7) likely won't fare as well.

So BlackBerries with WebKit browsers should effectively be supported by WET due to WET's support for other WebKit browsers.

**Comment by LaurentGoderre** [comment]
Actually, the Blackberry version of WebKit and Blackberry 10 had (and maybe still have) the highest level of compliance to HTML5 out of all mobile browser. The older ones however are a different story, much like older version of Android (such as 2.3)

**Comment by LaurentGoderre** [comment]
Can we close this now?

**Comment by DHaslip** [comment]
Yes.
