### ISSUE TITLE
Reload a form with error messages already displayed?

### ISSUE THREAD

**Issue by josephbr** [wet-boew/wet-boew#6464]
Is there a a way to load the page with an error message already displayed? One particular form I am working on requires a server call in order to validate it correctly. Namely it contains file uploads that need to be checked first.

If validation fails, I would like to show the form again with a custom error displayed in the same style used by the jQuery validation plugin itself (i.e. error field highlighted, box at the top listing the errors with links to the corresponding input, etc).

Is this possible to do? It would also be handy for validating the form should somebody have JavaScript disabled.

**Comment by LaurentGoderre** [comment]
@CalvinRodo can you share what you did?

**Comment by josephbr** [comment]
It seems I found a solution to my own problem. All I did was capture the output of the error box and then inserted it into the page with the error already displayed (i.e. I show the error after the POST request to the form) using the exact same markup structure as the jQuery generated messages. I then clicked "Submit" to trip the actual jQuery validation and it happily used the box I created ahead of time (which is what I wanted to happen).

**Comment by CalvinRodo** [comment]
@LaurentGoderre Until I have time to work on some documentation for how to properly mark up errors, you can look at issue #6281 for how to render errors server side so they match how it's displayed through jquery, so it works without the  jquery validation plugin and javascript turned off.

The version of wet we have needs to have some extra markup on the page but I believe that is fixed with the latest version available from github.
