### ISSUE TITLE
Intertab linking for the tabbed interface

### ISSUE THREAD

**Issue by fbernard2** [wet-boew/wet-boew#6479]
Unable to use relative paths for intertab linking.

**Comment by pjackson28** [comment]
You shouldn't be using relative paths for that at all (even for regular same page links). If you are linking to somewhere on the same page then you should only use the fragment identifier (URL hash, i.e., the number sign followed by the id of the fragment you are targeting). Otherwise you are telling the page to reload and the go to the fragment rather than just going straight to the fragment.

See the Example 1 tab panel in the [tabbed interface working example](http://wet-boew.github.io/v4.0-ci/demos/tabs/tabs-en.html) for an example of how to do inter-tab linking properly. There is also an example of how to link to tab from outside the tabbed interface.

**Comment by fbernard2** [comment]
Right, we are using the fragment identifier (URL hash, i.e., the number sign followed by the id) but for the version 4.09,  build 623. It does not work.

**Comment by pjackson28** [comment]
It is working in v4.10 (and in the live working examples) so you should try updating to that version to see if it addresses your issue. If you are still having the issue then you should also try on the live working example to see if it could be a browser or implementation issue.

**Comment by fbernard2** [comment]
Thanks Paul, we will need to get version v4.10. Could you provide the link to the live examples?

**Comment by pjackson28** [comment]
Yes, you can find it in my first response.
