### ISSUE TITLE
Main Menu, Sidebar, and Faceted searches

### ISSUE THREAD

**Issue by ashzadeh** [wet-boew/wet-boew#6493]
Hello everyone,

I'm currently working on implementing WET4 into an existing WET3 site and am running into a few obstacles.

### Main menu
The menu menu does allow for sub menus but what if the sub menu parent is a page as well? As best I can tell, WET4 removes the link. Is there a solution for this?

### Sidebar
1. I don't see anywhere in the documentation or the examples a way to implement multilevel menus. Is there a way to do this? 
2. Is there a way to include more than one sidebar menu? I noticed that the mobile menu only picks up the first menu.
3. Is the sidebar reserved for one menu only? Non-menu items do not display in mobile views, the content is lost. 
4. If the sidebar is only for one menu, does WET4 have an <aside> or other mechanism to include sidebar-like structuring for related content. Is the grid system the only way to do this?

### Search
1. The existing site has a faceted search with options (checkboxes) in the sidebar. If I put them in the sidebar now, they'll disappear in mobile view. What is recommended for this application?
2. The current site has an "advanced search" option that dynamically shows advance search options. From the WET4 examples I can see that "advance search" leads the user to a new page with more search options. Is this the recommended method of displaying "advance search" options?

If more details are required for any of the items, please let me know.

Thank you,
Ash

**Comment by pjackson28** [comment]
Main menu:
That is intentional. Keyboard and touchscreen users couldn't use such a link (need it to open the menu) so it would only be available to mouse users. Usability testing also showed a 30% decrease in task completion due to accidental clicks (as they weren't expecting it to be a link). So we only allow it to be a link with JavaScript disabled because the submenu isn't available. If you want to make the landing page available then add a more link to the end of the submenu (see menu plugin example page for an example).

Sidebar:
1. We only support two levels in our themes but you could add more if you add the CSS. We recommend that you don't go past two levels as that makes for a very complex menu and has caused issues for users in the past (for both desktop and mobile view). We encourage making the side bar contextual to the current section (note it is called a "Section menu" in the associated heading).

2. No we don't support more than one, you should include everything in the same menu. It would be confusing structurally semantically to have another menu.

3. Yes, it uses the HTML nav element which is only supposed to contain navigation links. There should be no other content in a nav element (other than the hidden heading). If you want other content then I suggest using the grid system to position it in the content area (non-navigation content shouldn't be appearing in the mobile panel anyway).

4. The grid system is your best option for that. You can use the HTML aside element or another similar element for related content (which element to use depends upon the content). The sidebar provided for WET is only intended for secondary navigation.

Search:
1. That type of content isn't appropriate for a nav element so shouldn't be in the sidebar. Besides, the faceted search is a primary form of navigation on the results page so should be in the content area (which will also ensure it is visible in mobile view). You can use the grid system to position the content.

2. Which example are you referring to? Could you please provide the link? That example may be theme-specific.

**Comment by ashzadeh** [comment]
@pjackson28 

Thank you for your quick reply. That clears up a lot on our end. 

This is the example I meant: http://recherche-search.gc.ca/rGs/s_r?st=s&s5bm3ts21rch=x&num=10&st1rt=0&langs=eng&cdn=canada&hq=&q=&wb-srch-sub=#wb-land

**Comment by pjackson28** [comment]
@ashzadeh That is what is currently being used for the Canada.ca (and the Canada.ca theme), but I don't think that is a general recommendation for WET as a whole at this point. We don't have anything like that in any of the other themes (although the other themes don't show any search pages so that would be why).

**Comment by hsrudnicki** [comment]
@ashzadeh  @pjackson28 : Can this issue be closed?

**Comment by ashzadeh** [comment]
On my end, yes.
