### ISSUE TITLE
Overlay will not open from Mega Menu

### ISSUE THREAD

**Issue by vallieresc** [wet-boew/wet-boew#6507]
If I have the following in the mega menu inside an li item it does not work. The anchor and modal markup is good since it works when in the content area. I don't have any js errors. Running on 4.0.10. I also tested on your fresh theme and it didn't work.
```html
<a href="#centred-popup-modal" aria-controls="centred-popup-modal" class="wb-lbx lbx-modal" role="button">Centred popup - Modal (Lightbox + Modal)</a>
```

**Comment by pjackson28** [comment]
That's because the Lightbox link isn't initialized because it is AJAXed in. You would need to fire a wb-init.wb-lbx event on that link after the menu has been AJAXed in (so would use wb-ready.wb or wb-ready.wb-menu).

Why are you opening a popup directly from a sub-menu? The area is contained within a nav element which according to HTML5 "represents a section of a page that links to other pages or to parts within the page: a section with navigation links". Why are you implementing this in an area that is only supposed to contain navigation links? If you want to open an overlay/popup then you should be doing so from the content area, not from top-level navigation.

**Comment by vallieresc** [comment]
It is not ajaxed in. Our logout link is in the mega menu. Here is the rendered link. 

```html
<a href="#centred-popup-modal" aria-controls="centred-popup-modal" class="wb-lbx lbx-modal wb-lbx-inited" role="menuitem" id="wb-auto-1" tabindex="0" aria-posinset="1" aria-setsize="4">Centred popup - Modal (Lightbox + Modal)</a>
```

**Comment by pjackson28** [comment]
We recommend against putting your logout link in the mega menu, as that menu is intended for navigation links (doesn't make sense there as the menu uses the HTML5 nav element and has the hidden heading "Topics menu"). Lougout link there also fared poorly in usability testing in comparison to other locations (in the content area fared much better).

Note also that if you will be migrating to the Canada.ca theme then for that theme the location of the sign in/sign out will be prescribed and you will have no control over what goes in the menu bar.

@thomasgohard Is the guidance available for where the sign in/sign out should go?

**Comment by CalvinRodo** [comment]
#6232 Is the issue with guidance for Logout button.

**Comment by LaurentGoderre** [comment]
I don't think it can be done , if somehow we manage to deal with the conflict on dekstop view, it wouldn't work on mobile view

**Comment by vallieresc** [comment]
Done in content area
