### ISSUE TITLE
Main Menu Dropdown Delay and Dependency on JavaScript

### ISSUE THREAD

**Issue by knicklabs** [wet-boew/wet-boew#6509]
There is a needless delay on the dropdown of the main menu component which impedes usability. The dropdown feature is implemented in JavaScript where a pure CSS solution should suffice. The feature should work in browsers with JavaScript disabled.

**Comment by LaurentGoderre** [comment]
The delay is actually added for usability reasons. Here is an extract from an article by Jakob Neilsen

<blockquote>Don't make response time too fast, though: the mouse should remain stationary for 0.5 seconds before you display anything that's hover-dependent, such as a mega drop-down or a tooltip. Violating this guideline will make the screen flicker insufferably when users move the mouse. Only after 0.5 seconds of resting the pointer on a navbar item can you assume that a user actually wants to see its associated drop-down.</blockquote>

http://www.nngroup.com/articles/mega-menus-work-well/

With regards to the use of JavaScript, it is essential to use JavaScript to enable an accessible keyboard navigation for the menu, among other thing. It is also required to implement the delay mentioned in the previous article

**Comment by knicklabs** [comment]
Interesting. I was not aware of Jakob Neilsen's advice on this. The 500ms delay still seems excessive to me though. There is a 300ms delay in mobile safari used to signify user intent. This shorter delays feels much more responsive. I am not aware of any research on this particular topic. Do you know of any additional sources of information on this or was this decision based solely on Neilsen's advice? 

In terms of the JavaScript use. Is there anything in the current implementation that stands in the way of using progressive enhancement?

**Comment by LaurentGoderre** [comment]
@knicklabs our approach is progressive enhancement because if the menu doesn't work in javascript, the top level links go to a landing page that gives access to the same information.

As for additional sources, @thomasgohard probably knows better

**Comment by Brundlefly201** [comment]
Jakob Neilson also recommends never using a dropdown menu at all.

but this article from 2009 he's referring to "Mega-Menus" ( mega menus were pretty new in 2009 ) not just simple dropdown navigation interfaces.

**Comment by LaurentGoderre** [comment]
Maybe so but it doesn't mean the the advice of waiting for the mouse to stop is a bad one.

**Comment by Brundlefly201** [comment]
Maybe not on the first mouseover... 

but continuing the 500ms delay for entire menu after a user has already clearly decided to interface with it might be.

**Comment by pjackson28** [comment]
The delay actually provides a significant benefit even after the first mouseover, particularly with users with mobile impairments. If a person has a shaky hand and the pointer briefly edges onto the next top-level menu item then you will get a flickering mess of menus (switching sub-menus back and forth rapidly). Same if you move the pointer diagonally right from the top-level menu item to a menu item in the sub-menu, inadvertently crossing over the corner of the next top-level menu item. In both of these scenarios, reducing the delay would actually slow down the user because the menu they actually wanted will have disappeared, being replaced by the one they inadvertently triggered.

So it would not only be a usability concern but also an accessibility concern if you decrease the delay.

**Comment by stephenbe** [comment]
Another point, you could transition on visibility and transition delay the property : 

Before : 

```
	.sm {
		display: none;
		max-height: 0;
		overflow: hidden;
		position: relative;

		&.open {
			display: inline;
			max-height: 1000px;
			min-width: 12.5em;
			position: absolute;
			text-transform: none;
			top: auto;
			z-index: 500;

			li {
				@extend %global-display-block;

				a {
					text-align: left;
				}
			}
		}

		details {
			> {
				* {
					margin-left: auto;
					margin-right: auto;
				}
			}
		}
	}
```

After 

```
	.sm {
		display: inline;
		max-height: 0;
		overflow: hidden;
		position: relative;

		visibility:hidden; //i'm using visibility instead on using display
		transition-property:visibility;
                transition-delay:0.5s;

		&.open {
			
			max-height: 1000px;
			min-width: 12.5em;
			position: absolute;
			text-transform: none;
			top: auto;
			z-index: 500;

			visibility:visible;

			li {
				@extend %global-display-block;

				a {
					text-align: left;
				}
			}
		}

		details {
			> {
				* {
					margin-left: auto;
					margin-right: auto;
				}
			}
		}
	}
```

This will work without JS 

Here is a working codepen if you want to look at a working example :
http://codepen.io/anon/pen/KwEYxm


Side note : we could maybe do all of this with a `:hover:` and `:focus` on the li instead of using a JavaScript event listener...I don't know what problems this can cause if any.

Side note 2 : You will notice in this code that I am using BEM css methodology. I highly recommend giving it a read here : http://csswizardry.com/2013/01/mindbemding-getting-your-head-round-bem-syntax/

I really think this could make your css much much better and easier to maintain. (just a food for thought)

Hope this helps!

Stephen

**Comment by hsrudnicki** [comment]
Are you ready to close this issue?

**Comment by hsrudnicki** [comment]
Made "Going Stale" due to no further discussion to this issue's dilemma in order to close this issue or otherwise?  If you strongly think otherwise please update this issue's status again, thank you

**Comment by hsrudnicki** [comment]
Is this still an issue waiting for your consensus to resolve it?  Either way, please update this issue's status, whether this issue can be closed as resolved/fixed or if otherwise, thank you

**Comment by hsrudnicki** [comment]
Based on the above, this can be closed unless you still think strongly that this dilemma is an issue so please update the status of this again, thank you
