### ISSUE TITLE
Datepicker Redesign to Reduce User Errors 

### ISSUE THREAD

**Issue by neoinsight** [wet-boew/wet-boew#6558]
Last week, we had usability participants try to enter their date of birth via the datepicker. People had many problems that I will explain in other issues, but for now, would like to understand if this particular problem is a bug, because it looks like one. 

Participant opens the calendar, selects year and month, clicks GO, then clicks a day, and it reverts back to the current date.  On Chrome, it does NOT revert to the current date. Participant is on Firefox v35.0.1. See the video here (participant voice is disguised): http://www.youtube.com/watch?v=38FBlQud3wc

I can't replicate this on the latest version of firefox on a Mac. 

Working version is here. http://neoinsight.com/test/wetform1/exform2-en.html
I don't think it's a code problem because it worked for other people. 

<div class="form-group">
  <label for="bdate1"><span class="field-name">When were you born?</span>
  <span class="datepicker-format"> (YYYY-MM-DD)</span> </label>
<p> Please use your real date of birth - just switch the month to one month different from your own.</p>
<input class="form-control" id="bdate1" name="bdate1" type="date" data-rule-dateiso="true">
</div>

**Comment by LaurentGoderre** [comment]
@neoinsight Chrome use a native date picker so it wouldn't be affected. We will need to investigate in Firefox though.

**Comment by neoinsight** [comment]
Another potential bug - notice how it blacks out on the participant using Chrome v35.0.1916.114 m 
https://www.youtube.com/watch?v=bx3kR8xJa48

**Comment by LaurentGoderre** [comment]
That is a bug with Google Chrome, not WET4

**Comment by LaurentGoderre** [comment]
I am unable to reproduce in Firefox

**Comment by LaurentGoderre** [comment]
@neoinsight by analyzing the video, I can conclude with reasonable confidence that what occured is user error and that may indicate that the way the go to behavior works needs to be revised.

The user goes into the go to section and changes the year and month, doesn't press "Go" which is required to actually change the calendar view but instead click on the day number. The computer then lags a bit and the date that is selected is in fact the first of the current month (as was being displayed by the calendar since It wasn't refreshed. The second time I don't quite know what happened  but it could be a lag that caused it.

**Comment by neoinsight** [comment]
Ah ok! Thanks. The Go behaviour is a problem for sure. More videos to come. Could close this then.

**Comment by LaurentGoderre** [comment]
Can you open a new issue requesting that we get rid the go button and implement a redraw of the calendar when either the month or year change. Doing this is risky because you don't want to cause it to fail WCAG 2.0 Success Criterion 3.2.2 On Input but if the focus is properly managed there can probably be some significant usability gains.

P.S. it's pretty cool to see those videos of users. If every developer got the chance to see users use their software I am sure development would be very different.

**Comment by neoinsight** [comment]
Absolutely right about videos. I will make more available. Lots to discuss about datepicker before coming up with soutions - Peter will book a meeting.

**Comment by neoinsight** [comment]
Do you think this is the same bug? This one is on Chrome, but same problem of clicking day on calendar and losing the year and month. Voice is disguised. 
https://www.youtube.com/watch?v=xGXch7-MYPo

**Comment by LaurentGoderre** [comment]
@neoinsight that date picker is Chrome's native implementation and WET has no part in it. I did notice though that you can't type anything while the date picker is opened and from the video typing in a value does not update the calendar.

That being said, I doubt the behavior demonstrated in this video is covered by the spec so perhaps the spec need to be updated to improve usability.

**Comment by thomasgohard** [comment]
Related issue: https://github.com/wet-boew/wet-boew/issues/6143.

**Comment by LaurentGoderre** [comment]
@pcwsmith @neoinsight what do you think about this prototype

![datepickerprototype](https://cloud.githubusercontent.com/assets/1090826/6450761/17434728-c0f8-11e4-8c0f-0e9650d7ee5e.PNG)

**Comment by neoinsight** [comment]
Oh hey, that would really help! Year is obvious, and no Go button.

**Comment by LaurentGoderre** [comment]
Here's an updated look
![datepickerprototype2](https://cloud.githubusercontent.com/assets/1090826/6468321/480f0c84-c1a2-11e4-8797-a71675696133.PNG)

**Comment by LaurentGoderre** [comment]
@neoinsight one issue I have with this design is I have nowhere to put an icon for closing the dialog. Selecting a value, clicking outside or pressing escape all close the dialog but is that enough or do we absolutely need a close icon?

**Comment by neoinsight** [comment]
Everyone I saw clicked outside to close. I didn't even know there was a close icon! So I think we could live without it. Tabbing to next field would close it too?

**Comment by LaurentGoderre** [comment]
Not sure.....it would depend on the keyboard navigation we would decide one. If arrow keys navigate in the calendar then tab key could move the cursor to the next field or element in the tabindex (a bit like the menu behaves) What do you think?

**Comment by neoinsight** [comment]
Right now, tabbing won't open the calendar at all anyway. Tab stays in the text field for the date which makes most sense for a screenreader user. So goes from YYYY, to MM to DD to next field. Not sure how a screenreader user could even open the calendar. But if they do, tabbing gets stuck in it - can't get out via tab. So let's do what you suggest above, move to next element in the tabindex.

**Comment by LaurentGoderre** [comment]
@dfarough @mysticjeff what do you think about that?

**Comment by pjackson28** [comment]
Note that the keyboard navigation was modelled after the WAI-ARIA authoring practices design pattern for the date picker (http://www.w3.org/TR/wai-aria-practices/#datepicker) so we should ensure that at a minimum we stay aligned with those. It is very specific about keyboard begaviour.

Also a comment about a close button, we have it on all other overlays and popups so it would probably be a good idea to remain consistent. Couldn't we add more vertical height to the header to fit the close button?

**Comment by LaurentGoderre** [comment]
The date picker isn't quite like an overlay though and adding the button is likely to cause issues on touch devices when the user will accidentally touch the close button instead of the next button.

**Comment by LaurentGoderre** [comment]
Also....Ctrl-PageUp changes tabs in Firefox which mean that we can't implement it in a way where it meets everyone's expectations. Also it seems like those instructions would make sense to a screen reader user(except for the change year) bit not necessarily to a sighted keyboard only user.

It seems like the current one isn't meeting the ARIA spec exactly either so I think we will have to create a hybrid.

**Comment by pjackson28** [comment]
We can add additional keyboard support but the minimum should still meet what is required by WAI-ARIA. We could do more harm than good if we are faithful to the WAI-ARIA states and properties but not the keyboard requirements. That happened a while back with the menu bar where we went with a hybrid keyboard approach (supported arrows and tabbing) and it ended up causing a lot of screen reader user confusion so we had to remove the tabbing support (received a lot of feedback on that).

As for the close button, it is very common on popups, widgets, OS components, etc. It is normally a good thing to have multiple ways disclosing things, particularly an approach that is quite common. As for the accidental clicking risk, that is a proximity/spacing issue, not an issue with the button being provided. If there is a risk of accidental activation hen increase the spacing between the buttons.

**Comment by LaurentGoderre** [comment]
that would make the calendar widget HUGE though

**Comment by pjackson28** [comment]
Then that would be the case for every other popup, OS component, OS window (including browser windows and tabs), etc. out there. They all make room to fit the "X" button in their interfaces so I don't see why it would be an issue here. Why would we go against the common convention just to save some space?

**Comment by dfarough** [comment]
First of all I think that loosing the close button would cause problems for some users.  having more ways to exit is best I think.

What are those buttons for?  do they move back and forward a year, or by a month?  If you get to select the month and year, are they really necessary?

If we are trying to keep to AREA keyboard behaviour, then we need to fix the arrow navigation within the date grid.  Down arrow is supposed to move down to the same day in the following week.  Right and left arrows should move back and forward by a day in the same week.

This used to work if memory serves me.

**Comment by LaurentGoderre** [comment]
@neoinsight do you think the arrows have value? I think that perhaps they provide a bit more speed in some scenario but maybe we can get away with removing them.

**Comment by neoinsight** [comment]
The arrows have value for short-term dates. People definitely used them and expect them to move by a month. Agree they duplicate the month picker, but for just one or two months, it's faster - especially when looking at choosing a date that's at the end or beginning of a month.

**Comment by mysticjeff** [comment]
I agree with David on this.  

-----Original Message-----

**Comment by neoinsight** [comment]
As you continue to work on the datepicker, another issue arose as a participant typed in their response without using the hyphens - she was unable to understand the error message. See the video below. 
https://www.youtube.com/watch?v=hGtHEzgyRdQ

We know from the same set of test sessions and other research that people ignore formatting instructions. In this study for example, more than half of the people didn't put dashes into the telephone number, despite placeholders and formats in the label. 

The recommendation is that the code should handle the format, not the user. So if they miss the dashes, it should accept the date, not give an error message. 

In a truly usable design (to keep in mind for someday), it would change the dates into words, so that people can tell they got the date correct. In the participant's case, it would display '1986 September 17' so that she can look and confirm that the month and day are correct, since the browsers/settings are causing the dates to be displayed in different formats for everyone.

**Comment by LaurentGoderre** [comment]
These validation rules come from an upstream dependency (jQuery validation) and I think they probably require the dash to determine the date. For example, what date is 20132015?

The displaying in text is not something we control and browsers would need to implement it. In that case, it will also mean a ton of people asking us why the date is displayed in English on a french page (like is happenning for the Browse buttons)

**Comment by neoinsight** [comment]
@LaurentGoderre Darn, I wondered if that might be the case. Note though that missing dashes are different from an actual invalid date, like your example of 20132015. Also, we didn't see people make mistakes in terms of getting the month and day order wrong.

Certainly the date format differences across just our small set of 24 participants was startling. Of the computer users, 13 showed date as YYYY-MM-DD, 4 displayed MM/DD/YYYY and another 4 displayed it as DD/MM/YYYY. What a range.

Ok, well, just wanted to mention it - in case the opportunity arises in the future to handle it.

**Comment by LaurentGoderre** [comment]
The display is awefull but at least the spec says that all dates returned are in ISO format (YYYY-MM-DD)

**Comment by LaurentGoderre** [comment]
Here is an early look at the new date picker. There's still a lot of work before it's ready but it's getting there.

http://laurentgoderre.github.io/wet-boew/demos/datepicker/datepicker-en.html

**Comment by thomasgohard** [comment]
@LaurentGoderre what about greying out the dates that cannot be selected? I find that there's very little visual contrast between the selectable and unselectable dates. The only visual difference is the underline, which is short as the dates are short.

**Comment by LaurentGoderre** [comment]
agreed!

**Comment by LaurentGoderre** [comment]
How does this look

![datepickerdisabled](https://cloud.githubusercontent.com/assets/1090826/7374534/e45787f4-eda0-11e4-9315-9a4f26e57104.PNG)

**Comment by neoinsight** [comment]
@LaurentGoderre Great to see this start to come together. The greying out is better from my point of view, and seems to be the convention. I tried it on Chrome and still saw the original - am assuming that's part of the work to come.

**Comment by thomasgohard** [comment]
@LaurentGoderre perfect.

**Comment by LaurentGoderre** [comment]
@neoinsight Chrome won't display this one since it has a native implementation

**Comment by neoinsight** [comment]
Ohhh. But so many of our participants were on Chrome, and the Chrome implementation really hurt task success. I misunderstood that this would override the native Chrome because it's polyfill.

**Comment by dfarough** [comment]
I am not able to access any of the controls within the calendar widget.  When I open the calendar and tab to the controls, my focus goes to the end date totally missing the controls within the widget.

**Comment by LaurentGoderre** [comment]
@dfarough as I said, this is by no means ready and it only a preview of how things are progressing

**Comment by neoinsight** [comment]
I really like the distinction between the year and the month. Anyone else feel that year should be after the month (to the right)? The way the year is first made me wonder how the arrows would work, whereas I have the impression that year to right would make me confident that the arrows will just move between months.

**Comment by RobJohnston** [comment]
After you mentioned it, I thought that the year first was a bit odd, but the format asked for entering dates is year-month-day, so that makes sense to me.  I also thought that the left arrow might change the year.  Would putting the arrows on either side of the month be better?

**Comment by neoinsight** [comment]
@RobJohnston Ah right, year-month-day. Although the browsers change that on people all the time - many of the participants so far have seen a different order. But yes, absolutely, moving the arrows so they flank month would make it much clearer.

**Comment by LaurentGoderre** [comment]
I think I would wait for test results before making a big change like that

**Comment by neoinsight** [comment]
@LaurentGoderre Fair enough!

**Comment by LaurentGoderre** [comment]
We will need to compile a list of videos of users failing to use the control and then submit it to the Chromium open source project and hope they fix it. We can't override native functionality.

**Comment by dravas-nat** [comment]
@LaurentGoderre :  I have been following this thread for improving the calendar widget. good discussion!
I agree with @neoinsight that moving the left arrow closer to the month would respect the affordance principle to give clues that this arrow works with the month.

**Comment by LaurentGoderre** [comment]
Unfortunately this should have come earlier before I created a new version. Changing it would cause too much of a delay so we will implement as is, test then improve again. It's already taking a really long time to land.

**Comment by neoinsight** [comment]
@LaurentGoderre Sure, sounds good.

**Comment by LaurentGoderre** [comment]
@dfarough I updated the example. There are still bugs but it's closer now to the finished product

**Comment by dfarough** [comment]
@wet-boew/access-working-group 
@LaurentGoderre What other changes do you plan to make?

I am wondering about putting the calendar grid within the application role.
I am also thinking that focus should go there immediately when the dialogue opens so that keyboard users do not have to tab through all the controls within the top part of the dialogue.

I think that we should also provide keyboard  shortcuts for the next and previous functionality for month and year.

Perhaps for this widget  we should also provide a help option much like we aree doing for the menus which explains the keystrokes that can be  use to work this widget.

**Comment by LaurentGoderre** [comment]
There are shortcuts for next/previous year/month (Page UP and Down according to the ARIA spec).

Moving the focus to days directly may not be the best for sighted keyboard only users.

**Comment by LaurentGoderre** [comment]
The last thing needed is closing the calendar when focus leaves it

**Comment by dravas-nat** [comment]
@LaurentGoderre  where could I see the latest version you are working on?
is it on this page? :
http://laurentgoderre.github.io/wet-boew/demos/datepicker/datepicker-en.html

**Comment by LaurentGoderre** [comment]
Yep

**Comment by dfarough** [comment]
I am noticing a few things that I will point out here.

1.  When focussed on a date in the calendar grid, The screen reader is not  reporting the focussed date properly.  I got the following when focussed on Wednesd March 27.
Wednesday, March 272013 Link  There needs to be s space between the day and the year.

2.  When you close the calendar, the focus  moves to the date edit field rather than the control that opened the calendar.

3.  After the calendar has been opened, the button that opens the calendar is reported as 
"Close: calendar (escape key) Link".  I notice that the title is being changed.

4.  The keyboard shortcuts that have been programmed in to this widget are not being reported to Access technologies.

5.  The application role is not being used for the calendar grid.  This makes it necessary for a Jaws user to turn off the virtual cursor in order to make the arrow keys work.  This will lead to confusion when using this widget.

6.  I think that we need to simplify this widget.  I feel that there is far too much redundant functionality for a keyboard user to tab through before they even get to the point where they can select a date in the calendar grid. 

Do all of these controls really need to come before the calendar grid?  Would it not make sense if they followed the calendar grid so that a user could tab to them if necessary.  This way a user could hit enter on the selected date if selecting a different year or month was not necessary.

**Comment by LaurentGoderre** [comment]
1. There are spaces there....I don't know why your screen reader doesn't read them here is what I copied from the control: Wednesday May 1 2013. Perhaps it needs a coma?

2. Why would it need to go to the control and not the field. If they cancel the date picker selection they may want to enter it by hand

3. This is correct since clicking on the button again will close the date picker.

**Comment by LaurentGoderre** [comment]
Number 6 needs to be tested with users using various technology I am really concerned about confusing the keyboard-only users.

**Comment by dfarough** [comment]
1.  I don't know why it did not include a space, but I can say that both Jaws and NVDA did the same thing, so it is definitely getting the value from somewhere.

2.  It is usually done to put the user back to where they were before the dialogue was opened.  It is just as likely that they might want to move forward from that point.  At least if the focus moves back to the button this would be the behaviour that the user would expect.  then the user can decide where next to go.

3.  Perhaps I was not clear.  I had closed the dialogue with the close button.  the button which is supposed to open the calendar had the message about closing the calendar, not the message indicating to pick a date from the calendar for the related field.  I am assuming that you will be putting the functionality back that closes the widget when clicking or tabbing out of the dialogue.

for 6, I don't see what would be so confusing.  If the focus is obvious it would be pretty intuitive just to tab out of the grid to get to the controls to change the year or month

I did notice that perhaps a border around the calendar grid would help define the dialogue.  It seemed to me that the text behind the widget did kind of blend in with the calendar .grid.  I think a border might help.

**Comment by dfarough** [comment]
With regard to #1  I was referring to the value that is spoken by the screen reader when using the arrow keys to select a day in the grid.  It is this value that appears to be the problem.  When I pasted the text that Jaws was speaking, I used the Jaws Speech history facility to obtain the text that was spoken by Jaws.

With regard to the focus issue I mentioned for #2  I notice that if selecting a date by pressing enter on the chosen date, that  focus moves back to the date field rather than the calendar picker button.  For a keyboard user, this is even worse since it necessitates pressing tab twice to advance through the controls.

**Comment by LaurentGoderre** [comment]
Ok for #3 I probably don't switch it back.

For #2 It's probably a bug with JAWS because the space is there. Maybe adding a comma will help. Did you test in the french side?

**Comment by SBleeks** [comment]
I’ll take a look at this with various screen reader browser combinations and try changing JAWS number processing settings to see if it makes a difference.

**Comment by dfarough** [comment]
I tested the French sample and it is fine.  

I also noticed that when using the English sample, when I open the date picker dialogue, Jaws starts reading everything in the dialogue including all the dates in the calendar grid.  Jaws did not do this for the French example.

**Comment by LaurentGoderre** [comment]
I wonder if JAWS and NVDA automatically ignores space between numbers. Because in french there is text between numbers that behavior doesn't occur. so instead of May 27 2013, it should be May 27, 2013

**Comment by dfarough** [comment]
You could always try adding the coma following the day

**Comment by dfarough** [comment]
@wet-boew/access-working-group 
I particularly like Bryan Gariventa's date picker widget.
http://whatsock.com/modules/aria_calendar_module/demo.htm
for the following reasons.
1.  focus is placed in the calendar grid when the calendar is opened.
2.  screen reader users will not need to turn off the virtual cursor in order to select a date in the grid.
3.  the new date is spoken when the user arrows through dates in the calendar grid. 
4.  after making a selection or closing the calendar focus moves back to the element that opened the calendar.

Bryan is involved in the WaiAria working group and has a good knowledge of the guidelines and Aria practices.

I also think that it would be a good idea for us to incorporate some instructions for using this widget in our datepicker.  this could be designed like we have proposed for our topic menus.

I notice that Bryan has used page up and page down to go back and forward a month and alt plus page up and alt plus page down to go back and forward by a year.

**Comment by LaurentGoderre** [comment]
We already have page up/down and alt + page up/down for month and year navigation

**Comment by hsrudnicki** [comment]
Are you ready to close this issue?

**Comment by neoinsight** [comment]
@hsrudnicki The team is hard at work on this one, and we will not close it until we have usability tested with mobile, desktop and screenreader participants late in the summer.

**Comment by hsrudnicki** [comment]
Now we are in December, so again the same question: Can be this issue, just labeled as "Going Stale", closed or otherwise? Please update this issue's status.
Thank you,

**Comment by neoinsight** [comment]
@hsrudnicki. thanks for bring this to our attention. 

@masterbee is aware that @pcwsmith and others in the GC are waiting to see a solution to the problems of the date picker. And  @pjackson28 and the applications team will definitely need a solution as more WET applications come online over the next year. 

In fact, I received an email from a GC applications team a few months ago asking for advice. They said their users were entering incorrect dates when they tried to use the date picker to enter a date from a previous year into a form. This is the very problem we identified here. 

So it may be stale, but the lack of a solution from the WET team is not a viable reason for me to close it.
