### ISSUE TITLE
Tabbed Interface: Geomap: Don't play nice together

### ISSUE THREAD

**Issue by shawnthompson** [wet-boew/wet-boew#6570]
I tried to put a geomap inside a tabbed interface and the map would not load.

Here's an [example page](http://servicecanada.github.io/GCWeb/contact/find-en.html).

This page is a draft and might be updated or deleted so if someone goes to check it and it's not there, let me know and I'll put it back up.

This has been tested on the tabs demo page and same thing happens there.

**Comment by LaurentGoderre** [comment]
@jvanulde can you look into this?

**Comment by pjackson28** [comment]
@shawnthompson Could you please describe what the incorrect behaviour is? I'm assuming it has something to do with Geomap injecting some of the content outside of the tabbed interface but just wanted to confirm what is the actual issue (also makes for more helpful issue tracking).

**Comment by shawnthompson** [comment]
The geomap will not show up inside the tabs, I had to move it outside of the tabs to show the client what it would look like if it did show up.

**Comment by pjackson28** [comment]
@shawnthompson Did it show up for you at all in the tabs? When I tried it, some content (not the maps) appeared in the tap panel while the rest (including the maps) appeared below the tab panel. Did you experience that behaviour as well?

**Comment by shawnthompson** [comment]
@pjackson28, It didn't show up at all but I'll try it again and let you know

**Comment by shawnthompson** [comment]
@pjackson28 , I updated my [sample page](http://servicecanada.github.io/GCWeb/contact/find-en.html)

**Comment by shawnthompson** [comment]
same results

**Comment by pjackson28** [comment]
I think I know what the issue is. I think Geomap caches a reference to the map container (and possibly other containers) which gets lost when the Tabbed interface gets enhanced, since the enhancement involves DOM changes. Those DOM changes are invalidating the previous reference to the map container (since it is a descendent of the elements that underwent DOM changes). Since the reference to the map container is lost, Geomap has nowhere to inject the map.

@jvanulde The way we've dealt with this in other plugins is we store the id of the element rather than a reference to the element itself. It is a very inexpensive operation to find an element by id so we don't have to cache an object indefinitely. It is fine to cache the element for the duration of a function or a sequential (uninterrupted) set of steps but any time you are starting the executing of code as a result of an event or outside trigger then you should get the element fresh with the id.

**Comment by pjackson28** [comment]
@jvanulde I think the problem is in geomap-lib.js and how you are using <code>mapArray</code>. For instance you have getMapById and getMap which retrieve a cached reference based upon an id (rather than getting the map fresh).

A possible short term workaround (if it will take a while to deal with the invalidated object caching issue) would be to initialize Geomap after the Tab Interface is ready (either by having the Geomap plugin stalling initialization if it detects wb-tabs as an ancestor and waiting until the Tabbed interface has initialized or by injecting the Geomap markup after the Tabbed interface is ready and then manually initializing the plugin (e.g., with wb-init.wb-geomap).

**Comment by jvanulde** [comment]
Without diving into the code I can't see how the mapArray would affect the initialization of a map. As far as I can tell, the only fix would be to have the initialization hold until the parent tab has been inited. I will look into this. Other ideas welcome.

**Comment by jvanulde** [comment]
@pjackson28 I am able to solve this by reordering the plugin initialization. Is there way that we can initialize the tabbed interface before all the other plugins, or at least Geomap?

**Comment by LaurentGoderre** [comment]
I don't think this can easily be done....

**Comment by jvanulde** [comment]
@LaurentGoderre all we need to do is edit the Gruntfile as follows:

    ...
    "src/core/helpers.js"
    "src/plugins/tabs/*.js"
    "src/plugins/**/*.js"
    ...

**Comment by LaurentGoderre** [comment]
If we start that...we may never see the end of the priority changes

**Comment by jvanulde** [comment]
Tabs are unique though in that plugins are typically loaded into them. The only other workaround is to have other plugins (e.g. Geomap) check for a parent tabs plugin and delay init. That seems a bit heavy handed. If we want to do that then the tabs plugin should have a refresh plugin method like Geomap does.

**Comment by LaurentGoderre** [comment]
I know, I know...there is no good solution, just leas bad one. Next version of the tabbed interface shouldn't change the DOM so much so it could just be a temporary measure

**Comment by jvanulde** [comment]
@LaurentGoderre @pjackson28 can we agree on a solution? I don't want to start in on a Geomap plugin fix until we are clear on the best way to address this.

**Comment by pjackson28** [comment]
@LaurentGoderre The challenge with reducing the tabbed interface DOM changes is it means a lot more markup markup for implementers to put in place (correctly). That will mean major breaking changes. Besides, it would be nothing more than a bandaid and doesn't address the root cause.

What I suggest instead is to fix up the nesting handling in timerpoke (https://github.com/wet-boew/wet-boew/blob/master/src/core/wb.js#L283-L310). Currently it handles nesting of the same type (tabs inside of tabs) but it should be expanded to handle nesting of other types. Regardless of whether or not there are DOM changes, the parent should always be handled before any of its children. This should be handled in timerpoke and not at the plugin level.

**Comment by LaurentGoderre** [comment]
Agreed but this is no simple change. It would require an overhaul on how plugins are loaded.

**Comment by pjackson28** [comment]
PR #6663 fixes the issue. Tested successfully with the dynamic and static maps nested in a tabbed interface.

**Comment by LaurentGoderre** [comment]
This was fixed
