### ISSUE TITLE
Dismissable alert

### ISSUE THREAD

**Issue by b0uch3** [wet-boew/wet-boew#6575]
Has the dismissable option for alerts been removed from the bootstrap base functionality?  If so, why isn't it included?  

I noticed the documentation still mentions it, but the example is not listed in the [working example](http://wet-boew.github.io/wet-boew-styleguide/v4/design/alerts-en.html)

*Wrap any text and an optional dismiss button in .alert and one of the four contextual classes*

**Comment by LaurentGoderre** [comment]
@b0uch3 we do not use the Bootstrap components. I believe we have a solution on the way for this. Was it you @Pacoup that was working on it?

**Comment by pjackson28** [comment]
We use [collapsible alerts](http://wet-boew.github.io/v4.0-ci/demos/collapsible-alerts/collapsible-alerts-en.html) instead as it was determined that the alerts should still be available, just taking up considerably less space.

**Comment by Pacoup** [comment]
@LaurentGoderre Yup.

@b0uch3 And @pjackson28 is right, we did collapsible alerts instead.

**Comment by LaurentGoderre** [comment]
@b0uch3 does that work for you?

**Comment by b0uch3** [comment]
For a good number of alert cases I am running into, dismissal of the message and panel is preferred.  Otherwise we are left with a coloured panel and arrow that isn't needed on screen anymore.  Messages like "Successfully signed out" or "Record has been updated" do not need to persist.  There are really an unending set of cases where an alert can be dismissed.   

In contrast, messages like a Privacy Statement will work fine as a collapsible alert/message.   

Since it's already an option in the base bootstrap framework, it'd be great to have access to it out of the WET box.

**Comment by pjackson28** [comment]
There are no plans at this point to implement the Bootstrap JS (we only use the CSS framework). Why would you require the user to dismiss those messages? If they are no longer needed, and are transitory in nature, then you should remove them automatically (e.g., once the user has proceeded with other actions) and not require the user to put in the effort to dismiss the messages (particularly annoying for keyboard users).

Also using alerts like that is likely not good from an accessibility standpoint since you are probably adding the alert to the page without a page refresh (so there is no way for a screen reader to know that you added the message). You should look into creating an aria-live region (or using a specific WAI-ARIA role such as [role="status"](http://www.w3.org/TR/wai-aria/roles#status) or [role="log"](http://www.w3.org/TR/wai-aria/roles#log)) which safely (and politely) informs the user about such non-urgent information. That region can be made to look like an informational alert but every time you update the message in that region it will be available to all users.

**Comment by b0uch3** [comment]
I didn't realize that none of the JS were included. The alerts are typically added via a postback.  It'd be nice to provide the ability to dismiss them for the majority of users though.

**Comment by pjackson28** [comment]
I was more suggesting having a status messages area (or even a log area) rather than adding a new alert for each item. That way you can have a clear messages button if you don't want to remove the messages automatically (and users can dismiss all messages at once rather than one at a time) and can make it an aria-live region so screen readers will actually get the messages. That way you could just use a regular alert or a collapsible alert and then dynamically control the contents within (or create another area for displaying the messages if you like). You could even let it have a scroll bar for overflowing content if you want the messages to have some form of persistence. Also, if they don't want to see the messages then they can just collapse the area.

**Comment by hsrudnicki** [comment]
Are you ready to close this issue?

**Comment by pjackson28** [comment]
Closing since WET now includes collapsible alerts and dismissible content.
