### ISSUE TITLE
Date picker: No visible area to trigger picker when icon is missing

### ISSUE THREAD

**Issue by NPhilouze** [wet-boew/wet-boew#6599]
Most browsers have the ability to force font styles which results in icons not being displayed.
Since the date picker polyfill is triggered by clicking the calendar icon, the absence of icons affects its functionality:
Default fonts: ![old](https://cloud.githubusercontent.com/assets/11313678/6513872/34a507f6-c34c-11e4-9f05-6ff2dda87dfc.JPG)
Forced fonts: ![oldforcedfont](https://cloud.githubusercontent.com/assets/11313678/6513763/62a85bb8-c34b-11e4-9798-d654f0436a3f.JPG)

Wrapping the icon in a button, for example with input-group (http://wet-boew.github.io/wet-boew-styleguide/v4/design/forms-en.html#input-groups) would fix the issue:
Default fonts: ![new](https://cloud.githubusercontent.com/assets/11313678/6513804/aac5b260-c34b-11e4-93ba-9f65c5bed003.JPG)
Forced fonts: ![newforcedfont](https://cloud.githubusercontent.com/assets/11313678/6513810/ad0652f0-c34b-11e4-8869-da16bbc14762.JPG)

Thoughts on this bug and proposed fix?

**Comment by LaurentGoderre** [comment]
It's not quite a bug and this should really be fixed at the browser level but I do kind of link this is a fail safe. :+1:

@pcwsmith, what do you think?

**Comment by pjackson28** [comment]
Note that this originally was in a button but thanks to the overly aggressive form handling of IE, we had to change it to a link. That was because people were accidentally triggering the date picker when trying to submit the form (since IE was activating the first button it could find in the form). We could replicate the button look with CSS but we should be careful about implementing actual button markup unless we can prevent this unwanted behaviour from happening in IE.

**Comment by DK-TBS** [comment]
Hi @LaurentGoderre!  Dave here.  Peter sits next to me, and we both took a look... we both agree that the fix is worthwhile.  A blank box isn't ideal, but it's a hell of a lot better than seeing nothing at all.

Oddly enough, we suffer from the same problem here, but for a different reason.  Our browsers aren't doing any kind of forced fonts thing, but our firewall seems to smack down any and all icons that are implemented this way, so we're used to seeing little bits missing from canada.ca here and there.  But this does reveal another issue: testing the [datepicker polyfill](http://wet-boew.github.io/wet-boew/demos/datepicker/datepicker-en.html) here on our end shows that the icons being used *inside* the little pop-up calendar for next/previous month are also absent.  I'm guessing that these icons will also be affected by forced fonts the same way, which will cause additional trouble for users who get past the original blank-box problem we're talking about.

I don't suppose you happen to have an easy fix for the missing icons inside the calendar, eh?  Any ideas?  

Maybe we could adjust the polyfill to replace the prev/next icons with chevrons or angle bracket characters?

**Comment by DK-TBS** [comment]
Oh no, so even the button fix might not be an option?  Someone needs to find a way to just delete IE from the internet.

**Comment by shawnthompson** [comment]
:+1:

**Comment by NPhilouze** [comment]
While it's true that you won't see the arrows in the polyfill with forced fonts, you're still able to click the month and use the month and year dropdown menus.

I've replaced the button in my example to the <a> tag that was used initially changing input-group-btn to input-group-addon.
Since the clickable area is the icon itself, it's difficult to find it when it's not visible, even with the input group wrap. I replaced the padding on the input-group-addon span with padding on the <a> tag to make the whole area clickable.

The only downside I can find right now is that the dimension of the icon is 21px * 23px but the placeholder when the icon is missing is 13px * 21px. That 2px difference is height results in a minor misalignment:

Default fonts: ![default](https://cloud.githubusercontent.com/assets/11313678/6525855/ca56e1ac-c3d8-11e4-8386-20c97eba46cc.JPG)
Forced fonts: ![forcedfonts](https://cloud.githubusercontent.com/assets/11313678/6525945/0b5550b6-c3da-11e4-8018-9beb62f8ac26.JPG)

**Comment by LaurentGoderre** [comment]
@NPhilouze has a good point there!

**Comment by DK-TBS** [comment]
Very true;  the prev/next arrows are really only a convenience, a shortcut past the dropdown business.  Not having those icons is a smaller problem than the missing calendar button. 

Glad to see that the text field will still accept direct input, so none of this should represent a total barrier for users, at least.  The calendar is cute, but not crucial  :)

**Comment by LaurentGoderre** [comment]
@NPhilouze why did you close the issue?

**Comment by NPhilouze** [comment]
My bad, didn't mean to close the issue, only the pull request.

**Comment by hsrudnicki** [comment]
Are you ready to close this issue?

**Comment by LaurentGoderre** [comment]
No, this is still outstanding

**Comment by hsrudnicki** [comment]
Made "Going Stale" in order to close this issue as resolved based on the above milestone or if otherwise? Either way, please update this issue's status, thank you
