### ISSUE TITLE
wbdisable parameter?

### ISSUE THREAD

**Issue by josephbr** [wet-boew/wet-boew#6624]
What is the "wbdisable" parameter's purpose? It seems that adding "?wbdisable=true" to any page produces three links at the top of the header including "Skip to main content", "Skip to site information", and "Standard version". This came up when a co-worker found that Google had indexed one of these "?wbdisable=true" pages. Not sure how this can be when it is not linked anywhere. 

Is it safe to just add 	.wb-disable-inited{display:none;} in case someone lands on one of these pages or does it actually serve a purpose? It seems to also alter your session as the three links then start appearing on all pages until I add "?wbdisable=false" to the URL.

**Comment by pjackson28** [comment]
It is the progressive enhancement kill switch. If a user has difficulties with WET enhancements then they can turn them off with the "Basic HTML version" link which sets wbdisable to true (Standard version link is used to re-enable enhancements). This is primarily intended for users with very old AT that encounter difficulties with WAI-ARIA and other enhancements. 

Those three links are intended to be visible and should not be hidden with CSS as otherwise you prevent people from re-enabling the enhancements.

**Comment by josephbr** [comment]
Thanks for the explanation. I'll leave it as is then.
