### ISSUE TITLE
Details/summary polyfill no longer working

### ISSUE THREAD

**Issue by Christopher-O** [wet-boew/wet-boew#6639]
With the new update, and using the new wet-boew.min.js file, the details/summary polyfill function no longer works (in our template).  The arrows disappear and you can no longer click to make the hidden elements appear.  I am wondering if this may have something to do with the update to the tabs plug in, since it uses the detail and summary tags as well.  I tried putting in the 4.0.11 version of the wet-boew.min.js file instead and the plug-in works as expected.

**Comment by Christopher-O** [comment]
Need to investigate further, may be a miscommunication with the template and the wet-boew.min.js file.

**Comment by pjackson28** [comment]
I tried the live v4.0.12 working examples with Firefox (which doesn't have native support) and it worked fine for me. Also check to see if jQuery is being downloaded as you might get the same error if jQuery doesn't load (since jQuery is being downloaded from a CDN and is not included in the WET zip file).

**Comment by Christopher-O** [comment]
Hi Paul, thanks for looking into it, and I realized that the Polyfills were the issue.  I brought them over and it now works like a charm.
