### ISSUE TITLE
Change the location of the browser support documentation

### ISSUE THREAD

**Issue by LaurentGoderre** [wet-boew/wet-boew#6646]
Questions about browser support are coming up very often on that and the documentation for it is not easy to find. @thomasgohard @zachfalsetto can you come up with a recommendation on where we can put this information more visible?

**Comment by LaurentGoderre** [comment]
Secondarily, we have to surface the fact that IE89 is no longer supported. @pjackson28 and I were thinking about replacing the v3.1 notice with en IE8 notice.

**Comment by Ting-ChongMa** [comment]
My two cents draft:
We now use Canada.ca analytics for the basis of what we support.
We will not support any browser usage below 5%.

Therefore, for mobile devices, WET supports the current versions of:
•Safari - iOS
•Chrome - Android
•Android Browser

for desktop PCs, WET supports the previous and current versions of :
•Chrome
•Safari
•Firefox

WET supports IE9, IE10, IE11 (because we are seeing IE8 visits hovering around the 3% to 4% range).

**Comment by thomasgohard** [comment]
The WET 3.1 messaging is definitely due to be removed. We can reuse the space to advice that IE 8 and 9 are no longer supported.

I still say we should have a browser support page linked to from the front page, as well as a browser support section in the readme though. That would be the easiest way for people to find that information.

**Comment by Ting-ChongMa** [comment]
My two cents draft is changed to:
We now use Canada.ca analytics for the basis of what we support.
We will not support any browser usage below 5%.

Therefore, for mobile device, WET supports the current versions of:
•Safari - iOS
•Chrome - Android
•Android Browser

for desktop PC, WET supports the previous and current versions of :
•IE
•Chrome
•Safari
•Firefox

**Comment by LaurentGoderre** [comment]
@thomasgohard yeah, I was suggesting both. Perhaps the banner can link to the support page as well. Are you able to open a PR for this?

**Comment by thomasgohard** [comment]
Sure. I'll do that.

**Comment by pjackson28** [comment]
We should make it clear that we are not stripping out existing support, just that we will not be actively maintaining that support. So things will still likely work well on IE8 and IE9, but that we will treat any new issues raised for IE8 and IE9 as low priority (community can submit PRs to address issues quicker if they like).

**Comment by pjackson28** [comment]
As for the wording for what we support, we should be careful to oversimplify with just the 5%. The browser support criteria has three bullets to ensure we don't include/exclude too much so it is:
* The current and previous major version of each browser that accounts for at least 5 per cent of visits to the website;
* Any major version of a browser that, on its own, accounts for at least 5 per cent of visits to the website; and
* The current major version of each mobile browser that accounts for at least 5 per cent of mobile device visits.

**Comment by hsrudnicki** [comment]
Can this issue be closed or otherwise?

**Comment by hsrudnicki** [comment]
@thomasgohard and others: Please update this issue's status whether this issue can be closed or otherwise? Thank you in advance

**Comment by hsrudnicki** [comment]
Made "Going Stale" due to no further discussion, and no any PR yet, does it mean that this issue can be closed or otherwise?

**Comment by dcabasson** [comment]
So where is actually the said documentation? There is no pull request there or anything...

**Comment by hsrudnicki** [comment]
Please check if this issue can be referenced with the other issue: 5574 in regards to Documentation?  Either way, please keep the status of this issue updated, whether this issue can be closed as resolved or otherwise? Thank you

**Comment by hsrudnicki** [comment]
After referencing to #5574 to be included in the docs, can be this closed or otherwise?

**Comment by dcabasson** [comment]
I would recommend leaving that issue as is. 5574 looks like a mega issue that hasn't been touched in at least a year or 2 except for being reopened. I think tracking individual issues is more valuable than trying to pile all the issues into a single one.Denis                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: Hanna S RudnickiSent: mardi 20 septembre 2016 08:12To: wet-boew/wet-boewReply To: wet-boew/wet-boewCc: dcabasson; CommentSubject: Re: [wet-boew/wet-boew] Change the location of the browser support documentation (#6646)After referencing to #5574 to be included in the docs, can be this closed or otherwise?

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/wet-boew/wet-boew","title":"wet-boew/wet-boew","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/wet-boew/wet-boew"}},"updates":{"snippets":[{"icon":"PERSON","message":"@hsrudnicki in #6646: After referencing to #5574 to be included in the docs, can be this closed or otherwise?"}],"action":{"name":"View Issue","url":"https://github.com/wet-boew/wet-boew/issues/6646#issuecomment-248330154"}}}
