### ISSUE TITLE
angular js

### ISSUE THREAD

**Issue by jackp55** [wet-boew/wet-boew#6664]
Hi all.... can we use angular js on a GOC site?

thx

**Comment by LaurentGoderre** [comment]
Do you want to use it on a site or a web application?

**Comment by CalvinRodo** [comment]
We've used Knockoutjs pretty successfully with our web app here at esdc both internal and external. 

I would assume you would have to do some testing to make sure it works with your audience, for instance we couldn't use angular because we still have a requirement to support ie8 as a significant portion of our users still use ie8.

**Comment by hsrudnicki** [comment]
Are you ready to close this issue?

**Comment by jackp55** [comment]
thx guys, we're using angular here now... so far so good!

**Comment by LaurentGoderre** [comment]
Let me know if you have any questions
