### ISSUE TITLE
Relative links in print.css usability concerns with the GCWU theme

### ISSUE THREAD

**Issue by delisma** [wet-boew/wet-boew#6686]
Hi,

We are using the WET 4.0 and I'm wondering if it's possible to render relative links more usable in breadcrumb and "Header" with the print.css. As it can be seen in both screen captures, we can compare our test page and the WET 4.0 example GCWU.

On the WET 4.0 example site the home link in the breadcrumb is an absolute url which gives some kind of context to the user if the absolute url is not printed in the margins. In our test page, even with the absolute url in the margin, I don't know how useful the relative url is when we don't adhere to a meaningful url convention.

The subsite "Header" has been added by the dept. and even if we would add the absolute url it could still be hard to figure out for a regular user. We would also have to consider the different environments that we use in our workflow. So I don't know if it's something on our end that needs to be done or is it something that you can tackle?

**WET 4.0 GCWU example**
![WET 4.0 GCWU example with annotations](https://cloud.githubusercontent.com/assets/2599251/7137782/0adce594-e28a-11e4-8555-36ed54c7a148.png)

**Industry Canada subsite**
![Industry Canada subsite with annotations](https://cloud.githubusercontent.com/assets/2599251/7137781/0adb305a-e28a-11e4-940d-46cecf5f4698.png)

**Comment by thomasgohard** [comment]
You can't make a relative URL into an absolute URL using CSS. The reason that the URL in the WET page is an absolute URL is that it's an absolute URL in the markup.

The subsite banner is not part of the GCWU theme. That's something that you would have to address on your end.

**Comment by elismatiq** [comment]
So I could ask for a custom class to be added for the subsite banner to override the css for adding the URL after the a tag and that shouldn't be an issue in terms of usability?

**Comment by ElismaD** [comment]
So I could ask for a custom class to be added for the subsite banner to override the css for adding the URL after the a tag and that shouldn't be an issue in terms of usability?

**Comment by thomasgohard** [comment]
If the link has value, you could change it to an absolute link. Otherwise, yes, you would need to add custom CSS to hide the URL in the subsite banner.

**Comment by ElismaD** [comment]
How do we establish value would be my next question. But I do get what you mean. Could it be possible also to tweak the URL in the breadcrumb to with something like this:
<pre>
&lt;ol class="breadcrumb"&gt;
	&lt;li class="<b>stratpre1</b>"&gt;&lt;a href="<b>stratpre1.ic.gc.ca/eic/site/icgc.nsf/eng/home</b>" title="Home">Home&lt;/a&gt;&lt;/li&gt;
	&lt;li class="<b>icgcca</b>"&gt;&lt;a href="<b>www.ic.gc.ca/eic/site/icgc.nsf/eng/home</b>" title="Home">Home&lt;/a&gt;&lt;/li&gt;
	&lt;li&gt;&lt;a href="/eic/site/icgc.nsf/eng/h_07057.html" title="Weights and Measures"&gt;Weights and Measures&lt;/a&gt;&lt;/li&gt;
	&lt;li&gt;&lt;a href="../eng/home"&gt;Measurement Canada&lt;/a&gt;&lt;/li&gt;
&lt;/ol&gt;
</pre>
Considering that the "stratpre1" class shows content on the development server (stratpre1.ic.gc.ca) but hides it from view on  the Internet (www.ic.gc.ca) and "icgcca" class shows content on the development server (stratpre1.ic.gc.ca) and the Internet (www.ic.gc.ca). This looks like a quick fix for me, since available in our template. Might not be the best one but it could add context .

**Comment by thomasgohard** [comment]
> How do we establish value would be my next question.

User research.

As for your breadcrumb tweak, that would introduce usability and accessibility issues if you have two home links at the start. Nevermind that one of those would be pointing to your development environment and therefore be unavailable to your end-users.

But I'm not sure why you'd want two home links with absolute URLs in the breadcrumb in the first place: The URLs in the breadcrumb are not displayed when printing.

**Comment by LaurentGoderre** [comment]
This is a GCWU issue not a WET core one. This issue should be filed here
https://github.com/wet-boew/theme-gcwu-fegc

**Comment by thomasgohard** [comment]
@LaurentGoderre The treatment of URLs in the header when printing is common across themes though.

**Comment by LaurentGoderre** [comment]
Nevermind, it applies to all theme except GCWeb. I don;t think the URL should be displayed on the site title. Also we should consider making this title bigger because it's not obvious what it is. Or we could hide it altogether.

**Comment by thomasgohard** [comment]
I think we should keep the site title visible as it gives context to the breadcrumb. If there was no site title, it may not be possible to tell which site the page was printed from. But I agree that we should give it a different visual treatment to distinguish it from the breadcrumb.

As for printing the URL for the site title, we can suppress that too.

**Comment by LaurentGoderre** [comment]
Are you taking it on @thomasgohard?

**Comment by thomasgohard** [comment]
Yep. I'll take it on.

**Comment by ElismaD** [comment]
@thomasgohard The two home links idea was not meant to be both visible at the same time, but more like depending of the environment the theme is displayed at any given moment. I do concede that the suggestion looks more like a hack than a proper solution.

I guess that a proper solution should be a server-side implementation instead of client side one.

**Comment by thomasgohard** [comment]
But isn't the setting the value of the home link in the breadcrumb already handled by EPIC for both environments? You don't need to set an absolute URL for that link as it's never shown in the print version.

**Comment by ElismaD** [comment]
@thomasgohard Sorry I submitted my comment too quickly. Had to do a couple of edits.

**Comment by thomasgohard** [comment]
I think I understand what you mean: You mean that if a relative URL in the content is shown in the print version, e.g., `lm00115`, because the root of the URL changes for different subsites, the user may not know which subsite `lm00115` belongs to. Is that correct?

**Comment by ElismaD** [comment]
Dead on!

**Comment by ElismaD** [comment]
I hadn't realized that this issue may be a little bit complex than just changing one selector. There still the fact that we have no guidelines to make these links more human readable, therefore more usable.

**Comment by thomasgohard** [comment]
You're dealing with a special case here because Industry Canada has different URL roots for different subsites. Sites where the root remains constant wouldn't necessarily have that problem. That probably won't be a problem on Canada.ca for example.

That being said, relative URLs in the content aren't exactly "usable". The end-user would still need to figure out what the URL root is. And we don't want to force absolute URLs in the content when relative URLs will do.

Should we suppress showing relative URLs entirely in the print version?

Is there any value to showing URLs in the print version in the first place?

Also, there's an underlying assumption that the full URL of the printed page is somewhere on the printout. Is that always true?

**Comment by ElismaD** [comment]
>You're dealing with a special case here because Industry Canada has different URL roots for different subsites. Sites where the root remains constant wouldn't necessarily have that problem. That probably won't be a problem on Canada.ca for example.

This, I do agree completely, and I think that the concerned parties should come up with solution in conjunction. Because of the challenge on both sides.
>That being said, relative URLs in the content aren't exactly "usable". The end-user would still need to figure out what the URL root is. And we don't want to force absolute URLs in the content when relative URLs will do.

What I'm saying is that non-human readable or non-memorable relative URL are hard to figure out, if the user is not used to the file structure.
>Should we suppress showing relative URLs entirely in the print version?

I truly believe they bring a lot of value if the context is set properly
>Also, there's an underlying assumption that the full URL of the printed page is somewhere on the printout. Is that always true?

Not always true unfortunately, and we shouldn't rely on the user's print environment to give him context

**Comment by hsrudnicki** [comment]
@ElismaD @thomasgohard : Can this issue be closed?

**Comment by hsrudnicki** [comment]
Made "Going Stale" to close this issue as resolved/fixed due to the above or if otherwise? Either way, please update this issue's status, thank you

**Comment by hsrudnicki** [comment]
Is this still an issue waiting for your consensus to resolve it or otherwise?  Either way, please update this issue's status, whether this issue can be closed as resolved/fixed or if otherwise?  Thank you
