### ISSUE TITLE
HTMl Basic version - wbdisable parameter

### ISSUE THREAD

**Issue by hamdaneh** [wet-boew/wet-boew#6712]
Hi,
Is there documentation on what is the difference between basic and standard html version ? When we switch from standard to basic version (adding wbdisable=true in the url), we have errors creating datatables. I have the impression that some librariries are not loaded in the basic version.

Here is the exact error logged in the console 

wet-boew.min.js:11 (anonymous function)    : Uncaught TypeError: Cannot read property 'settings' of undefined

Thanks!

**Comment by pjackson28** [comment]
Basic HTML version means all enhancements are disabled. This is normally used by users with very old screen readers that have difficulty with the enhancements.

**Comment by hamdaneh** [comment]
What are those enhancements ? (just an example please)

**Comment by pjackson28** [comment]
All plugins and polyfills. It is nearly the same thing as turning JavaScript off.

**Comment by hamdaneh** [comment]
Ok :( The fact that datatables are not part of the librairies loaded is a big issue for us. We have been using them to populate search results. I can understand that polyfills are not included (or any advanced css functionality) but do not understand why datatables.min.js is not part of basic html version.

**Comment by LaurentGoderre** [comment]
@hamdaneh if datatables is not loaded, you should still get the table without the enhancement such as sorting and  searching

**Comment by hamdaneh** [comment]
No actually we don't get sorting at all, and whenever we want to refresh data with ajax, datatables.min.js is not there for that purpose. It is ok, we will have to include it when we detect a basic mode.

**Comment by pjackson28** [comment]
@hamdaneh The issue is the user has explicitly opted out of any enhancements so you should not be forcing DataTables on them. They have opted out of enhancements because their technology is unable to deal with the enhancements (creates barriers for them). So you shouldn't be providing anything more that the table without any enhancements. You can AJAX in the data into the table but there should be no sorting, searching or any other enhancements to that table.
