### ISSUE TITLE
Menu: Must press escape twice to close a sub-menu when a sub-menu item has focus

### ISSUE THREAD

**Issue by thomasgohard** [wet-boew/wet-boew#6731]
Steps to reproduce:
1. Load Web page (e.g., http://wet-boew.github.io/wet-boew/demos/index-en.html).
2. Tab to the menu.
3. Use the down arrow to select a sub-menu item.
4. Press escape. **Sub-menu will close and then re-open with not sub-item selected.**
5. Press escape. **Sub-menu will close and stay closed.**

The problem is probably linked to the selection of a sub-menu item as, if you follow the steps above without Step 3, you only need to press escape once to close the sub-menu.

**Comment by pjackson28** [comment]
It is because the first escape moves focus to the menu bar item and the second escape moves focus out of the menu bar. The submenu reopens on the first escape because of the focus shifting to the menu bar item. It doesn't on the second escape because the focus is outside of the menu. The purpose of the escape key in this case is to exit the submenu/menu bar rather than close it. You could extend it to be for closing the submenu and keeping it closed but that wasn't the primary focus of the action (was for keyboard navigation rather than visuals).

You could try to keep the submenu closed

**Comment by LaurentGoderre** [comment]
It does look behaves in an awkward manner. The first escape moves out of the menu, the second one makes it invisible. Could we simplify this so that the second escape does nothing...basically, the submenu would always be visible as long as the top menu item has focus.

**Comment by pjackson28** [comment]
Will be fixed by #6739. Just increased the timeout to prevent the submenu from reopening.
