### ISSUE TITLE
3rd level Left Nav

### ISSUE THREAD

**Issue by TinoTran-Work** [wet-boew/wet-boew#6774]
Hello,

We've added a third level to the site, but the left navigation is not indenting the 3rd level to mark it as another sub section. Does the left navigation only work for up to 2 levels?

Thanks!

**Comment by pjackson28** [comment]
The side menu is not intended to have that many levels (since it creates a lot of complexity for mobile users). Technically the menu can support it (including in the mobile panel) but the CSS hasn't been designed to handle that much nesting in the desktop view.

@thomasgohard @LaurentGoderre @zachfalsetto Could one of you please provide a link to the recommendations for side menu?

**Comment by thomasgohard** [comment]
It's at https://github.com/wet-boew/GCWeb/issues/776#issuecomment-65173962.

**Comment by hsrudnicki** [comment]
@TinoTran-Work @pjackson28 @thomasgohard : Can this issue be closed or otherwise?

**Comment by pjackson28** [comment]
Yes as the question was answered and a link to the relevant discussion was provided.
