### ISSUE TITLE
Changes to WET Core and Themes to simplify implementation by variants

### ISSUE THREAD

**Issue by LaurentGoderre** [wet-boew/wet-boew#6809]
To simplify the implementation of WET in variant I am proposing the following changes:

* [x] Merge wet-boew.css into theme.css and deprecate the use of wet-boew.css
* [x] Merge the unmin resources with the minified resources
* [x] Move theme resources into their own subfolder

/cc @pjackson28 @masterbee @sylus @jeffdavidgordon @upsonp

**Comment by pjackson28** [comment]
One risk is that this will result in an across the board markup change (merging two CSS files). If people forget to remove the old theme CSS file then it will override any newer changes in the merged CSS file. Should this be done globally at this point or just as part of the AEM variant? If we are doing it globally, how would it be versioned, communicated and managed?

I am unclear what is meant by merging the unminified and minified resources. Why would they be merged? Wouldn't that cause a lot of overlap and confusion having minified and unified files in the same directory (since that means duplicate JS, CSS, HTML, etc. files). Shouldn't we only be sending production (minified files) to a production server?

Not sure what you mean by moving theme resources into their own sub-folder. What would be the before and after? Are you meaning in the source repository or the dist repository or both?

How would we create streamlined packages? Isn't that the responsibility of variants rather than core and the themes? Or do you mean that variants would be responsible for creating the streamlined packages? Also what files would be included and what would be left out and where would this be done?

**Comment by pjackson28** [comment]
Also this seems to involve some pretty significant changes for a maintenance release (since this is tagged v4.0.15). What would be the impact on each of the repos as well as implementers?

**Comment by LaurentGoderre** [comment]
This should have no effect on the implementers, here is why:

1) The WET styles are integrated inside the theme file. The existing WET CSS files are kept so that it doesn't work even if you don't update your markup.

2) We would be merging the folders, having the minified and unminified source in the same folder

3) This would introduce a small markup change but this is something every variant needs. We may be able to address this without introducing the markup change.

**Comment by pjackson28** [comment]
1) Okay, so the fallback is an empty wet-boew.css file. Isn't it very misleading to call it a theme CSS file when we have a wet-boew JS file? The vast majority of that CSS file will be core yet we are calling it a theme CSS file. Shouldn't we instead merge into wet-boew.css and instead deprecate the theme.css file? There is the risk that people will think there is no wet-boew CSS file (since there is nothing to indicate that theme.css is WET unless you look inside). I recommend sticking with wet-boew.css and dropping theme.css if something has to go..

2) I still don't understand this one. Are you referring to the production files rather than the source? Why would we host minified and unminified HTML in the same folder? We currently have no suffix to differentiate the minified and unminified versions (only the folder is used to differentiate). Also what is the benefit of having all the minified and unminified files side by side in the same folder? Won't that increase the risk of people deploying and using unminified files?

3) What is currently the proposed before and after? I still am unclear as to what this involves. I don't even know which repository or repositories that the proposed changes will be made in.

**Comment by LaurentGoderre** [comment]
1) It has to be theme.css because it contains the WET styles compiled in the context of the theme. The variables allow customizing the styles to match your theme. It woulds be very confusing to have different wet-boew.css that are actually different. And to be fair, wet-boew.css is mostly bootstrap and it's not confusing anyone.

2) We are using both a folder and a suffix. The suffix makes it easier for instance to create a debug mode that switch to unminified. In the current context we have to do `<link rel="{{#if !minified}}unmin/{{/if}}css/wet-boew{{#if minified}}.min{{/if}}.css"/>

3) Before:

```html
<!--[if gte IE 9 | !IE ]><!-->
<link href="./assets/favicon.ico" rel="icon" type="image/x-icon" />
<link rel="stylesheet" href="./css/theme.css" />
<!--<![endif]-->

<!--[if lt IE 9]>
<link href="./assets/favicon.ico" rel="shortcut icon" />
<link rel="stylesheet" href="./css/ie8-theme.css" />
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.js"></script>
<script src="./js/ie8-wet-boew.js"></script>
<![endif]-->
```

After:

```html
<!--[if gte IE 9 | !IE ]><!-->
<link href="./assets/favicon.ico" rel="icon" type="image/x-icon" />
<link rel="stylesheet" href="./theme-gcwu-fegc/css/theme.css" />
<!--<![endif]-->

<!--[if lt IE 9]>
<link href="./assets/favicon.ico" rel="shortcut icon" />
<link rel="stylesheet" href="./theme-gcwu-fegc/css/ie8-theme.css" />
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.js"></script>
<script src="./js/ie8-wet-boew.js"></script>
<![endif]-->
```

**Comment by pjackson28** [comment]
1) We already have theme.css files that are the same in name but are different from theme to theme so I don't see how it is an issue with making wet-boew.css different from theme to theme. I also don't see how theme.css is any more helpful than wet-boew.css. The issue I am raising is how will people know that theme.css is WET short of looking at the comment block inside the file? Ultimately we are just producing a configured wet-boew.css file where the configurations are only a small part of the CSS file.

2) We aren't using a suffix for unminified HTML files. For example:
* demos/index-en.html
* unmin/demos/index-en.html
If we bring them into the same folder then we will have a naming conflict.

3) Since they downloaded the GCWU theme why would they need to have the CSS in the theme-gcwu-fegc folder in a folder that already has theme-gcwu-fegc (once they unzip)? Also with that convention you would have to do that for all assets (such as favicon.ico, all other images, all the theme-specific HTML, etc). What would be the benefit since there are no other conflicting files in that package? Wouldn't that just result in everything but the core JS and CSS files residing in a theme-gcwu-fegc folder? That seems to be a lot of markup changes with little actual benefit.

**Comment by LaurentGoderre** [comment]
1) We could name it wet-boew-theme.css if we are already changing the markup

2) We would not change the HTML, just the source files so JS and CSS

3) For variants this is a nightmare if you want to provide multiple theme because there are collisions etc. The benefits of this for variants manager are huge and they have been asking for this for a while.

**Comment by pjackson28** [comment]
1) Do we have to change the markup? I think we should first be planning out the variant-centric global view to folder structures (as covered in the 3rd item) before we decide upon any markup changes. If we do end up making markup changes then a name change likely wouldn't create any further issue. Although if we do end up grouping core files separate from theme files, we wouldn't need "theme" in the filename any more (since the folder structure would be identifying it as theme-specific so adding theme would be redundant).

2) I'm not sure I understand. What do you mean by source files? These is no unmin/min until after the build. Were you just referring to the post-build supporting files (e.g., JS and CSS)? If so, how would we deal with the minified and unminified HTML? We grouped all the unminified and minified files in separate folders but are you saying the unminified HTML files would stay where they are and the unminified JS and CSS files would move out of the unmin folder? If so, how does this help? Is there a reason we should be doing this? Would we be deploying unminified files to production servers alongside minified files?

3) So you want to group everything but the core JS and CSS in a theme folder within a folder that already has the theme name in it? So theme-gcwu-fegc/theme-gcwu-fegc/css/theme.css (since the files are available in a zip file that includes the theme name)? Wouldn't it make more sense to group the core files in a core folder?

I think we are getting mixed up by focusing on the changes to each individual theme. Since this is supposed to be a variant-centric approach, we should first propose a global folder structure for a multi-theme variant implementation (so maybe a global core folder alongside theme folders), then worry about actually getting that implemented in the themes later. I don't have a good grasp of what you are proposing for a multi-theme variant folder implementation at this point.

**Comment by pjackson28** [comment]
Would a global variant-centric structure be something like this?
* *.html
* demos/*.html
* docs/*.html
* core/css
* core/js
* core/fonts
* core/assets
* wet-boew/*.html
* wet-boew/css
* wet-boew/assets
* GCWeb/*.html
* GCWeb/css
* GCWeb/assets
* theme-gcwu-fegc/*.html
* theme-gcwu-fegc/css
* theme-gcwu-fegc/assets

**Comment by LaurentGoderre** [comment]
The structure needs to be independent to give flexibility so that the theme folder can either be nested or separate altogether

**Comment by pjackson28** [comment]
So what are you proposing then for the global end result as well as the individual themes? You said that variants are having difficulty with clashes so what global grouping are you proposing to avoid that? If the above structure works globally then you could always have that grouping within each of the zip files (so have root, core and named theme folders in each theme so when all themes are unzipped in the same folder, only root and core will overlap and would safely overwrite the previous theme).

**Comment by jeffdavidgordon** [comment]
The way my variant, WET-BOEW-SSI does it is rename the production dist folder for each theme.    So the complete folder structure ends up being something like:
demos-ssi
dist-ssi
dist-wet-boew
dist-gcwu-fegc
dist-gc-intranet

dist-ssi also contains some theme specific stuff but it's only SSI related items.

**Comment by LaurentGoderre** [comment]
@jeffdavidgordon with the changes I proposed you will ber able to keep it that way, in gfact it probably be simpler to manage it.

**Comment by LaurentGoderre** [comment]
After a discussion with @pjackson28 this is what we agreed on:

1) Merge the unmin and min resources (JS, CSS and assets) and modify the working examples accordingly

2) Merge the wet-boew.css and theme.css (though I am not sure we agreed on the name yet)

3) Move the theme resources files in a separate folder but keep these files in the old location to avoid breaking existing implementations

Anything to add @pjackson28 ?

**Comment by LaurentGoderre** [comment]
Correction, we will move core and theme resources in their respective folders

**Comment by pjackson28** [comment]
@LaurentGoderre Looks good to me.

**Comment by hsrudnicki** [comment]
@LaurentGoderre and others: Can this issue be closed?
