### ISSUE TITLE
v4.0.14 dist 404 page missing <header> section

### ISSUE THREAD

**Issue by vallieresc** [wet-boew/wet-boew#6819]
I just downloaded the dist release of 4.0.14 and saw that in 404 error page en/fr the <code>&lt;header&gt;</code> section is completely omitted from the html source. I had to copy it from your demo.

**Comment by pjackson28** [comment]
Which v4.0.14 zip file did you download and which file was missing the header section? Also which demo page did you get the header section from? The live working examples use the same files as what is in the zip files so likely there as file up in the live working examples that is missing the header section as well.

**Comment by vallieresc** [comment]
Downloaded file: wet-boew-dist-4.0.14.zip
Demo page got header section from: http://wet-boew.github.io/themes-dist/theme-gcwu-fegc/404-en-fr.html

**Comment by pjackson28** [comment]
It looks like it is because the WET theme doesn't have a banner (so no header) while the GCWU theme does (housing the official symbols). Here was I saw when checking each of the themes:

* WET theme: No header
* Base theme: No header
* Canada.ca theme: Header with FIP symbols
* GCWU theme: Header with FIP symbols
* GC Intranet: Header with FIP symbols
* OGPL theme: Header with OGPL logo

@thomasgohard @LaurentGoderre Should the WET theme have a header with the WET logo like the other themes or should it remain without a header like the Base theme?

**Comment by vallieresc** [comment]
I guess it's a misunderstanding, I was assuming the 404 template was GCWU but I guess it's base so it's normal.

**Comment by hsrudnicki** [comment]
@vallieresc @pjackson28 @LaurentGoderre  : Can this issue be closed?

**Comment by hsrudnicki** [comment]
@vallieresc @pjackson28 : Can this issue be closed?
