### ISSUE TITLE
Geomap fields - usability participants can't enter locations

### ISSUE THREAD

**Issue by neoinsight** [wet-boew/wet-boew#6845]
We had the first two participants last week try to use the Geomap demo on the Demo page to show the location of a previous address. Both had great difficultly with the location field - usually no suggestions would appear, and in both cases, the suggestion only appeared when they deleted the address to try again, as seen in these video clips.  

http://youtu.be/KT8nqGTr2Dc
https://youtu.be/rDLnwzhwZnI

We have stopped having participants try to use the map until this issue is better understood and the performance improves. 

Copying @pcwsmith, @thomasgohard

**Comment by hsrudnicki** [comment]
@neoinsight and others: Are you ready/working to close this issue?

**Comment by neoinsight** [comment]
@hsrudnicki  I will close the issue when I can see that the address bar is functioning properly enough to have usability participants try it again. I assume @thomasgohard or @LaurentGoderre would need to update or assign the issue.

**Comment by pjackson28** [comment]
It is probably due to Chrome only supporting matching at the start of the string versus Firefox which supports matching anywhere in the string. So Chrome as a result would show less matches than Firefox because there is less to match against.

**Comment by neoinsight** [comment]
@pjackson28 Now that the string matching is repaired, as per PR #7018,  the suggestions are much better, but the problems in Safari are still very present. As you can see, the datalist appears only for an instant, and then disappears before I can get my cursor there to select something. See video clip: http://www.youtube.com/watch?v=cZF_wo54B-I

**Comment by pjackson28** [comment]
@neoinsight It looks like Geomap is using the dynamic version of the datalist solution. Could you please try the following example in Safari to see if you get the same issue? http://wet-boew.github.io/wet-boew/demos/datalist/datalist-dynamic-en.html

If you get the same issue on this working example then it likely an issue between Safari and the WET enhancement. If you don't get the same issue, then something in Geomap may be interfering.

**Comment by neoinsight** [comment]
@pjackson28 Looks to me like the problem is in Geomap. I do not have the same issue in Safari in the dynamic datalist demo on the page above. At the same time though, I wonder if it's the SIZE of the dynamic list. Note the problems in Chrome in the videos at the top of this issue are very similar to my issue in Safari. The suggestions don't appear until backspacing etc. Wonder if it's worth trying a really long dynamic list (like the geomap data) in the dynamic datalist demo to isolate the problem?

**Comment by pjackson28** [comment]
@jvanulde Could you please investigate to find out what is going on in Geomap?

@neoinsight The multimedia option has over 200 associated issues with probably over half of those starting with "Mu". So if you can't reproduce with the "Multimedia player" in the drop down and "Mu" in the text field then it may not be a size issue.

**Comment by neoinsight** [comment]
@pjackson28 Hmm. When I select the multimedia option for the Dynamic Datalist in Safari, and type in 'mu' (or 'Mu'), I only see 8 options, as shown below. However, it does work, while the Geomap does not. 
![dynamic datalist safari](https://cloud.githubusercontent.com/assets/1855584/9395399/423a2f9c-475c-11e5-8ce7-1b4e5636a15a.png)

**Comment by pjackson28** [comment]
There is probably an upper limit on the amount of records returned by the plugin to avoid issues in some browsers where 100 or more records are displayed. I manually counted way more than 8 issues that started with "Mu" (although perhaps only the open issues are being returned).

**Comment by jvanulde** [comment]
PR #7003 may fix this.

**Comment by neoinsight** [comment]
@jvanulde I notice that PR #7003  was merged - does this mean that it's live in the Geomap plug in demo at http://wet-boew.github.io/v4.0-ci/demos/geomap/geomap-en.html ? 
We have more participants coming up this month, if it is, we want to retest to see if it's resolved on all their different browsers.

**Comment by jvanulde** [comment]
It looks like it's available on that build @neoinsight.

**Comment by neoinsight** [comment]
@jvanulde Excellent - will give it a try and schedule it in. If you have another site where it's also implemented, and where it's a working page with a specific task, instead of a demo page, do let me know.

**Comment by neoinsight** [comment]
@jvanulde @pjackson28 Ok, geomap is definitely fixed in Chrome, which is terrific, since the majority of Canada.ca users are on Chrome. And it works on Firefox too. However, it's still not working in Safari (latest version) on my desktop or on my iPhone- cannot select from the dropdown because the dropdown only is displayed if I click backspace. http://www.youtube.com/watch?v=qdNANqDtUgs

I can't test with participants until this issue is cleared, because many of our mobile participants have iPhones. 

BTW, @thomasgohard there is something really weird happening with the whole Geomap page on my iPhone. It loads at a normal size, and then suddenly shrinks, as shown in the screenshots below, note that the table low on the page is loading at the correct size. None of the other demo pages do this. If you are no longer responsible for the demo pages, please direct me to the correct person. 
![img_1557](https://cloud.githubusercontent.com/assets/1855584/10176550/619e2894-66c3-11e5-9400-a594d7f0c9d0.PNG)
![img_1559](https://cloud.githubusercontent.com/assets/1855584/10176552/643ab248-66c3-11e5-9c64-20aa098b8f09.png)

**Comment by jvanulde** [comment]
I can confirm the same behavior. My guess is that this is normal for Safari. I notice that on keyup for any key the results are shown. Do we have an example of a dynamic autocomplete in WET that does not have this problem in Safari?

**Comment by pjackson28** [comment]
@jvanulde Yes, you can find it in the [Datalist polyfill dynamic example](http://wet-boew.github.io/wet-boew/demos/datalist/datalist-dynamic-en.html). @neoinsight tried it on Safari and could not reproduce the problem (see [related comment](#issuecomment-132789590)).

**Comment by jvanulde** [comment]
That example is somewhat different then what Geomap is doing. Geomap is searching on every keystroke which may be the issue. Requests are ignored depending on how fast the user is typing. The issue is likely that Safari doesn't know when the content is refreshed... so it doesn't display the results. I am probably close to admitting defeat on this one but will try to address in the migration to OL3. Unless this is a high priority item in which case I am going to have to ask for assistance from someone.

**Comment by pjackson28** [comment]
@jvanulde If they are different, can you align the Geomap approach with how this dynamic datalist example is implemented? The example that was provided is using GitHub's API so in theory you could get similar results with the OpenLayer's API.

**Comment by jvanulde** [comment]
@pjackson28 I doubt it since the demo makes request on load for all options, then the datalist filters on that complete list when the user types. In Geomap we can't do that because we would have to load a couple of hundred thousand results. Instead when the Geomap receives 3+ characters as input, it goes to NRCan's goelocation API for a result set. Subsequent characters result in a new result set. I think this is where the problem resides with Safari - it doesn't refresh when the content of the datalist is refreshed.

**Comment by pjackson28** [comment]
@jvanulde Yes, but it does AJAX content in on each change event for the select field which is what you should be replicating. So you should be triggering the AJAX request from the example on a keydown and listening for the completion of the AJAX request and then updating the field exactly as shown in the example (including emptying the dataList, injecting the new suggestions (with the wrapper for under IE10) and then firing the wb-update.wb-datalist event. Those steps are necessary for this to work in the polyfill as without them the list won't be refreshed correctly.

**Comment by jvanulde** [comment]
We tried to implement it some time ago but we were unable to access the request object so we could cancel it. From a usability point of view this is important as it prevents unnecessary requests to the API which introduces delays in the rendering of results. See #6810. We can try looking at it again. If we figure this out it should be included as an example for the datalist plugin.

**Comment by pjackson28** [comment]
There exists the possibility of aborting the AJAX request, since the ajax-fetch plugin uses $.ajax, it is just the plugin is not designed at this point to provide access to the reference created by $.ajax (since that wasn't an identified use case). Someone could add a method or callback that can be used to fire an abort or maybe even have the plugin return the reference created by $.ajax so you could do the abort yourself.

Keep in mind that this has nothing to do with the actual datalist polyfill, as you could technically use a custom ajax approach with the datalist polyfill and it would still work as long as you follow the steps for after an ajax request completes (the ajax part is just a means of providing updated suggestions to the polyfill and doesn't affect the functionality of the polyfill itself). It would be better to improve the ajax-fetch plugin to add the new functionality/access rather than creating a custom mean of AJAXing in the data that does essentially the same thing as ajax-fetch except adds an additional feature.

**Comment by hsrudnicki** [comment]
Made "Going Stale" to close this issue or otherwise?
Either way, please update this issue's status, thank you

**Comment by jvanulden** [comment]
Needs to be addressed still.

**Comment by jvanulde** [comment]
@masterbee please take a look at this.

**Comment by hsrudnicki** [comment]
Does this remain still an issue?

**Comment by jvanulde** [comment]
Yes but it's being addressed in V2 of Geomap. So we can close this.

**Comment by hsrudnicki** [comment]
Thank you for your confirmation, it's closed.
