### ISSUE TITLE
Recommendations for a multiple select plugin

### ISSUE THREAD

**Issue by wilkmit** [wet-boew/wet-boew#6870]
I am looking for recommendations on a multiple select plugin. We were using select2 originally but it has some serious IE11 bugs. Any direction would be great.

Select2 JSFiddle:
http://jsfiddle.net/wphqwvLf/16/

**Comment by pjackson28** [comment]
Checkboxes are normally used for multi-selection because they are usually more accessible and usable than multi-selects. Is there a reason why checkboxes aren't sufficient? They are natively supported so would have better performance and mobile support than JavaScript-based alternatives. Note also that multiple selects have been natively supported by browsers for quite a while but they do pose keyboard challenges.

**Comment by CalvinRodo** [comment]
What issues does it have with IE11? I've used it quite successfully for filterable selects and haven't noticed any issues. 

@pjackson28 We didn't go with checkboxes for multiselects because we had to allow the user to multiselect from potentially a hundred different items and that many items on a page would be too cumbersome.

**Comment by wilkmit** [comment]
The issues seem to be with the multiple select. see https://github.com/select2/select2/issues/3300 for details on the issue.

**Comment by hsrudnicki** [comment]
Maybe it's too early, but just by occasion, are you ready to close this issue or otherwise?

**Comment by hsrudnicki** [comment]
@wilkmit @CalvinRodo @pjackson28 : Can this issue be closed?

**Comment by wilkmit** [comment]
On my end we just fixed it ourselves so it can be closed. However it would be nice to have a completly accesable solution other then check boxes for when multiselect lists get to long.
