### ISSUE TITLE
Table scroll bars appearing where they shouldn't.

### ISSUE THREAD

**Issue by ehcee** [wet-boew/wet-boew#6889]
I've noticed a few table issues where on very large tables, link in question:
http://www.healthycanadians.gc.ca/science-research-sciences-recherches/data-donnees/ctads-ectad/tables-tableaux-2013-eng.php

(1) Scroll bars appear in content in medium/larger display views
In IE 8/9 the scroll bars are appearing in the web page content in the larger display views. Firefox, chrome are not experiencing this issue. From link above see first table example.
*Noe these ones on this page are surrounded by div's with "table-responsive" class's.

(2) Print preview shows scroll bars
In IE9 and Google Chrome when I goto print preview that page, the print preview sometime's contains horizontal and/or vertical scrollbars. Could it be in print  preview it thinks it's at a smaller resolution ie for mobile devices?

**Comment by pjackson28** [comment]
It's because you are using Bootstrap's table-responsive class which triggers scrollbars for tables that overflow the container (effectively sets overflow to auto).

**Comment by pjackson28** [comment]
So for issue 1, it is likely because of the broken box model in IE8/IE9 which does cause some container overflows when it shouldn't (also note that IE8/IE9 are now outside of the support window).

As for issue 2, yes the print preview is generally a much smaller viewport width than on your computer monitor (due to paper sizes) so it is not unusual to trigger mobile view when printing.

**Comment by ehcee** [comment]
Perfect thanks for the feedback.
