### ISSUE TITLE
Form validation: 

### ISSUE THREAD

**Issue by sebastienHubert** [wet-boew/wet-boew#6912]
Hi,

I have the following form:

![feedbackform](https://cloud.githubusercontent.com/assets/11776025/8482720/67c74f70-20b9-11e5-9315-134fbee9f8da.PNG)

And on said form, I'm wondering if it would be possible to easily specify that instead of having a list of all errors at the top of the page, to simply have something like: "Please correct the error(s) on this page.".

It that feasible without going into the jQuery validation JavaScript file and manually editing code?

Sebastien

**Comment by pjackson28** [comment]
The summary doesn't come from jQuery Validation, it is added by WET. The following are the reasons why it was added:
1. Users need to know the number of errors up front. Without the number of errors identified up front, users were missing some errors and getting frustrated when resubmitting and failing again after they thought they got all of the issues. The number of errors up front was requested by users ( screen reader users in particular).
2. The summary identifies in one place everything that was done in error. Users (particularly visually impaired users) had difficulties identifying all the issues because they can't quickly scan the form like users without visual impairments. The summary of errors was requested by users.
3. The summary also provides quick links to the fields in errors, speeding up the process of fixing the errors. This is particularly useful for keyboard users who may have to tab through a large number of links and fields to get to the field in question. This was requested by keyboard users and screen readers users for that very reason.

**Comment by sebastienHubert** [comment]
It all sounds reasonable, I'm not doubting that there were reasons behind having a summary or its content, I was trying to see what are the possibilities regarding modifying the content. 

In other words though, are you saying it is not easily possible to change the contents of the summary?

Thank you for the information and for taking the time to answer my questions.
Sebastien

**Comment by pjackson28** [comment]
What type of changes are you looking for? The goal is to standardize user interfaces across the GC, in part to improve usability, so having different approaches and messages for form error messages would be counter to that goal. Currently the summary is a standardized opening line followed by content derived from the form labels and error messages themselves. Is there a particular use case that you are trying to cover that requires more or less in the summary?

**Comment by sebastienHubert** [comment]
At this point, if any changes were made, I was hoping it was through parameters that the form validation plugin would accept. It seems as though there is no such thing however, and at this point, I was just doing research into this proactively. If an actual request for change comes to us from our client, we may speak about this again, but at this time, that will be all.

Thank you very much for your time, and for providing that information.

Sebastien
