### ISSUE TITLE
Image maps in WET

### ISSUE THREAD

**Issue by silentcanadian** [wet-boew/wet-boew#6913]
Hi, my question is in association to issue #4144.

I'm using the latest version of WET for one of our GoC initiatives and recently I've been asked about the feasibility of adding an image map to one of the web pages. Is there anything within WET at the moment which would be used for the implementation of an accessible image map?

Thanks.

**Comment by pjackson28** [comment]
There is nothing in WET specifically, but that is because special enhancements are normally not needed and implementations are specific to each image map. For instance with a client-side image map, you just define the shapes and provide the text equivalents. Where things can get tricky is with responsive design where you could have a different image size for each view size where you would need to update the shape dimensions as the image size changes.

From an accessibility perspective, it is better to use client-side image maps rather than server-side image maps, particularly for keyboard users who need to tab through the image map.

**Comment by silentcanadian** [comment]
Noted, thanks.  So if I plan on implementating a client-side image map for my clients, there would be nothing that states that it should not be done from the perspective of the GoC web standards and WCAG?

On the topic of responsive design, in reference to the original issue from another GitHub user which I had made mention of in my first post, there was a solution created with respect to responsive image maps.  Would something like that be Ok to use in a GoC Internet web page (I didn't look too close at any licencing....)?  If not, will there be any responsive image map functionality within later versions of WET?

**Comment by pjackson28** [comment]
There is nothing preventing you from using a client-side image map, from an accessibility perspective, as long as you implement it correctly (according to WCAG 2.0 guidance). Keep in mind that you will likely encounter some challenges from a responsive design standpoint if the image map is large (so make sure to test and optimize for mobile). Usually best to provide a non-image map alternative for users that may have difficulty with an image map (usually links after the image map).

As for the solution you reference, something like that may work but it would need to be aligned to WET resize events (since relying on browser resize alone is very problematic since browsers are inconsistent and because it does not cover zoom size changes either). So it may make sense to adapt this work for WET, although there has been little interest so far in responsive image maps so far (only the second mention I've seen). That may be in part do to the page weight of image maps could be discouraging some usage (and because they can be difficult to deal with on small screens due to the much smaller touch targets).

Would your area be interested in trying to build a reusable solution for WET? It could be based off of the referenced solution.

that amount of computation on a resizeit may be possible to integratethe challenge is the JS can become very specific and may not be feasible to genericize into a plugin.

**Comment by silentcanadian** [comment]
Fair enough. I'll take a look and see what I can do, but it may take some time. I wonder, though, with the GoC movement into a WCMS if something like this would even be used. Doesn't hurt to investigate and give it a try, though.

**Comment by hsrudnicki** [comment]
@silentcanadian @pjackson28 : Please update the status of this issue, can this issue be closed or otherwise?

**Comment by silentcanadian** [comment]
I'll close this issue since my question was answered.  Thanks.
