### ISSUE TITLE
General question about wet supporting HTML5 

### ISSUE THREAD

**Issue by cnichols001** [wet-boew/wet-boew#6915]
We are using WET toolkit - specifically themes-dist-theme-gcwu-fegc. Using generated code to test HTML5 results in a lot of HTML5 errors - even using the Web Experience Toolkit page content-secmenu-en.html gives 72 errors against HTML5 (and possible WCAG). It is version 4.0 - Dec 5 2014.

Isn't WET supposed to be HTML5 compatible? Is there a later version or theme I should be using?

thanks,
Chris

**Comment by LaurentGoderre** [comment]
What are you validating with? Note that the W3C validator doesn't support HTML5 validation anymore and should use validator.nu

**Comment by cnichols001** [comment]
Using Total Validator - having it listen mode so we use generated source. If I use validator.nu by just right clicking and getting the source it passes, if I use the generated source then it fails. I'm under the impression that I should be testing using the generated source (?)
thanks

**Comment by pjackson28** [comment]
The issues I see in the generated source are the following:
1. Link elements generated by Yepnope (for CSS files) is missing the property attribute. This only affects polyfill CSS as it is the only CSS that is loaded dynamically.

2. There is an errant <code>'=""</code> in mobile panel summary elements. This will be fixed by PR #6920.

3. There is a header element within a header element (mobile panel in within the page header element and that panel contains a header element like with other overlays). Not sure how to fix this. Possible options are:
* 3a. Move the mobile panel overlay outside of the page header but keep the mobile panel button in that page header (most semantically correct).
* 3b. Stop using the header element in the mobile panel overlay (which would be out of sync with other overlay implementations).

4. Complains about the use of aria-setsize and aria-posinset in the menu. This has been a known issue for a long time where the validator flags this as an error, despite being necessary for accessibility. WAI-ARIA is addressing this in the next version where it allows the use of those properties where WET uses it now (so all we can do is ignore these errors in the meantime).

**Comment by cnichols001** [comment]
Ok, great - thanks. I also get an error on the meta tag:
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"/>
 - to me it looks like it must be checking for 'Edge' - do we need the chrome ?

thanks,
Chris

**Comment by cnichols001** [comment]
Sorry, didn't copy the tag correctly:
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"/>

**Comment by cnichols001** [comment]
meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"

**Comment by pjackson28** [comment]
That meta tag doesn't come from WET and doesn't seem to be in any of the generated output from the WET working examples. Is it added on your side? If not, perhaps it is added by Internet Explorer.

**Comment by cnichols001** [comment]
Nope - saw it when I was first implementing WET - must have been in an example or themes-dist-theme-gcwu-fegc. 
Ok, so good to know.

You didn't see duplicate id errors because of the mobile menu being created using the same id as the secondary menu? 
Thanks.

**Comment by pjackson28** [comment]
I checked the GC Web Usability theme examples and couldn't find that meta tag either. Perhaps an older version of WET had it but has since been removed.

As for the duplicate id issues, which duplicate ids are you encountering? I've looked at the side menu example and don't see any duplication. Perhaps it was an issue that was resolved in a previous version.

Which version of WET are you using? Can you reproduce those errors with the latest version?

Also noticed something about the first error I mentioned (re the link element). HTML5 has no mention of a property attribute for the link element, so it looks like it is another validator bug (that we'll need to ignore). Updated my comment above accordingly.

**Comment by cnichols001** [comment]
It could be how i'm creating the menu - I will check on that.
The link error occurred for me because the noscript tag (with link element under) was not after a script tag and then I had to make sure the noscript tag was being added in the header not in the body - when the link tag is in the body it looks to validate for RDF so mentions the property attribute being needed.

**Comment by pjackson28** [comment]
There is nothing in the HTML5 spec that limits where the link element can be used or that indicates when it is in the body element that it should be treated as RDF (or even treated differently). I don't see any basis in the HTML5 spec for the validator to flag it as an error. Not the first time the validator has been over-zealous in comparison to what is actually required by the spec.

**Comment by cnichols001** [comment]
Appreciate your comments. So we are using themes-dist-theme-gcwu-fegc so both the banner and footer cause duplicate id errors. I've just upgraded to WET 4.0.15... and have noted a couple of things:
1) still get the duplicate id errors, example in Footer because it has an id. (Not really a concern)
2) Notice that the UNMIN js is missing some error messages in Scripts/i18n/fr.js , all the ones under "formLanguages.wb" (wb.doc.one).
3) Am getting multiple errors: Attribute aria-required not allowed on element label at this point. Here is a code snippet:
<div id="ctl00_MainContent_uc2448_txtOpt5_gqc" class="form-horizontal">↩
765.        <div class="form-group">↩
769.	        <div id="ctl00_MainContent_uc2448_txtOpt5_divLabel" class="col-sm-5 control-label centerLabel">↩
770.                <label aria-required="true" class="dxeBase wetLabel required alignLeft control-label" id="ctl00_MainContent_uc2448_txtOpt5_lblOpt1" for="ctl00_MainContent_uc2448_txtOpt5_txtOpt1"><span class="field-name">City</span> </label>↩
771.            </div>↩
773.            <div class="col-sm-5">↩
779.                <input class="dxeTextBoxSys form-control" aria-required="true" required="required" id="ctl00_MainContent_uc2448_txtOpt5_txtOpt1" maxlength="80" value="Ottawa" name="ctl00$MainContent$uc2448$txtOpt5$txtOpt1" style="width:100%;" type="text"><script id="dxss_1238940294" type="text/javascript">

Question - Scripts/i18n/deps/additional-methods.js -has this been translated to French? I don't see any French translation within the copy I have.

By the by - great framework you all put together and I appreciate the prompt replies!
thanks
Chris

**Comment by cnichols001** [comment]
Sorry - it snipped off some of my comments.... have attached it: 6915_code_snippet.
My other question was that the Scripts/i18n/fr.js UNMIN is missing some French translations - 
wb.doc.one("formLanguages.wb".

Is there a French translation for Scripts/deps/additional-methods.js? or is this a jquery thing?

By the by this is a great framework you all put together.
thanks,
Chris

**Comment by cnichols001** [comment]
![6915](https://cloud.githubusercontent.com/assets/9962425/8673900/5d187678-2a08-11e5-8048-dc05897daa07.png)


![image](https://cloud.githubusercontent.com/assets/9962425/8673911/6ec7a2ae-2a08-11e5-8a1c-a4816ef834b2.png)

**Comment by LaurentGoderre** [comment]
Which version are you using? We fixed an issue with the loading of the i18n files

**Comment by LaurentGoderre** [comment]
The aria error is true, the `aria-required` is just for the form control not the label.

**Comment by LaurentGoderre** [comment]
Is .NET fgorcing another ID than the WET one? Because WET itself doesn't have duplicate IDs

**Comment by cnichols001** [comment]
WET 4.0.15 - is there a later one?
And what about Scripts/deps/additional-methods.js - am thinking there never was a translation for these?
Ok, - thx will remove aria-required from the label. Just fyi that your demo shows it:
https://wet-boew.github.io/v4.0-ci/demos/formvalid/formvalid-fr.html#tel

The id comes from the theme I'm using - or do you mean the mobile menu should not be using ids?
thx

**Comment by LaurentGoderre** [comment]
The problem with i18n was introduced in v4.0.15 but will be fixed in 4.0.16 coming out next week.

**Comment by LaurentGoderre** [comment]
Actually, the aria-required on the label is fine, it doesn't give an error.

**Comment by LaurentGoderre** [comment]
The GCWU theme does not have duplicate IDs by default: https://validator.nu/?doc=http%3A%2F%2Fwet-boew.github.io%2Fthemes-dist%2Ftheme-gcwu-fegc%2Findex-en.html

Perhaps .NET is adding markup it shouldn't.

**Comment by cnichols001** [comment]
Did a quick test on your form validation demo - using generated source with https://validator.w3.org/nu/ & get same aria-required error from line 301.
GCWU theme - you are correct - sorry about that -- someone must have added them.

**Comment by LaurentGoderre** [comment]
Not sure which one is more up to date, that one or validator.nu.....

**Comment by pjackson28** [comment]
The aria-required issue is from jQuery validation. It looks like it is blindly adding <code>aria-required</code> anywhere it finds the <code>required</code> class. It should only be doing that for form elements. So that is something that should be fixed upstream.

WET is using the <code>required</code> class on label and strong elements to add the red asterisk and the error colouring. It may be possible to add a <code>wb-required</code> class as a workaround to avoid mis-adding of <code>aria-required</code> (or to remove <code>aria-required</code> from inappropriate elements but this is really something that should be fixed upstream.

**Comment by cnichols001** [comment]
That's great - thanks. So for the upstream jQuery validation - is that something you are able to fix?

**Comment by LaurentGoderre** [comment]
What issue is there with jQuery validation?

**Comment by pjackson28** [comment]
@nschonni What is the best to deal with jQuery validation adding <code>aria-required</code> where it shouldn't? The problem is here:

https://github.com/jzaefferer/jquery-validation/blob/master/src/core.js#L382-L384
```js
			// Add aria-required to any Static/Data/Class required fields before first validation
			// Screen readers require this attribute to be present before the initial submission http://www.w3.org/TR/WCAG-TECHS/ARIA2.html
			$( this.currentForm ).find( "[required], [data-rule-required], .required" ).attr( "aria-required", "true" );
```
It should filter to just form field elements (so <code>input</code>, <code>select</code> and <code>textarea</code>). So the following would probably work:
```js
$( this.currentForm ).find( "[required], [data-rule-required], .required" ).filter( "input, select, textarea" ).attr( "aria-required", "true" );
```

**Comment by pjackson28** [comment]
@cnichols001 Could you give us an example of the duplicate id? It doesn't seem to be occurring in any of the working examples. Perhaps .NET is adding extra ids and WET is copying them over when building the mobile panel (just assuming since we don't have any concrete examples of this issue).

**Comment by cnichols001** [comment]
That is definitely my issue - apologies... I noticed id's had been added.

**Comment by cnichols001** [comment]
What about Scripts/deps/additional-methods.js -- is there a French translation for this? (next version even).
thx

**Comment by pjackson28** [comment]
Yes, they exist for a large number of languages. The problem is that there was build bug in v4.0.15 that prevented the translations from being appended to the i18n files. This has been fixed for v4.0.16.

**Comment by cnichols001** [comment]
Great - thanks

**Comment by hsrudnicki** [comment]
@cnichols001 @pjackson28 @LaurentGoderre : So, based on the above can this issue be closed or otherwise (pls update again the status of this issue)?

**Comment by cnichols001** [comment]
Yes please consider this issue closed - and thx!
