### ISSUE TITLE
Value in overriding default CSS for <tfoot> elements situated at the start of a table?

### ISSUE THREAD

**Issue by EricDunsworth** [wet-boew/wet-boew#6919]
This is going to sound very strange, but here it goes...

The HTML5.1 spec allows `<tfoot>` elements to be placed directly before the first `<tbody>` **or** directly after the final `<tbody>`. However, default `<tfoot>` CSS always visually renders the footer at the bottom of the table, no matter what. In print CSS, the footer is always rendered at the bottom in every page the table appears on.

Now my problem is, if a content writer decides to place a totals row at the beginning of their table and it gets coded as a `<tfoot>` (which is semantically correct - since it represents column summaries), neither the table's visual nor print structures will match the intended content order.

To address that scenario, would anyone be on board with setting `display: table-row;` on `<tfoot>` elements?

@thomasgohard @LaurentGoderre @pjackson28 @masterbee @rlambert27 Thoughts?

**PS:**
I was originally going to suggest something like `thead + tfoot {display: table-header-group;}` to allow the first `<tfoot>` element to be repeated at the right spot across every page a given table gets printed on. However, the repetition didn't work when I tested it out. I guess that `display` property's printing effect only works on the first element that uses it (i.e. `<thead>`).

**Comment by duboisp** [comment]
Here my views.

> The HTML5.1 spec allows ```<tfoot>``` elements to be placed directly before the first ```<tbody>``` 

That was since HTML4 and before.

> directly after the final ```<tbody>```

That was since HTML5

> However, default <tfoot> CSS always visually renders the footer at the bottom of the table, no matter what.

That is more because of the HTML specification not the CSS.

> the table's visual nor print structures will match the intended content order.

If the *content order* is an issue, then you can ask the "content writer" to move the ```<tfoot>``` directly after the final ```<tbody>```, as it's allowed by the latest HTML spec.  

> To address that scenario, would anyone be on board with setting ```display: table-row;``` on ```<tfoot>``` elements?

That kind of effect is not a default common for HTML table that are coded with ```<tfoot>``` before ```<tbody>```. The only common table that I know is structured and rendered like that, is the "Nutrition Facts Table" that we can see printed on almost every alimentary product. Creating by default an visual effect like that may/would provide an high impression of having a bug into the HTML code because that is simply not the normal/standards behavior from a web editor/web developer perspective.

It's look weird to use a style that is based on tabular semantic onto a tabular elements that provide a different semantic. Like here a ```<tfoot>``` as defined to be a group that contains rows with columns summaries as per HTML, but I will visually render that row group as a table row ```<tr>``` as per the CSS. 

@EricDunsworth, Did you think that "effect" should be applied to all table by defaults? Is a ```<tfoot>``` before or after ```<tbody>``` read differently by screen reader? 

*FYI* - Historically, ```<tfoot>``` was before the ```<tbody>``` because it were a time that network was very slow (fax modem, BBS server) and rendering a simple webpage required a lot of times for a computer. Having the  ```<tfoot>``` before the ```<tbody>``` allowed the browser/printer to faster show/print columns summaries of all the tabular data that even if all the tabular data wasn't received yet.

**Comment by hsrudnicki** [comment]
@thomasgohard @pjackson28 @LaurentGoderre @rlambert27 @EricDunsworth @duboisp @masterbee and others: Please continue your thoughts, and update this issue status whether this issue can be closed or otherwise?

**Comment by EricDunsworth** [comment]
@duboisp IMO there'd be value in implementing the effect I'm proposing on all tables by default, to allow the visual content order to match what's been coded (and by extension - the content author's intentions). I'm not sure how screen readers react to the placement of ``<tfoot>`` elements.

Btw I'm on vacation now, so I might be MIA from GitHub until late August.

**Comment by hsrudnicki** [comment]
@EricDunsworth @duboisp and others, please update this issue's status

**Comment by shawnthompson** [comment]
Talk about it at codesprint, right now.... go!

**Comment by andre-gh** [comment]
You just missed him, @EricDunsworth can you update this issue?

**Comment by hsrudnicki** [comment]
Made "Going Stale due to no further results/status update(s) after the codesprint. 
Please update this issue's status again whether this issue, lingering for about 3 months since last comment, can be closed as resolved/fixed or otherwise?
Thank you

**Comment by hsrudnicki** [comment]
@EricDunsworth others interested: Does this remain still an issue? Please update the status of this in regards to the current 2016 year, thank you in advance for your update
[ If this is still an issue, can be this labeled as well? ]

**Comment by hsrudnicki** [comment]
In addition, see http://stackoverflow.com/questions/2053925/can-a-tfoot-go-at-the-bottom-of-a-table that may help in resolving/making a decision to close this as resolved

**Comment by EricDunsworth** [comment]
Gonna close this.

This issue is no longer relevant. The scenario it covers only applies to HTML5 and older.

It turns out that several months after I opened this issue, the HTML spec was changed to only allow ``<tfoot>`` to come after ``<tbody>``. In [HTML 5.1](https://www.w3.org/TR/html51/tabular-data.html#elementdef-tfoot) and [5.2](https://w3c.github.io/html/tabular-data.html#elementdef-tfoot) (as of this writing), ``<tfoot>`` can no longer come before ``<tbody>``.
