### ISSUE TITLE
Date Picker GoTo

### ISSUE THREAD

**Issue by nephinj** [wet-boew/wet-boew#693]
When selecting a year and month using the GoTo button it would be nice if the calendar dates were not clickable or if it took the values from the dropdowns when you click on a date.  Currently if you hit Goto and select 2000 for a date and then click on a day the year remains at the current year.  Users might not know they need to click Go for the values to be considered selected.

**Comment by hsrudnicki** [comment]
So again, are you ready to close this issue or otherwise ?

**Comment by LaurentGoderre** [comment]
This will be addressed by the date picker redesign

**Comment by hsrudnicki** [comment]
Thank you for the above update, and please keep posted this issue status.
Just in case, due to this issue creation date and labels assigned, here is an additional note into consideration that may help to reduce number of related issues, the Plugin: Calendar of Events has more than 70 issues open, and Polyfill: Date picker has +90 issues open

**Comment by hsrudnicki** [comment]
Please update this issue's status whether this issue can be closed or otherwise?

**Comment by hsrudnicki** [comment]
Closed status, based on the opened issue's date of 2012, and as well the last comment from @LaurentGoderre that this issue shall be fixed by the date picker redesign.
