### ISSUE TITLE
Exceeding maxiumum number of selectors supported per CSS file in IE8 and getting close on IE9

### ISSUE THREAD

**Issue by pjackson28** [wet-boew/wet-boew#6930]
Looks like we crossed the threshold for IE8 selectors:

```
Linting dist/theme-wet-boew/css/ie8-theme.css...ERROR
[L0:C0]
WARNING: You have 4103 selectors. Internet Explorer supports a maximum of 4095 s
electors per stylesheet. Consider refactoring. Will error when selector count is
 > 4095. (selector-max) Browsers: IE
```

What should we do about this? I know IE8 is outside of the support window but this could lead to big display issues on IE8 down the line because IE8 is dropping at least 8 selectors now and likely quite a few more in the future. It is one thing to leave support where it is but is another thing to let it sharply drop off where it is already well supported.

**Comment by pjackson28** [comment]
Some possible approaches are:
1. Remove unnecessary IE8 selectors (or minor/low visibility ones)
2. Split up the CSS files

**Comment by pjackson28** [comment]
One thing I will do to help is to remove the IE8 details/summary summary heading fixes in PR #6929. Doing that barely brings us below the threshold.

**Comment by pjackson28** [comment]
Another thing we could do is go through the SCSS and prevent it from emitting any CSS that IE8 would ignore anyway (such as :not selectors, transition CSS, etc). It would also reduce the IE8 payload while bringing us back from the precipice. Note that we may already be going over the limit in other themes, it just so happens we slip under the threshold in the WET theme.

**Comment by pjackson28** [comment]
Actually IE9 has the same limit. We aren't at the limit yet but the number of IE8-specific selectors that we apply are not that much greater than what gets applied to IE9. Technically IE9 is outside of the support window but this could lead to issues in either browser down the road (thankfully the limits were removed in IE10 and don't exist at all in other browsers).

fyi @LaurentGoderre

**Comment by thomasgohard** [comment]
@masterbee there should be a lot of opportunities to optimise the CSS selectors to bring down their number.

Also, the Canada.ca theme is probably more complex than the WET theme, so it's probably already past the threshold on both IE8 and IE9. It wouldn't look good to have things break on Canada.ca.

**Comment by hsrudnicki** [comment]
@pjackson28 @thomasgohard @masterbee : Please update this issue's status whether this issue can be closed or otherwise?

**Comment by hsrudnicki** [comment]
Due to no further status update(s), this issue, lingering for about 4 months since last comment, made "Going Stale".
Please update this issue's status again whether this issue, can be closed as resolved/fixed or otherwise? Thank you

**Comment by hsrudnicki** [comment]
Please update the status of this for the current year as well, thank you

**Comment by nschonni** [comment]
This has now been exceeded
```console
Running "csslint:unmin" (csslint) task
Linting dist/theme-wet-boew/css/ie8-theme.css...ERROR
[L0:C0]
WARNING: You have 4233 selectors. Internet Explorer supports a maximum of 4095 selectors per stylesheet. Consider refactoring. Will error when selector count is > 4095. (selector-max) Browsers: IE
Linting dist/theme-wet-boew/css/theme.css...ERROR
[L0:C0]
WARNING: You have 4175 selectors. Internet Explorer supports a maximum of 4095 selectors per stylesheet. Consider refactoring. Will error when selector count is > 4095. (selector-max) Browsers: IE
>> 11 files lint free.
```

**Comment by EricDunsworth** [comment]
It looks like the 4,095 selector limit only applies to IE9 and lower. According to [The Many Exciting CSS Limits of Internet Explorer](https://spaceninja.com/2015/03/31/ie-css-limits/), IE10-11 support up to 65,534 selectors per stylesheet.

Since WET technically only officially supports IE11+ nowadays, maybe there'd be value in modifying the build to generate an empty ie8-theme.css file and suppress the linting warning (by adding ``"selector-max": false,`` into [.csslintrc](https://github.com/wet-boew/wet-boew/blob/master/.csslintrc))?

@nschonni @duboisp Thoughts?

**Comment by EricDunsworth** [comment]
Gonna close this out since #8679 disabled .csslintrc's ``selector-max`` rule.

IMO this situation was never very ideal given that WET 4.0 was initially designed to support IE8+. But by now IE8-9 have been obsolete for years and [IE10 is on its very last legs](https://www.zdnet.com/article/microsoft-makes-final-push-to-rid-world-of-internet-explorer-10/).

WET 4.0's older IE support has likely degraded substantially since this issue was created. WET officially only supports IE11 nowadays.
