### ISSUE TITLE
Form validation: "Required" is spoken twice

### ISSUE THREAD

**Issue by SBleeks** [wet-boew/wet-boew#6966]
The word "required" is being spoken twice for each form element example here.  Why not use the ARIA=required true?

**Comment by pjackson28** [comment]
We are using aria-required="true" but we also need to identify to visual users that a field is required. That likely is why you are hearing it twice, the screen reader announcing that the field is required because of aria-required="true" as well as "required" being included in the form label.

**Comment by hsrudnicki** [comment]
Can be the(es) issue(s) closed or otherwise?

**Comment by hsrudnicki** [comment]
Please update this issue's status

**Comment by hsrudnicki** [comment]
Made this issue as "Going Stale" to close or if otherwise?
Either way, please update this issue's status whether this issue, referenced with the other, can be closed or otherwise?
Thank you

**Comment by hsrudnicki** [comment]
Based on the above, can be this issue closed as a duplicate of the issues: 7002, as well 7540 or otherwise?

**Comment by hsrudnicki** [comment]
in the meantime of waiting for the status update, check the issue #6834 where is a discussion about  input type="file" vs required, and whether this may have an impact on your decision about this?

**Comment by RobJohnston** [comment]
Note that jQuery Validation has just removed the aria-required attribute in the latest version:  https://github.com/jquery-validation/jquery-validation/pull/2012

**Comment by EricDunsworth** [comment]
@RobJohnston This particular issue isn't the result of both ``required`` and ``aria-required`` attributes being set on the same input fields. It's caused by the fields' labels having "(required)" hardcoded as textual content, followed by screen readers re-announcing "required" yet again upon detecting the ``required``/``aria-required`` attributes. It's highly unlikely that screen readers would attempt to separately re-announce "required" each time they encounter any kind of required attribute.

I'd recommend opening a separate issue for what you found. Or if you're up for it, maybe even sending over a PR to update [WET's jquery-validation dependency](https://github.com/wet-boew/wet-boew/blob/master/bower.json#L35) to v1.17.0.

**Comment by RobJohnston** [comment]
Ah, then the previous statement by Paul is invalid.

I have no plan to take any action... just bringing it to the attention of those who need to know..

**Comment by pjackson28** [comment]
@RobJohnston @EricDunsworth I was referring to the "(required)" text in the actual label (needed for visual users) and not the HTML5 "required" attribute. So what was happening was the screen reader was announcing the presence of the required/aria-required attribute as well as reading of the associated label which included the word "required" (hence why "required" was spoken twice).

**Comment by grifare** [comment]
ChromeVox and NVDA interpret the same codes differently: ChromeVox reads it normally.
