### ISSUE TITLE
Inconsistent assemble include

### ISSUE THREAD

**Issue by LaurentGoderre** [wet-boew/wet-boew#6983]
In the following file: https://github.com/wet-boew/wet-boew/blob/master/site/layouts/default.hbs all the include exclude the heading, except the `sitemenu` include. It should be made consistent. Which one should it be, heading inside or outside the include?

**Comment by pjackson28** [comment]
I think the difference in that case is the heading is not the immediate child or the parent container for the include. In the case of sitemenu, the heading is nested within <code>&lt;div class="container nvbar"&gt;</code>. Now that may not be enough justification to have a different approach but that seems to be the only difference. As for making it consistent, likely the most common approach would be the better one to go with rather than the one off.

**Comment by LaurentGoderre** [comment]
I think it makes more sens if the block has the heading inside it. Don't you think?

**Comment by pjackson28** [comment]
If I recall correctly (kind of fuzzy on this one), it was originally kept out because the headings were kept out because the i18n function broke inside the includes. I remember we used to have quite a bit of difficulty with i18n inside includes (assuming that has been fixed since then).

**Comment by LaurentGoderre** [comment]
Oh perhaps. It doesn't seem to be an issue anymore. PR inbound. WIth this PR, the amount of HTML that themes will have to maintain will decrease dramatically.

**Comment by hsrudnicki** [comment]
Based on your current response, please continue updating of this issue status whether this issue can be closed or otherwise?
