### ISSUE TITLE
French values don't sort correctly using datatables plugin

### ISSUE THREAD

**Issue by fomag** [wet-boew/wet-boew#7007]
Please see the following page on our web site for an example  http://www.cra-arc.gc.ca/gncy/cntrcts/2015-2016/q1/menu-fra.html

When you sort in ascending or descending order the monetary value seems to sort sequentially from left to right instead of by total value. It works fine in English.

Just from a little bit of troubleshooting.. removing the dollar sign at the end of all the entries still results in it being sorted incorrectly but popping the dollar sign into the front seems to fix it.

**Comment by pjackson28** [comment]
That sounds like it could be a formatted number detection issue (not detecting that it is a formatted number so just treating as a text string). Here is the detection code (https://github.com/wet-boew/wet-boew/blob/master/src/plugins/tables/tables.js#L118-L130):

```js
// Formatted numbers detection 
// Based on: http://datatables.net/plug-ins/type-detection#formatted_numbers 
dataTableExt.aTypes.unshift( 
	function( sData ) { 

		// Strip off HTML tags and all non-alpha-numeric characters (except minus sign) 
		var deformatted = sData.replace( /<[^>]*>/g, "" ).replace( /[^\d\-\/a-zA-Z]/g, "" ); 
		if ( $.isNumeric( deformatted ) || deformatted === "-" ) { 
			return "formatted-num"; 
		} 
		return null; 
	} 
); 
```

Looking at the code, my guess is that having the $ at the end is causing a failure of $.isNumeric. A possible fix could be to have the regex take off any trailing $.

Note also that the actual sorting algorithm can be found here: https://github.com/wet-boew/wet-boew/blob/master/src/core/helpers.js#L39-L56. It may need some fixing as well to handle trailing $.

**Comment by pjackson28** [comment]
@masterbee Is someone from your team available to look into this further?

**Comment by andre-gh** [comment]
I will take this, will update tomorrow

**Comment by andre-gh** [comment]
I could not reproduce until I downgraded jquery from `1.11.1` to `1.11.0`.  I am looking into the source of the actual bug.

**Comment by andre-gh** [comment]
My mistake, I did not reproduce it, red herring

**Comment by andre-gh** [comment]
I hard a hard time reproducing but I finally figured it out.  I copy-pasted your HTML directly and was unable to reproduce it even with your exact WET and jquery, and datatables build.

I downloaded your page and inspected the encoding directly, it appears that some of your spaces are UTF-8 `NO-BREAK SPACE` instead of a normal space and internally these do not get handled like normal spaces.  When I copy-pasted your HTML these characters got translated into normal spaces.  We can look into switching the sorting code up to handle various whitespace characters, but in the mean time I recommend correcting the data.

The data may have been copy-pasted from Excel or some other program and had the other space character inserted that way.

Your space character (Hex highlighted on the right): 

![char](https://cloud.githubusercontent.com/assets/13316676/9119117/f9a7279a-3c42-11e5-8ed5-24a4ee8e72b3.png)

A regular space character is only 0x20

**Comment by fomag** [comment]
Those pages are generated using a java tool. These are Proactive disclosure so it’s hundreds of pages. We will look into correcting this on our end.

Thanks,

Andrew

**Comment by hsrudnicki** [comment]
@andre-gh @fomag and others: Can be this issue closed or otherwise? Please update this issue's status.

**Comment by hsrudnicki** [comment]
Further, please update this issue's status, thx

**Comment by fomag** [comment]
From my end it can be closed
