### ISSUE TITLE
LightBox and Usability

### ISSUE THREAD

**Issue by oueder** [wet-boew/wet-boew#7025]
On the following link: http://www.cra-arc.gc.ca/bnfts/uccb-puge/menu-eng.html 
We have coded "yes" or "no" button using lightbox. (See above "Video: Helping families prosper"). We had a blind person test this with Jaws and here is his comment: 
"After selecting, “yes” The text appears at the top of the page and I can read it using Jaws.  However, I did not know that this occurred and I had to move the cursor around a lot to determine where the cursor  was on the screen when the answered appeared.  The main problem with this configuration is that the user will not know that this happened and could get lost for a while.  Also, the user will have to navigate the cursor to the spot that they were before making this selection."

I) Would you have any alternative/solution to make this more usable?

II) Also, If the resolution of the page is not change, most mobile devices would display correctly the text in the lightbox. However, if the text is enlarged, and you select “Yes”, the lightbox window would in some mobiles devices not appear on screen.

Any ideas/solutions to share?

**Comment by pjackson28** [comment]
I just tried it with Jaws (version 14 in this case) and here is what happened:

1. I navigated to the Yes/No question (using a combination of keys) then tabbed to the Yes button.
2. I hit enter to activate the button. The overlay opened and it announced the title of the overlay.
3. I used the arrow keys to navigate down and it immediately read the entire contents of the overlay (it was next in the reading order).
4. I hit the escape key to close the overlay. Focus was returned to the Yes button and the Yes button was read off.

So everything worked properly for me in Jaws so I'm not sure what happened with the Jaws user. Focus was maintained correctly and I was able to quickly get to the text without looking around. Works well in NVDA as well.

Suggest you rerun the test with the Jaws user and find out exactly what went wrong. The overlay content is not at the start of the page so I'm not sure how the Jaws user determined that was where it was located (overlay content is where you originally put it in the DOM (which is a few nodes after the Yes button). Also suggest you look into the browser and screen reader versions to see if they could be contributing factors.

As for the mobile devices, I am not able to reproduce on my Android device. What specific mobile devices and mobile browsers are you encountering the problem on?

Note you are using an older version of WET v4.0.9 so make sure to upgrade to the latest version as there are known bugs in v4.0.9 that have been addressed since (current version is v4.0.16).

**Comment by pjackson28** [comment]
Also for the mobile device issue, does that happened any time the text size is larger than default or only when you change the text size without refreshing the page (so a page refresh corrects the issue)?

**Comment by oueder** [comment]
Hi Jackson

We are currently using WET v4.0.9 and will be moving to v4.0.14 in the near future.

For mobile devices, we tested this page
http://www.cra-arc.gc.ca/bnfts/uccb-puge/menu-eng.html

Devices used:
Samsung S6, using default browser and chrome
Samsung Galaxy Ace IIx, using default browser and chrome
Iphone 5s, using safari and chrome

Here is what we did:
•	Go to the webpage
•	Enlarge text
•	Click on Yes
•	Which brings you to the lightbox, where text is still enlarge text. Lightbox text does not display properly, see screenshot of the S6, for reference.

![screenshot_2015-08-11-14-05-31](https://cloud.githubusercontent.com/assets/13737283/9209079/cd3e96ee-4042-11e5-9768-f178e7fa6fd6.png)

**Comment by pjackson28** [comment]
I just tried with the default Android browser and Chrome on an LG G2 (Android 4.4.2) and I can't reproduce the issue in your example page as well as on the WET example page. I tried scaling the text all the way up to 200% and the lightbox still displayed correctly, both before and after a page refresh. How did you increase the text size? In both browsers I went into the Accessibility settings and dragged the Text scaling all the way to the right.

What version of Android are you running on?

**Comment by gdanova** [comment]
When you say "I tried scaling the text all the way up to 200%", how did you do that? Because I believe the issue depicted in the mobile screenshot above is really just the result of a "pinch to zoom" followed by a launch of Lightbox. Which in my opinion is not a issue because when you zoom into a page this way it's a literal magnification and nothing on the page should reflow. So when Lightbox is launched it is also magnified like the rest of the page and doesn't fit on the screen until you un-magnify (un-pinch back to the default zoom factor).

**Comment by hsrudnicki** [comment]
Are you ready to close this issue or otherwise, please update this issue's status

**Comment by hsrudnicki** [comment]
Is still this issue or otherwise?
Please update this issue's status whether this issue, lingering for 4 months without further discussion/status updates, can be closed as resolved or otherwise?

**Comment by oueder** [comment]
No more an issue. Sorry 

    Le Vendredi 18 décembre 2015 15h08, Hanna S Rudnicki <notifications@github.com> a écrit :
 

 Is still this issue or otherwise?
Please update this issue's status whether this issue, lingering for 4 months without further discussion/status updates, can be closed as resolved or otherwise?—
