### ISSUE TITLE
dropdown menu: first element not clikable

### ISSUE THREAD

**Issue by marieeved** [wet-boew/wet-boew#7029]
Hi,
I realize that with my dropdown menu, the first element of the navigation (the one that we see on the line-ex: "à propos de nous"-see the pic) are not clikable. I want that the first element go to an other page but the link doesn't work. The link works only if the dropdown doesn't appear (ex: when loading the page) but I would want that the link works anytime.
is it possible?
![navbarreg](https://cloud.githubusercontent.com/assets/13418868/9232405/792aad72-40fb-11e5-996f-e5674500d3f1.JPG)

**Comment by LaurentGoderre** [comment]
This is by design, for usability reasons. Those links should point to a landing page that contains all the links for the submenu (in case the submenus doesn't load or JavaScript isn't working). Those top level links should not point to content pages.

**Comment by marieeved** [comment]
yes that's exactly the page that I want to display but anytime.
so, you tell me that it's not a good practice to display a landing page for ex the section called "à propos de nous" all the time? The menu should point only to content page (subpage of this section)? but I read in an other issue that often people don't navigate with the menu but inside the content (and it's true in my team too, we meet employees and some tell us that it was their behavior). So, it was an other way to navigate inside the site (not only just by the menu) in having access to these landing pages.

**Comment by LaurentGoderre** [comment]
Actually you should be doing both. You should use navigation in the content area as well as in the top menu.

The reason why it's thje way it is is because some people think you need to click the top level menu item to display the submenu, and in doing so, they navigate away from the page. By making those links non clickable, it prevents this behavior.

**Comment by pjackson28** [comment]
To see an example of this in action, see Canada.ca and go to the Travel menu. You will notice the "Travel - more" at the bottom of the sub-menu. So when JavaScript is disabled, they can click the "Travel" link in the menu bar (which points to the Travel -more page) and when JS is enabled they can get to the same page by clicking the last link. It caused may usability problems when the top link was clickable and the sub-menu was available (30% drop in task completion both due to accidental clicks and users choosing the more generic link first rather than the more specific one that would help them more).

**Comment by marieeved** [comment]
ok that's an option, but in the case where I don't want to use a label "more page".
is it enough to point to these landing pages via the home page? see the pic: if the section appears on the home page (à propos de nous- in blue) and people click on the title, it's ok to point to the landing page where they will see all the subpages of the menu (second pic). 
Or I have to use the 2 ways to maximize navigation through the website?
![homepage](https://cloud.githubusercontent.com/assets/13418868/9232805/bf7b690e-40fd-11e5-907f-41142366fb72.JPG)
![nous](https://cloud.githubusercontent.com/assets/13418868/9232806/c27f5a98-40fd-11e5-922d-86a1ce3762c3.JPG)
