### ISSUE TITLE
Charts and graphs - changing the color of a single bar in a bar chart

### ISSUE THREAD

**Issue by wilkmit** [wet-boew/wet-boew#7053]
I am attempting to achieve something like in the JSFiddle below. I have read through the WET4 documentation and can not find a way to achieve this. To your knowledge is there a way to change the colour of a single bar in the bar chart and not change all the bars of that series? (ex. change one td's colour).

http://jsfiddle.net/TPp8m/

**Comment by LaurentGoderre** [comment]
@duboisp please respond

**Comment by duboisp** [comment]
There is only one colors per series of data, it's not possible to set the colors for only one td's. 

*FYI - related WET4 documentation*
Your exact use case is not represented in the chart documentation but there is documentation regarding how to define a color for a series if you look at [Charts and graphs - Customization](http://wet-boew.github.io/wet-boew/demos/charts/custom-en.html)

**Small analysis of your jsfiddle example**
In your jsfiddle example it's define 3 series of data from each it set a different color. Each of the series do not contain data for all column, in fact each defined series have only one data where it defined in different column.

*Aside:* It might useful to know that the WET chart do 2 major thing. It build the series of data (line 1 to 3 in your jsfiddle) and it build and calculate the ticks (line 16 in your jsfiddle)

So in order to make the 3 series of data compatible with WET charts, I needed to map it into a data table. And in order to acheive the same results as your jsfiddle, I needed to provided a value of 0 for the column that didn't have a data.

**How to acheive that in WET**

You can define in one shot the color you want to use for each series. 
```html
<table class="wb-charts table" data-flot='{"series": {
        "bars": {
            "show": true,
            "barWidth": 0.3,
            "align": "center",
            "lineWidth": 0,
            "fill": 0.75
        }
    },
	"colors": ["red", "yellow", "green"]}'>
<caption>Colors</caption>
<tr>
	<th>Colors</th>
	<th>Red</th>
	<th>Yellow</th>
	<th>Green</th>
</tr>
<tr>
	<th>Series 1</th>
	<td>1</td>
	<td>0</td>
	<td>0</td>
</tr>
<tr>
	<th>Series 2</th>
	<td>0</td>
	<td>2</td>
	<td>0</td>
</tr>
<tr>
	<th>Series 3</th>
	<td>0</td>
	<td>0</td>
	<td>3</td>
</tr>
</table>
```

or it possible to set the color directly in the series header.
```html

<table class="wb-charts table" data-flot='{"series": {
        "bars": {
            "show": true,
            "barWidth": 0.3,
            "align": "center",
            "lineWidth": 0,
            "fill": 0.75
        }
    }}'>
<caption>Colors</caption>
<tr>
	<th>Colors</th>
	<th>Red</th>
	<th>Yellow</th>
	<th>Green</th>
</tr>
<tr>
	<th data-flot='{"color": "red"}'>Series 1</th>
	<td>1</td>
	<td>0</td>
	<td>0</td>
</tr>
<tr>
	<th data-flot='{"color": "yellow"}'>Series 2</th>
	<td>0</td>
	<td>2</td>
	<td>0</td>
</tr>
<tr>
	<th data-flot='{"color": "green"}'>Series 3</th>
	<td>0</td>
	<td>0</td>
	<td>3</td>
</tr>
</table>
```

Cheers

**Comment by wilkmit** [comment]
Thanks! I Appreciate you taking the time to look into my question.
