### ISSUE TITLE
terms and conditions question

### ISSUE THREAD

**Issue by anon123123** [wet-boew/wet-boew#7055]
can i reuse web experience toolkit 3 or 4 for my own website? if so, which theme am i allowed to use? do i have to include this copyright text in all of my web pages where i use wet? (text: THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.)

**Comment by pjackson28** [comment]
Yes you can use WET on your own website, although WET 3 is no longer supported.

As for themes, the Canada.ca theme, GC Web Usability theme and GC intranet theme can only be used on Government of Canada sites because of the official symbols. They could be used as a basis for a new theme on a non-Government of Canada site but would need be made different enough, including removing the official symbols, so as not to give the impression that it is a Government of Canada site. Same for the OGPL and WET themes. The base theme could be used as is, but it is suggested that you choose a more appealing colour scheme since the colour scheme is intended to highlight the various regions rather than look good. Note also that there is a theme generator to help you with building a custom theme: https://github.com/wet-boew/generator-wet-boew-theme

As for copyright text, the MIT license requires that you provide a reference to the terms and conditions in each file that includes WET code. Here is how to provide those references:

HTML: 
```html
<!-- Web Experience Toolkit (WET) / Boîte à outils de l'expérience Web (BOEW) wet-boew.github.io/wet-boew/License-en.html / wet-boew.github.io/wet-boew/Licence-fr.html -->
```

CSS (included by default): 
```css
/*!
 * Web Experience Toolkit (WET) / Boîte à outils de l'expérience Web (BOEW)
 * wet-boew.github.io/wet-boew/License-en.html / wet-boew.github.io/wet-boew/Licence-fr.html
 * 4.0.15 - 2015-06-24
 *
 */
```

JS (included by default): 
```js
/*!
 * Web Experience Toolkit (WET) / Boîte à outils de l'expérience Web (BOEW)
 * wet-boew.github.io/wet-boew/License-en.html / wet-boew.github.io/wet-boew/Licence-fr.html
 * v4.0.15 - 2015-06-24
 *
 */
```

**Comment by hsrudnicki** [comment]
Can be this issues as a help question be closed or otherwise? Pls update this issue's status

**Comment by anon123123** [comment]
I am wondering if this template is usable like this. I removed the Government of Canada images and text. MIT license is included in header. Please see attached screenshot.

![index](https://cloud.githubusercontent.com/assets/13953901/11821102/e35a5d5e-a335-11e5-97e2-6c9fc1c3abf0.png)

**Comment by anon123123** [comment]
and of course the WET text content will be removed

**Comment by anon123123** [comment]
can i get a status on this?

**Comment by hsrudnicki** [comment]
Based on the last comment, @anon123123: Do you need still an answer from @pjackson28 in order to resolve this issue and close it or if otherwise?
Either way, please update this issue's status whether this issue as a question can be closed as resolved or otherwise?

**Comment by anon123123** [comment]
It's still an issue as I didn't get a reply. I sent a screenshot to look at and for someone to let me know if that modified template is considered usable for my own website. Can I get an answer?

**Comment by pjackson28** [comment]
@anon123123 Technically you could use that approach because it doesn't use the official Federal Identity Program symbols. Still, it does look fairly similar to the original Government of Canada style so it would be ideal if you were to change the look a little bit more by switching in a different background image or colour to avoid the risk of giving visitors the wrong impression (since the background with the blue waves is fairly recognizable).

**Comment by anon123123** [comment]
is this ok then?
![index](https://cloud.githubusercontent.com/assets/13953901/12834616/cd74a0d0-cb76-11e5-8f96-a42c5d0fe8e9.png)

**Comment by hsrudnicki** [comment]
Is this still an issue? @anon123123 : are you waiting for an answer from @pjackson28? Please update the status of this, thank you

**Comment by pjackson28** [comment]
It looks pretty different so shouldn't be an issue.

**Comment by hsrudnicki** [comment]
Based on the above, this can be closed. If you strongly think otherwise, please update again the status of this, thank you
