### ISSUE TITLE
How to add Id value to autoComplete 

### ISSUE THREAD

**Issue by bomarleau** [wet-boew/wet-boew#7082]
Hi, I used to use dropdown to list all the options. In the dropdown, I used Id as option value. Once a value is selected, the id of the value will be sent to backend. 
Example:
"<"select name="carlist" form="carform" ">"
   "<"option value="1">Volvo "<"/option ">"
   "<"option value="2">Saab"<"/option ">"
   "<"option value="3">Opel "<"/option ">"    
   "<"option value="4">Audi"<"/option">"
"<"/select">"

I tried to use autocomplete to replace the dropdown. But I am not sure where to put the Id. If I put Id in
value, it will be displayed as value. 
Example:
"<"label for="city">City"<"/label ">"
 "<"input type="text" id="city" name="city" list="suggestions" / ">"
"<"datalist id="suggestions>"	 
	 "<"option label="Volvo" value="1">"Volvo "<"/option">"
	 "<"option label="Saab" value="2">"Saab "<"/option">"
	 "<"option label="Opel" value="3">" Opel "<"/option">"
"<"/datalist ">"

This won't work as the search will display 1,2, 3 install of Volvo, Saab, Opel. So,
Where do I put 1,2,3 ?

**Comment by pjackson28** [comment]
@bomarleau The HTML5 autocomplete (input list + datalist) is equivalent to a text input field with autocomplete functionality so I don't believe it provides the ability to submit anything other than the text that is in the text input field (just like a regular text input field). Also the HTML5 autocomplete doesn't prevent the user from submitting a custom value (just like with text input fields) so you would have no way of converting the custom value to a number your backend would understand.

If you need to limit the choices for users and want to submit an id instead of the displayed value then the select would likely continue to be your best option.

**Comment by hsrudnicki** [comment]
So, can be this issue closed or otherwise?

**Comment by hsrudnicki** [comment]
Based on the above, and no further discussion after the last comment from @pjackson28 (summarizing: if a must to enter one of the choices, then use the select element unless user wants to enter whatever, use the datalist element), this issue labeled as "Going Stale" and closed as resolved.

If @bomarleau and/or others think otherwise, please update this issue's status again, thank you.
