### ISSUE TITLE
Overlay: "Close overlay (escape key)" text repeats for screen reader because in both title attr and wb-inv

### ISSUE THREAD

**Issue by robwloch** [wet-boew/wet-boew#7126]
Hi,

I tested one of the examples on this page using NVDA and as expected it repeats the "Close overlay (escape key)" text because it has both a title attribute and hidden text. I believe that repeating text is not good according to WCAG 2.0 but just wanted to ask if it's okay in cases like this?

Thank you, Rob.

**Comment by pjackson28** [comment]
There is a reason for that. For the "Close overlay (escape key)" text to be displayed on mouse hover, it needs to be in the title attribute. The problem is that not all screen readers are configured to read off title attributes (many are not) so that is why it is also provided in the hidden text (which consequently is not available on mouse hover). There is no requirement in WCAG 2.0 to avoid repeating text, and I can understand how it could be a bit annoying, but I'm not sure how we can avoid the repetition without taking the text away from someone.

**Comment by robwloch** [comment]
Thank you @pjackson28 !
