### ISSUE TITLE
wb-linkdesc class

### ISSUE THREAD

**Issue by agagnon** [wet-boew/wet-boew#7127]
In WET 3.1, there was the "wb-linkdesc" class. Is there something similar in WET 4.0? I understand the feature was dropped in v4.0, is that correct?

Can you suggest a solution to replace that feature, or just tell me what I should do about it in a 4.0 page?

**Comment by pjackson28** [comment]
There isn't something similar in WET v4.0 because although it worked fine for mouse and keyboard it did not work at all for touch screen interfaces (such as mobile devices). You would need to use other means of conveying that information which are not reliant upon an element having focus (e.g., progressive disclosure through details/summary).

**Comment by hsrudnicki** [comment]
Please update this issue's status whether this issue can be closed or otherwise? Thank you

**Comment by hsrudnicki** [comment]
@agagnon : Is this issue still valid?
Due to no further discussion/status update, this issue labeled "Going Stale". Please update this issue's status whether this issue can be closed as resolved/fixed or if otherwise? Thank you

**Comment by hsrudnicki** [comment]
Based on the above, this issue is closed, and if you think otherwise please respond/update the status of this.
