### ISSUE TITLE
General question on testing of HTML5 for WET framework.

### ISSUE THREAD

**Issue by cnichols001** [wet-boew/wet-boew#7128]
This may be off topic but I'm wondering if you know whether there is a mandate on how to test for HTML 5 compatibility? Should testers be using the generated source or the static page (view source)? 
I ask because a government client insists on using only a static page (view source) and has never heard of using generated source. In my search I've seen both referenced but nothing that says one over the other should be used.
If you are able to answer or point me in the direction of someone who can it would be much appreciated.
cheers,
Christine

**Comment by andre-gh** [comment]
I am sorry, could you clarify what you mean by generated source vs page source?

**Comment by cnichols001** [comment]
Sure.
By page source I mean that static page produced by the server. Normally
viewed by right click & view page source.

Generated source includes source from the DOM elements and therefore
includes dynamic elements created by JavaScript. More actual representation
of the page. trickier to get, in Firefox can do select all of page, right
click & choose view selected source.
Thanks
Chris

**Comment by andre-gh** [comment]
WET should be tested with the source before any JS has run allowing the JS to run if needed as many of those changes are things like browser-specific poly-fills and would not look right if copied browser-to-browser.

**Comment by cnichols001** [comment]
So are you saying that WET should only be tested by using the static page
source and not generated source?
Thanks (want it spelled out so no confusion)

**Comment by andre-gh** [comment]
WET should be tested on the source as generated by the server (the HTML from the server) rather than the source as generated by any WET plugin or polyfil as any runtime source is not intended to be transferred between browsers.

I should clarify that WET is intended to be used with JS enabled to allow those polyfils to function, so they should be tested as they are generated...just not transferred between browsers (they should be allowed to re-generate each time).

**Comment by cnichols001** [comment]
Thanks so much for clarifying. Such a pleasure using WET and having you all
support it so well.
Cheers
Chris

**Comment by pjackson28** [comment]
I'm a little unclear as to what is being asked. The original wording of the issue seems to hint at testing the HTML5 compatibility of a specific browser but the description of the testing seems to be hinting at HTML5 validation (so validating the source against the HTML5 specification).

If the question is about testing for HTML5 compatibility of a specific browser (to determine whether a polyfill is needed or not), then yes you would test compatibility before applying any enhancements. If the question is about HTML5 validation, then you should test both the page source and the resulting DOM as some HTML5 attributes are dynamically added and maintained (e.g., WAI-ARIA attributes) so would not be present in the original page source. The page should still be valid HTML5 even after JS enhancements (although note that the HTML5 validator has been known to flag certain things as errors that shouldn't be, particularly with WAI-ARIA, due to evolving specifications and the validators not always being in sync).

**Comment by cnichols001** [comment]
The question was about testing for Html5, however, I really wanted to know
the recommended way to determine if a page is html5 valid. It sounds like,
as Paul says, I should be validating using both static and generated
sources.
Thanks

**Comment by pjackson28** [comment]
Just a reminder that there are certain things in the WET generated DOM that are flagged as errors by the HTML5 validator but are needed to support screen readers and will be addressed in future versions of the WAI-ARIA specification. So still good to test the resulting DOM, but good to keep in mind that certain validation errors could be acceptable. 

Also be careful with how you get the generated source as some tools will strip off parts that are needed for HTML5 validation (such as the DOCTYPE). So generated source validation can get a bit messy and confusing, but it is nonetheless helpful in identifying any DOM issues your custom markup or JS could be introducing.

**Comment by cnichols001** [comment]
Will do - thanks

**Comment by MaximMartel** [comment]
can this issue be closed @cnichols001 ?

**Comment by cnichols001** [comment]
Yes
