### ISSUE TITLE
Desktop view in Mobile - possible enhancement request

### ISSUE THREAD

**Issue by theruraljuror** [wet-boew/wet-boew#7132]
Was wondering if it made sense or was possible to have a desktop view option in WET 4 for mobile users (in the menu or part of the mobile footer), to allow users to see the full site and zoom to an area of interest on the page, as an option for the user, instead of scrolling from top down in mobile view, and as a result if a desktop view was added, then a 're-instate' mobile option would be needed to allow a user back into mobile.

**Comment by pjackson28** [comment]
The only real difference between mobile and desktop view is that some of the secondary navigation is collapsed under a panel (which in usability testing seems to work quite well in most cases) and that a few of the plugins orient themselves a little differently to fit into a narrower viewport (e.g., horizontal tabs switching to a vertical accordion). The reason the secondary navigation is collapsed is because there is not enough screen real estate to fit them (much the same reason why grid systems collapse down on narrower viewports).

I don't think there is really any benefit to offer such an option because both desktop and mobile users have access to exactly the same information (they both have access to all content and the full site).

**Comment by pjackson28** [comment]
Also not sure what you mean by scrolling from top down in mobile view as it is no different than a regular page other than wrapping to fit the narrower viewport (rather than forcing the user to scroll horizontally to see content that extends beyond the viewport).

**Comment by theruraljuror** [comment]
this is definitely not an issue, it would be more to have an option to ignore the viewports, as you are aware, some websites have an option to view the site as a whole while on mobile, without stacking/layering the content where you scroll through the content starting at the top, where as a desktop view (non mobile viewport) you see the whole site zoomed out, and can tap to an area to zoom in. it's just something i have appreciated on some sites that I've encountered. i do understand usability prefers current implementation, it was more of a 'perhaps this could be added' for the odd few out there that may prefer the option.

**Comment by LaurentGoderre** [comment]
This unfortunately isn't easy to implement

**Comment by pjackson28** [comment]
I've seen those sites as well and the reason most provide a link to the full site is because they don't leverage responsive design and only provide a small subset of the content in the mobile view (essentially they are providing two separate sites). I'm not sure it would even be possible to offer the option with WET as the responsive design is provided exclusively through CSS (so no separate pages or sites) so it would likely mean overriding the Bootstrap grid system, including the CSS media queries, to force it to look like the desktop view on a narrow viewport.

**Comment by theruraljuror** [comment]
ok,i thought maybe it would be difficult, not a problem, I was more just throwing it out there to see if it was or not, as it was a preference i have to see full sites on mobile, thank you both for your time.
