### ISSUE TITLE
Session Timeout: 

### ISSUE THREAD

**Issue by KenFeier** [wet-boew/wet-boew#7165]
Hello! I would like to use the "session time out" feature from your site, however I am unsure how to go about implementing it to my site. I know I need to copy and paste the code into my html but I am unsure what to do with the WET zip that I downloaded.

**Comment by masterbee** [comment]
@KenFeier - We have created a bit of a "Get Started" page with WET to help getting people off the ground using WET faster. Here is the link : http://wet-boew.github.io/wet-boew/docs/start-en.html

Let me know if this helps.

**Comment by KenFeier** [comment]
Thank you for your response. I have taken a look at this however I am still unsure what to do with the WET zip file I have downloaded nor do I see anything on how to link it with my page. I assume I copy and paste the code that calls the class but don’t I have to have some sort of code that connects it to a specific file in the WET zip?

 

Thank you for your time

**Comment by rlambert27** [comment]
@KenFeier Do you work for Government of Canada? I noticed your email has xceltesting.com. A working example is included here:

http://wet-boew.github.io/v4.0-ci/demos/session-timeout/session-timeout-en.html

Because this repo is specific to WET (Web Experience Toolkit) you would need to reference most if not all the WET files to get it working. You could go through the repo and simply copy the portion of the JS file relevant to the session timeout and implement it in your own website if you wanted to.

https://github.com/wet-boew/wet-boew/blob/master/src/plugins/session-timeout/session-timeout.js

You would still need to update that script though to get it working with whatever files you are currently calling on your own website.

Hope that helps!

**Comment by hsrudnicki** [comment]
@KenFeier and others: Based on the above, can be this issue closed as resolved/fixed or if otherwise? 
Either way, please update this issue's status, thank you

**Comment by hsrudnicki** [comment]
Can be this closed based on the above?

**Comment by hsrudnicki** [comment]
Based on the above, this can be closed as resolved.  If you think otherwise, please update the status of this again, thank you

**Comment by KenFeier** [comment]
Sorry, I don’t know what this is for.
