### ISSUE TITLE
Tables: Footnote link created in a table column header doesn't work via keyboard

### ISSUE THREAD

**Issue by sarasuri** [wet-boew/wet-boew#7166]
Hi,

We are using WET 4 Data table with searching, sorting and filtering and having an issue with implementing a footnote link in the data table column header.

In Firefox 40 and IE9, 10, and 11, footnote 1 link in a column header receives focus via keyboard but when you press the “Enter” key to activate the link it doesn’t take users to the actual footnote provided at the bottom of the data table. 
![snap1](https://cloud.githubusercontent.com/assets/12256067/10771133/8ad64fb2-7cc5-11e5-9716-ecdc7515e309.gif)
 
Any suggestions/recommendations on how to address this issue. Thanks

**Comment by pjackson28** [comment]
@sarasuri That isn't an issue with WET but is instead because DataTables is intercepting all enter key usage within the table header cells and stopping the event propagation (so prevents the event from reaching other event handlers and the browser default handling of links). I get the exact same result if I put a regular link in the table header cell (doesn't go anywhere, just changes the sorting). Strangely enough it works fine with a mouse click so that would seem to be a bug with how DataTables handles the situation.

**Comment by pjackson28** [comment]
As for how to address the issue, you could file an issue with DataTables (http://datatables.net/forums/) or find another way to provide the reference (since links won't work in a table header cell that has sorting enabled).

**Comment by hsrudnicki** [comment]
@sarasuri : Based on the last comment(s) from @pjackson28 , can be this issue closed as resolved/fixed or if otherwise?
Either way, please update again this issue's status, whether this issue can be closed or otherwise, thank you

**Comment by sarasuri** [comment]
Yes, it can be closed.
