### ISSUE TITLE
Lightbox in Basic HTML

### ISSUE THREAD

**Issue by hamdaneh** [wet-boew/wet-boew#7173]
Is there a way to hide the dialogs from showing when the HTML version of the site is set to be basic?
I tried this on the WET web site, and it has the same issue. 
http://wet-boew.github.io/v4.0-ci/demos/lightbox/lightbox-en.html?wbdisable=true

Thanks!

**Comment by pjackson28** [comment]
Yes, you can hide it with CSS. So something like <code>.wb-disable ...some selector...</code> to target just the dialog that you want hidden at all times. 

Note that the dialogs being visible at all times on the WET site is intentional as in Basic HTML version all enhancements are disabled so there would be no way for the user to make that content visible (which is why everything needs to be visible by default). So make sure that the dialog your are trying to hide in Basic HTML version is supposed to be hidden from the user permanently.

**Comment by hamdaneh** [comment]
Thanks! I will then keep them as-is (not hide them) and keep them the same as in the wet example website then.
