### ISSUE TITLE
autocomplete behave different in IE and firefox

### ISSUE THREAD

**Issue by bomarleau** [wet-boew/wet-boew#7175]
Hi, I tried to use autocomplete to allow the user to search input. In IE 11, when the user clicks a letter, In the WET 4 working example, when I click "b", only items start with "b" will appear: "Barrie". In Firefox, when the user clicks "b", items with "b" in any position will appear:"Barrie", "Chibougamau". We want what the firefox displays: a list of item with "b" in any position. 

How do I fix this problem? Do you have any plan to fix this in WET?

**Comment by pjackson28** [comment]
What you are seeing is differences in native browser implementations. Most browsers only match to the start of the string (Chrome, IE, Opera, etc.) but Firefox is the one outlier that does it differently by matching anywhere in the string. Since these are native implementations within the browser (like native implementation of forms controls) this behaviour is not something that WET can control. Such issues would have to be dealt with directly with the browser vendors and the HTML5 spec maintainers.

**Comment by bomarleau** [comment]
I did some search and the jQuery UI - Autocomplete behave the way we want (https://jqueryui.com/autocomplete/#maxheight). But WET did not implement it. I am wondering the difference between the way WET implement and the way  jQuery UI - Autocomplete does. Should we use  jQuery UI - Autocomplete  instead to satisfy the requirement?

**Comment by LaurentGoderre** [comment]
jQuery UI will likely create performance nightmare on your site. That's why we are not using it. Hopefully the HTML spec arounf this element becomes clearer and more useful

**Comment by pjackson28** [comment]
In the v2.x of WET we did include jQuery UI but it drove performance into the ground, particularly on mobile, with huge download sizes and very heavy processing. That is the same reason why we walked away from jQuery Mobile. It was necessary to go a different route to meet requirements because GC mobile requirements cannot be met with jQuery UI or jQuery Mobile.

Keep in mind that you are comparing behaviours across browsers whereas users on a particular browser would be familiar with that browser's implementation so wouldn't notice that it behaves differently than on other browsers (since most users use only one browser). So this is mainly just an issue for testers and not for actual users.

**Comment by bomarleau** [comment]
How about this solution:

**Comment by pjackson28** [comment]
@bomarleau It looks like it would need a complete overhaul to meet accessibility requirements. Only use of WAI-ARIA I could find was the use of aria-hidden. I tried it with a screen reader (NVDA) and there is nothing useful announced for telling the user what they are dealing with (no indication there is any autocomplete functionality or that there are even any suggestions). There is far more useful information provided for the native datalist implementation.

**Comment by hsrudnicki** [comment]
@bomarleau : Based on the provided comments, can be this issue closed as resolve/fixed or if otherwise?  Either way, please update this issue's status, thank you

**Comment by hsrudnicki** [comment]
Is this still an issue? Please update the status of this for the current year, whether this can be closed or otherwise, thank you

**Comment by masterbee** [comment]
closed since out of area of concern (native browser implementation differences) for WET
