### ISSUE TITLE
Bootstrap Dropdown Toggle built-in?

### ISSUE THREAD

**Issue by johnpalaganas** [wet-boew/wet-boew#7193]
Hello,

I tested the following code found on http://wet-boew.github.io/wet-boew-styleguide/v4/design/icons-en.html#examples Pressing on the arrow button produces an error instead of toggling the dropdown. Is this supposed to work or just an example if you include bootstrap js?
```html
<div class="btn-group open">
  <a class="btn btn-primary" href="#"><span class="fa fa-user fa-fw"></span> User</a> 
  <a class="btn btn-primary dropdown-toggle" data-toggle="dropdown" href="#"> 
    <span class="fa fa-caret-down"></span></a> 
  <ul class="dropdown-menu"> 
    <li><a href="#"><span class="fa fa-pencil fa-fw"></span> Edit</a></li> 
    <li><a href="#"><span class="fa fa-trash-o fa-fw"></span> Delete</a></li> 
    <li><a href="#"><span class="fa fa-ban fa-fw"></span> Ban</a></li> 
    <li class="divider"></li> 
    <li><a href="#"><span class="i"></span> Make admin</a></li> 
  </ul>
</div>
```

Thank you,
John

**Comment by pjackson28** [comment]
At this point WET does not include any of the Bootstrap JS, including the dropdown toggle. It looks like someone mistakenly included it in the Font Awesome examples page (probably missed because it is intended to demonstrate an optional icon library add-on, not intended as a demonstration of anything else). That dropdown toggle example should be removed to avoid any further confusion.

@andre-gh Could someone from your team please delete the dropdown toggle example from the page in question?

**Comment by johnpalaganas** [comment]
Thanks for the clarification @pjackson28

**Comment by andre-gh** [comment]
@pjackson28 Thanks, fixed
