### ISSUE TITLE
Image galery: more legend

### ISSUE THREAD

**Issue by marieeved** [wet-boew/wet-boew#7220]
Hi,

Is it possible to have two legends for a photo in image galery?
I mean to have text at the top of the photo and text at the bottom of the photo.

Thank you.

**Comment by pjackson28** [comment]
@marieeved If you want that type of control then you should do an AJAX gallery rather than an image gallery (examples are on the demo page). With the AJAX gallery approach, you have full control over what is in the lightbox so can have text before and after an image.

**Comment by marieeved** [comment]
ok. and what do I write in my ajax file?
like this:
```
<ul>
	<li>
		<a class="wb-lbx" href="demo/1_b.jpg" title="Image 1">
			<img src="demo/1_s.jpg" alt="Image 1" />
		</a>
	</li>
...
</ul>
```

**Comment by marieeved** [comment]
I have to put only 1 image by ajax file?
I can't create 1 ajax file with all the photos like with JS version?

**Comment by pjackson28** [comment]
@marieeved You can do it all with one file if you want. The ability to filter the AJAXed-in content by URL hash has been around since v4.0.7 and the ability to filter by selector has been around since v4.0.12 (examples are in the Single items section of the demo page). As for what markup to use, I'd suggest using the same <code>figure</code>/<code>figcaption</code> approach used in the lightbox for images, and then just add the additional markup that you need.

As for how to trigger the AJAX approach, just use the same approach in the demo page for the AJAX gallery and insert the image in the link if you want (the href for the link would be to the AJAX page though).


AJAX - Content filtered by URL hash (v4.0.7+) 
• AJAX - Content filtered by selector (v4.0.12+)

**Comment by marieeved** [comment]
thanks will look at that. tomorrow.
