### ISSUE TITLE
Tabbed Interface: blank space is created in tabs when you expand and collapse tabs

### ISSUE THREAD

**Issue by muling** [wet-boew/wet-boew#7232]
Tested this on browseemall and browserstack for various mobile devices (iPhone, Samsung Galaxy S6 etc).

![samsung_galaxy_s6-2015-11-12-12-42-59](https://cloud.githubusercontent.com/assets/2365028/11515777/a78945ee-984d-11e5-9a91-18c8d6e7b307.png)

**Comment by andre-gh** [comment]
Could you update to v4.0.19 and verify this no longer occurs?

**Comment by muling** [comment]
We could try that.  Is your live wet4 example already using this version?  Perhaps I can just test that.

**Comment by andre-gh** [comment]
Yes, https://wet-boew.github.io/themes-dist/GCWeb/regulations-en.html has a tab panel on it.  I can not reproduce your issue and I fixed a bunch of odd issues we were experiencing with tabs and details panels in the last release (although not this one in specific, it might have been fixed by related chance)

**Comment by muling** [comment]
Yes I tried it.  It seems to work. Thanks.
