### ISSUE TITLE
Question Convert Government of Canada Web Usability to Canada.ca theme.

### ISSUE THREAD

**Issue by alexandre-trottier** [wet-boew/wet-boew#7309]
Question: What is needed to to convert the Government of Canada Web Usability theme to Canada.ca theme that are on the same WET version? Do we only need to change some reference to the template?

**Comment by rlambert27** [comment]
No, unfortunately not. There are semantic HTML changes required. You will need to update all the different page elements. For example the header and footers are different and the HTML has been changed so they require changes.

If you are switching over to Canada.ca you can also have a look at the CDN for Canada.ca templates. It will make it easy for you to stay up to date with changes in the canada.ca look and feel and is compatible with most technologies (.NET/Java/HTML5/....).

http://www.gcpedia.gc.ca/wiki/Content_Delivery_Network

Hope that helps!

**Comment by masterbee** [comment]
@alexandre-trottier - in addition to @rlambert27 comment there is also the requirement for WET4.0. While there still needs to be changes to underlying markup ( header and footer HTML ), WET 3.0 and older did not use the same CSS base so conversion will be more intensive since you will need to alter the content of the HTML as well.

**Comment by alexandre-trottier** [comment]
Thanks @masterbee, I should have mentioned that I was referring to WET 4.0 framework for the question. I understand that the conversion will be more intensive with a different version of the WET framework.
