### ISSUE TITLE
WET h1 34px font size; reason for going with that size?

### ISSUE THREAD

**Issue by robwloch** [wet-boew/wet-boew#7320]
Just wondering if research was done to determine what the best h1 font size for WET would be?

bootstrap: 36px
w3chools, w3c: 2em aka 32px

Thank you, Rob.

**Comment by hsrudnicki** [comment]
Is this still an issue, waiting for a response (in regards the WET h1 font size, as well depend on a browser's default stylesheet)?  Either way, please update this issue's status, whether this issue can be closed as resolved or otherwise?  Thank you

**Comment by robwloch** [comment]
Hi @hsrudnicki , still waiting for a response. We're just curious how the sizes for the h1, h2, h3 were chosen. Assuming bootstrap's 36px was deemed a bit too large?

**Comment by hsrudnicki** [comment]
Does this remain an issue? Please update the status of this whether this can be closed or otherwise?

**Comment by masterbee** [comment]
@robwloch - just chiming in quickly, the h1 was leveraging Bootstrap h1 size and each of WET themes had the ability to alter it if the theme felt it needed it. To be honest  I am not sure if there was an exhaustive research done on the optimal size other that leveraging a well adopted CSS framework like Bootstrap that has done most of that footwork. 

I will close the ticket for now since this is a bit dated in terms of when it was opened but feel free to open a new issue if this does not address your question.
