### ISSUE TITLE
Console error when using GoC Activites and Features

### ISSUE THREAD

**Issue by rlambert27** [wet-boew/wet-boew#7324]
Hello,

A developer using the CDN pointed out a console error after upgrading to the latest version of WET (v4.0.20) on the CDN. The error is triggered when the GoC activities and initiatives is being pulled in from cdn.canada.ca.

URL with console error : http://www.esdc.gc.ca/includes/op-so/cdn-demo/content1-en.shtml
URL without console error (no GoC activities and initiatives pull) : http://www.esdc.gc.ca/includes/op-so/cdn-demo/content1-fr.shtml

I used the unminified WET files for easier debugging. Spoke with @EricDunsworth and maybe a "ajax-replace vs wb-eqht incompatibility" in v4.0.20.

Thought I would check on canada.ca (https://www.canada.ca/en.html) but it's not using data-ajax-replace to pull in the GoC activities and initiatives.

I couldn't find another website using v4.0.20 already to replicate the issue. I couldn't use the demo site because the feed is not used.

I think this may need to be resolved earlier than later given the console errors it will produce on websites running the v4.0.20.

Thoughts?

Roch

**Comment by rlambert27** [comment]
Sorry forgot to mention this is a demo site, so the first URL might have a slightly different Canada.ca look, it's just for a demo :-)

**Comment by EricDunsworth** [comment]
Just to give more context, what seems to be happening is that some JS from the CDN injects this bit of code into pages:
```<div id="gcwb_prts" class="wb-eqht row" data-ajax-replace="https://cdn.canada.ca/gcweb-cdn-live/features/features-en.html"></div>```

The aforementioned container div is leveraging both the equal heights and data AJAX plugins. It's initially empty and gets its children via data AJAX. But before that happens, the equal heights plugin is running... and failing because the container doesn't yet contain any child elements. Its children aren't getting AJAXed-in until some point after the equal heights plugin has failed.

**Comment by andre-gh** [comment]
> equal heights should wait until data AJAX has finished loading its content into the page, then run.

I would personally suggest emitting a wb-content-updated call from plugins inside WET which update content and then have the equalheight plugin listen for that event on any of its elements.  Keeps code very isolated and does not require any special cases inside either plugin for living together.

**Comment by LaurentGoderre** [comment]
The equalheight can also listen for the ajax loaded event and retrigger.

**Comment by andre-gh** [comment]
I don't like that since it feels too special case, maybe there are other non-ajax plugins which would want to retrigger the layout down the road?

**Comment by LaurentGoderre** [comment]
You can always do both.....listen for the built-in ajax plugin and create a "third-party" event that developer can trigger

**Comment by andre-gh** [comment]
But why would we not make the replace/etc plugin aware of a content updated trigger from the start and avoid needlessly adding an extra special case plugin?  Making equal-height aware of something like ajax responses just serves to over-complicate it and special case it.

**Comment by LaurentGoderre** [comment]
The scenario here is that equalheight doesn't retrigger when new content is added, It is resonable to add an event listener for events that indicate that content has changed in the element. Since one of the core way of changing the content is using ajax, you can listen to the built in WET ajax fetched event and also listen for an arbitrary second event that you would trigger if you modified the content using another way. There is nothing special case about this

**Comment by LaurentGoderre** [comment]
None of this is the ajax responsibility, it's the equalheight plugin that must react to changing content

**Comment by andre-gh** [comment]
But it is much better for ajax to say "I updated some content, in case anyone wants to know" than equalheight to say "hey was that an ajax request?  Lemme know if there is one"

**Comment by LaurentGoderre** [comment]
You need to do both, you need to send the event that content was added, and equalheight needs to listen for that event to update itself

**Comment by andre-gh** [comment]
Yes, but then equalheight is only worrying about "a content updated event" not this low level idea of an ajax event which means you have a nice clean flow.

**Comment by LaurentGoderre** [comment]
ok, sounds good

**Comment by andre-gh** [comment]
@LaurentGoderre Could you take a look at #7327?

**Comment by EricDunsworth** [comment]
@andre-gh @LaurentGoderre Thanks :)!

@rlambert27 mentioned earlier that things are working out on his test page now after updating its version of wet-boew.js.
