### ISSUE TITLE
Hidden inputs prevents form submission in IE 11

### ISSUE THREAD

**Issue by sbrioux** [wet-boew/wet-boew#7387]
Not sure if I'm just using this incorrectly or not but here is the general situation I just had going on.

I had two forms on a page, both with multiple inputs.  The first form was working fine for submitting the form (via Jquery.ajax()) but the second form would work just fine as well in all browsers EXCEPT IE 11.

The first form was defined as follows:
```html
<form role="form" action="#" method="post">
    inputs in here...
</form>
```

Second was as such:
```html
<form class="form-horizontal" role="form" action="#" method="post">
Multiple input fields here....
    <input class="hidden" type="submit">
</form>
```

With that setup it would not work in IE 11 but Chrome and FF were good to go.

To fix this I changed the class of the input to wb-inv and now it appears to work okay.

Bug?  Developer issue?

Edit:  In case it matters I am using the intranet template via
```json
{
  "dependencies": {
    "wet-boew": "wet-boew/wet-boew-cdn#4.0.18",
    "theme-gc-intranet": "wet-boew/themes-cdn#4.0.18-theme-gc-intranet"
  }
}

**Comment by LaurentGoderre** [comment]
Applying the hidden class on the button makes it completely useless since the class applies `display: none` which removes it from the DOM entirely. The `wb-inv` class is the corrrect class to use for adding hidden text.

is the button being hidden at all? How is the form submitted without the button?

**Comment by sbrioux** [comment]
The button was being hidden in both cases and we are handling the submission of the form using JQuery and relying on the user using the enter key to preform the search.

**Comment by LaurentGoderre** [comment]
@neoinsight what is you thoughts on hiding form buttons?

@sbrioux there is no issue with using AJAX but it wouldn't hurt to have the button as well as an option to submit the form. Some reasons are that pressing enter on some type of controls doesn't submit the form and this behavior is not guaranteed to work on mobile devices.

**Comment by sbrioux** [comment]
@LaurentGoderre I agree.  It is an issue that I'm going to have to address during UI design meetings with the client.  I'm pretty sure this violates some usability rules out there.

**Comment by LaurentGoderre** [comment]
That being said, for your immediate need, the wb-inv would be the way to go. If I had to guess, IE only trigger the submit event if a submit control is present, and since the hidden class removes it from the DOM, it wouldn't count.

**Comment by sbrioux** [comment]
I would also agree with that however, the first form on the page doesn't have a submit button at all.  Odd behaviour none the less.

**Comment by neoinsight** [comment]
My understanding is that the button is required for both mobile, accessibility, and clarity > if the page has multiple fields (can you send a pic?), then we've seen lots of problems with people clicking Enter and accidentally submitting too early, then getting errors because they hadn't done the other fields. The only reason to NOT have a button is because there is 'instant feedback' - like the filter field on the WET table.

**Comment by sbrioux** [comment]
Here is a sample.  The number of input fields on the right can vary greatly.  The fields on the left are a form of its own vs. the fields on the right.
![untitled](https://cloud.githubusercontent.com/assets/4192331/12990394/2b003546-d0d8-11e5-95da-e3648430f999.png)

**Comment by neoinsight** [comment]
Ok, that doesn't follow search conventions at all. If someone automatically (and I mean that literally, people hit enter without consciously planning to do so - the motor movement is initiated before the thought), then it acts as a submit, even though they intend to enter more parameters. 

Here is our example WET form, which has been tested with many Canadians, with next, previous and submit. http://thomas.gohard.me/web-form-validation-test/index-en.html

One other thing, and that would be that perhaps a Finder template should be considered instead. This looks like a limited set of results, that could be filtered instead of searched. The finder template is in the Content and Information Architecture spec or should be today. Again, based on much testing. Very similar to the publications Finder at Gov.UK here: https://www.gov.uk/government/publications
