### ISSUE TITLE
Mega menu items's width too small

### ISSUE THREAD

**Issue by menmarc** [wet-boew/wet-boew#7392]
Hi

We're having an issue with the WET 4 template regarding the width of sub-items under a mega menu node for the desktop view. When the caption's length of the mega menu item is high (ex: Frequently asked questions) and sub-items's length is low, the user has problem reaching sub-items links without making the sub-items menu (grey area) disappear. This happen because users usually put their cursor at end of the root mega-menu item to show the sub-items and then move their cursor down and then to the left to reach sub-items links. However, by doing so, sub-items menu disappears. Right now, to get to sub-items links (once it's visible), they actually have to move back their cursor to the left (on the mega-menu root item) and then move it down over the grey area of the sub-items links. This is not instinctive for them.

Is there a way of expanding the width of sub-items to be the same as the mega-menu root item? That would fix the issue.

Here's a screenshot showing how it currently look. You'll see that sub-items menu (grey area) is way too small. 
![image](https://cloud.githubusercontent.com/assets/2150536/13051422/299b1710-d3c7-11e5-947f-6be5e5abd2cf.png)

Thanks!

**Comment by rlambert27** [comment]
I'm just curious but how come you are changing the Canada.ca menu? Maybe it doesn't expand because it wasn't meant to be changed. The Canada.ca C&IA prevents the modification of the menu. This is specified in section 6.1.2 which states:

The global navigation menu must always adhere to the themes and topics approach described in this document. The global elements cannot be altered and must remain consistent across all content under the Canada.ca umbrella.

Just sayin :-)

**Comment by menmarc** [comment]
Hi @rlambert27 

We're not a sub-site of canada.ca so we don't fall exactly under the canada.ca umbrella. Our web application is the census website that will allow respondents to fill out their questionnaire. Since we're considered as an application and not a sub-site, we have the authorization to modify the mega-menu content (canada.ca mega-menu content is not relevant for our users and might actually distract them from the purpose of our site).

Thanks!

**Comment by rlambert27** [comment]
So maybe a suggestion would be to use the "Transactional" template (ex:  https://ssl-templates.services.gc.ca/app/cls/WET/gcweb/v4_0_20/samples/transactional-en.shtml) and then use a local navigation block instead?

Anyway i'll let the WET experts help you out! :-)

**Comment by menmarc** [comment]
As I see in this template, there's no mega-menu included. Removing the mega-menu at this point is not an option. 

Having the WET experts helping us out would be great.

Thanks!

**Comment by pjackson28** [comment]
@menmarc The Canada.ca theme can only support what is permitted by the Canada.ca Content & IA specification and applications that use the Canada.ca theme are required to follow the specification much like with other content. Currently that specification only supports the standard menu bar and the various transactional scenarios for supporting applications (which the various options are detailed in section 6.4 of the specification). If there are concerns with the options permitted then that should be addressed through the Canada.ca Content & IA specification and not through WET as WET just follows what is prescribed by the specification.

**Comment by michael-milette** [comment]
@pjackson28, I am in the same boat as @menmarc. I have an application, Moodle LMS, which requires a dropdown menu in order to work. I took a look at section 6.4 of the specification and I am not sure that it could be considered in a perpetual "transactional" state. Does this template support dropdown menus in the top menu bar?

**Comment by pjackson28** [comment]
@michael-milette The Content & IA Specification does not permit a custom menu bar, only the option of hiding the menu bar during transactional scenarios. Could your menu needs be met in the side menu or in the content area where the Content & IA spec allows for more flexibility?

**Comment by michael-milette** [comment]
Hi @pjackson28 ,

The application side menu is dynamically generated for each page's context. It PHP source code is over 225 Kb. Unfortunately it is not WCAG 2.0 compliant and cannot be made to be without replacing core application code and re-engineering it's IA.

Doing this is undesirable as it would result in forever having to maintain the modifications which would quickly get expensive defeating the cost savings associated with using an open source application.

The solution I came up with in WET 3.1 and 4.0 was to use their WCAG 2.0 compliant top navigation menu to dynamically generate only the most commonly used features of the application's default navigation side and remove the default side menu completely. The result was that it not only made the navigation WCAG compliant, it also simplified the user interface and made the menu easily accessible on mobile devices.

The Moodle default side column is actually one of any number of context aware dynamically generated blocks. Using the side menu, as you suggested, would take up the whole column of the page which would necessitate a second column for the application's blocks leaving less space for the actual page course content, besides aesthetically looking off balance. Someone also mentioned that it is temporary and should not be considered for long term use. I could be mistaken but I also seem to recall the specs mentioning that it should not be used as a site-wide navigation.

The other current option is to start creating a whole bunch of landing pages. While this would technically meet WCAG requirements, it would also becomes a logistic nightmare since the content of this new landing page would need to be context aware of the page you were previously on. And even then, I would still not have a place to put this a link to this landing page since I cannot add it to the top navigation menu.

The only other thing besides the header which is consistent across the whole site is the footer but it just seems counter intuitive to expect people to go looking in page a footer for a navigation menu.

With Canada.ca theme taking over the top navigation menu, there is no real place left for true applications, such as an LMS, to put their menu system.

**Comment by pjackson28** [comment]
@michael-milette The top navigation menu is only intended to be used as secondary or tertiary navigation anyway (which is the case on Canada.ca) so the primary means of navigation should be provided through the content area. This is particularly important on mobile where the top menu would be collapsed into the mobile panel for space reasons.

With the current approach, how would a user access through the content area all the functionality that you have been offering through the top menu? If it is not currently possible then it is recommended that the approach be revisited to ensure that users can accomplish all tasks through the content area without having to rely upon secondary and tertiary navigation systems such as the top menu or the side menu.

**Comment by LaurentGoderre** [comment]
Would that application be available on Canada.ca or is it an internal tool?

**Comment by michael-milette** [comment]
Moodle is already currently in used on both internal and public facing GoC sites. None of them are on Canada.ca yet as the only themes which will currently work are the Usability themes due to the navigation menu restriction. However my understanding is that there is a move to eventually move all GoC sites to Canada.ca which is why I am bringing it up.

There is also a movement in the GoC (and the rest of the world really) to make greater use of LMS (Learning Management System) sites to reduce training costs.

Whether it is Moodle or any other LMS, these are not just informational sites with fancy search engines. LMS applications like Moodle are interactive web based training applications with courses containing Lessons, Books, Quizzes, Wiki, Forums, Content pages, Assignments, Chat, Glossary, Surveys, Workshops and more for in-class and online eLearning. The big advantage of a mature open source application like Moodle over other commercial products like Saba is the cost. With Open Source, organization like the GoC can allocate more of their budgets to course development instead of yearly application licensing + development.

This only effective if you don't end up spending tons of money on extensively customizing the application and having to maintain those customizations. Otherwise you are just moving your licensing costs into ongoing development instead.

This is why I am trying to find a sustainable solution for this issue. If you prefer to spend lots of tax payer dollars on licensing instead of education and training, the commercial solutions will always be there, and they will charge the GoC even more to address the same navigation related issues but will do nothing to contribute to the current government's mandate of promoting open collaboration and innovation.

If there is nothing in the current Content and AI specifications that will allow for this to happen, perhaps it is time to take another look at how these specs should evolve or provide an alternative solution which addresses the issue.

**Comment by pjackson28** [comment]
@michael-milette Even if the Content & IA specification allowed for a custom top menu, there is still the issue that the top menu is still secondary navigation at best and there is not enough room on many mobile devices to fit that top menu without using up too much of the on-screen real estate. That is why the top menu is being collapsed into the mobile panel on all the themes (including the GC Web Usability theme).

It is good to have this work well across platforms, including open source platforms, but the challenge we are encountering here is that some of the traditional approaches of such platforms don't work as well on mobile devices with limited real estate as desktop devices where there is plenty of room. Is there a way to shift (or configure) Moodle to take a more content area-centric approach to better support the mobile devices with limited real estate?

**Comment by michael-milette** [comment]
@hsrudnicki I just sent a request to get a copy of the latest Canada.ca Content and Information Architecture Specification. I will look into it and get back to you after I've had a chance to review it.

**Comment by masterbee** [comment]
closing this issue and inviting the both @michael-milette and/or @menmarc  to open a new issue if they have further issues that are WET related.
