### ISSUE TITLE
Error message for invalid input does not get focus

### ISSUE THREAD

**Issue by supertia** [wet-boew/wet-boew#7393]
# Steps to reproduce
1. Create a WET 4 / HTML 5-validated form that contains a date field.
2. Open the form in your internet browser, and enter a non-date in the date field (ie. “dfsdfsdf”)
3. Hit the tab key.

# Expected Behaviour
The user’s focus should be brought to either the error message summary at the top of the screen, or to the error message that appears directly above the date field.

# Actual Behaviour
The user’s focus goes to the next item/field that would normally get focus.

# Additional Information
People using screen-reading technology (i.e. Jaws) or other similar technologies will not be alerted to the error in the field until they hit the form's “Submit” button.  They should be made aware of the problem right away so that they don’t have to jump around the form fixing errors later.
![untitled](https://cloud.githubusercontent.com/assets/12084610/13057861/e04aa32a-d3ec-11e5-8bb2-a5ae95f2c202.png)

**Comment by pjackson28** [comment]
@supertia Forcing focus to an area that is not the expected destination (away from where they are trying to tab to) could be disruptive to the user and could potentially fail WCAG 2.0 as per [F55: Failure of Success Criteria 2.1.1, 2.4.7, and 3.2.1 due to using script to remove focus when focus is received](http://www.w3.org/TR/2015/NOTE-WCAG20-TECHS-20150226/F55). What is being done in WET instead is to use an <code>aria-live</code> region that announces to the screen reader user when there is an error in the field when the field loses focus. That way the user can still navigate normally without interference but is informed that there is an issue with the field the user just left. You should be able to hear this through a screen reader (e.g., Jaws, NVDA), but if not then something is not working correctly and that should be filed as an issue.

**Comment by dfarough** [comment]
We need to be aware that ARIA live regions will not help users of older Access technologies that as yet do not provide good support for ARIA.  Deaf Blind users would not normally have speech turned on so would not get this information.  I agree with those who are suggesting that the page should be reloaded in this instance.  It would also be advisable  to place the error message content at the beginning of the page title so that users would be alerted immediately of the reason for this error.  This would be a good fall back option for users of older access technology.

**Comment by pjackson28** [comment]
That would really degrade the experience for other users (include screen reader users with WAI-ARIA support) if you force a refresh every time a form field loses focus and an error message is displayed. It could result in dozens to hundreds of page refreshes while trying to fill out the form. That would also likely fail WCAG 2.0 for forcing a change of context whenever a form field loses focus. 

Keep in mind that for older screen reader users they still have access to the error message, whether they navigate back to the field and hear the updated label or try to submit and are informed about all the errors after the submit attempt. The dynamically updated error message is an enhancement for users that have support for it and will likely become quite the detriment if you try to replicate that with a rapid series of page refreshes (both for the end user as well as the server delivering the form).

**Comment by martynka** [comment]
I have a couple of comments on the WET vs 4 - form validation.
The form control validation is performed in a real time at which point two things happen:
1.	the error messages that display above the from controls are not accessible to everyone. The error on the date picker was not read in IE 9 using JAWS. Need to note: we are not expert JAWS users. In Firefox the error message was read, but only after the next field that got the focus was read first.
2.	the mechanism to display error messages that link to the form controls is activated. The heading for the errors says: “The form could not be submitted because 4 errors were found.”. Because no submit button has been pressed yet, no list of errors should display at this point in front of the form. It looks like the page refreshes every time required field is validated. This did not happen in WET vs 3.

Here is the link to the form in WET working examples version 4:
http://wet-boew.github.io/v4.0-ci/demos/formvalid/formvalid-en.html

Here is the link to the form from WET working examples version 3 (to compare):
http://wet-boew.github.io/wet-boew-legacy/v3.1/demos/formvalid/formvalid-en.html

**Comment by pjackson28** [comment]
1. The error message is associated to the form field using the label element (it is included as part of the label). That is the WCAG 2.0 supported way of associating text to a form field (and is in most cases well supported by screen readers, including older screen readers). If IE9 + Jaws doesn't read the error message when the field has focus, then that is an issue with how IE9 + Jaws is handling the association of text to the form field and not something that WET can fix (since WET is just using standard HTML to form the association). If you are referring to it not reading off the error message when focus is away from the field then perhaps you are using a browser/screen reader combination that does not support the <code>aria-live</code> region. In that case the user is unable to take advantage of the enhanced real-time messaging but would still have access to the error message when the field regains focus or the user attempts to submit the form (so no decrease in functionality from a standard web form without real-time inline error messages).

2. The updates to the summary at the start of the form as well as any inline error messages are done without a page refresh (the DOM is updated directly). The only issue I see with the approach is that the opening wording is slightly inaccurate when there is no form submission because it says the form could not be submitted. That minor semantic issue aside, the summary can be helpful for users if they want a summary of all the errors currently in the form without having to navigate through each field to hear each error or attempting to submit the form (so provides a benefit).

As for not happening in WET 3, I just tried the examples you identified and the summary in WET 3 is displayed just like in WET 4 (I see no difference in how the summary is handled).

**Comment by martynka** [comment]
1. Thank you for the comments. We will discuss this issue further among the AWG and get back if we need to. 
2. No refresh that's good. Yes, I was a little confused with the wording as I thought that the form was accidently submitted. Indeed, the errors are handled in real time in WET 3 as well, I didn't see the errors, I was expecting red text. My bad.

**Comment by hsrudnicki** [comment]
Please update the status of this, whether this remains as an open issue or can be closed? Thx

**Comment by martynka** [comment]
I believe this issue can be closed.

**Comment by hsrudnicki** [comment]
Based on the above, this is closed as resolved, thank you
