### ISSUE TITLE
Icons for "Follow".

### ISSUE THREAD

**Issue by glevert** [wet-boew/wet-boew#7426]
In the list of icons http://wet-boew.github.io/wet-boew-styleguide/v4/design/icons-en.html
I do not see what would be the proposed icon for the purpose of:
- following content - i.e. telling me if content has changed
- following someone - such as in Twitter for example.

What would be a "standard" icon for that?

Thanks,
Guy

**Comment by JJmom** [comment]
Do you want it look like this:
![capture](https://cloud.githubusercontent.com/assets/17767658/13676094/6583f32a-e6b2-11e5-84cc-f77d5a2d900a.PNG)

Here is the code:
`<section class="followus"> 
   <h2>Follow:</h2> 
   <ul> 
    <li><a rel="external" class="facebook" href="http://www.facebook.com/"><span class="wb-inv">Facebook</span></a></li> 
    <li><a rel="external" class="twitter" href="http://twitter.com/"> <span class="wb-inv">Twitter</span></a></li> 
    <li><a rel="external" class="youtube" href="https://www.youtube.com/"> <span class="wb-inv">YouTube</span></a></li> 
    <li><a rel="external" class="flickr" href="http://www.flickr.com/photos/"><span class="wb-inv">Flickr</span></a></li> 
   </ul> 
  </section>
`
then you need to specify the links to a related page.

**Comment by RobJohnston** [comment]
The GCWeb theme has a [widget page] (https://wet-boew.github.io/themes-dist/GCWeb/widgets-en.html) that demos the usage of these icons on the right-hand side.  

You can also see something like @JJmom's code in context on the [topic landing page] (http://wet-boew.github.io/themes-dist/GCWeb/topic-en.html), for instance.

**Comment by hpauze** [comment]
I don't think an actual icon for "follow" exists. Unless you're specifically asking people to follow you on social media, I've seen the eye icon (for "watch this conversation" - e.g. GitHub) or the star icon (to "favourite" a page), but neither mean "following" per se. I've also seen the email forwarding arrow using for following, but I find this one confusing because it already has a defined meaning. Maybe it just needs to be as simple as a button that says "follow" that adds a checkmark and switches to "following" when the user clicks on it.

**Comment by hsrudnicki** [comment]
Does this remain an issue or otherwise? Please update again the status of this, thx

**Comment by masterbee** [comment]
closing since the caller's (creator of issue) appears to have been addressed with a  few good recommendations.
