### ISSUE TITLE
Tabbed Interface - Carousel: 1 item in carousel: Thoughts

### ISSUE THREAD

**Issue by shawnthompson** [wet-boew/wet-boew#7428]
How about turning the carousel off when there is only 1 item in the carousel. This would be used for those who are using the carousel in a system where they don't have access to the code. This would turn off all the carousel-like components and become just a figure with a caption.

Carousel with one image:

![image](https://cloud.githubusercontent.com/assets/2575266/13464813/ceb9dbc8-e060-11e5-904b-839803bb7a83.png)

Would change to this:

![image](https://cloud.githubusercontent.com/assets/2575266/13464840/f2d054a6-e060-11e5-91d4-7ff33f34efc0.png)

Thoughts on this?

cc/ @masterbee, @LaurentGoderre, @EricDunsworth, @nschonni 

GO :+1:

**Comment by masterbee** [comment]
@shawnthompson - this makes sense, since the plugin should be able to address the case where there is nothing to rotate. May make it more application friendly since it removes the burden of code from the implementing system ( do not output carousel code when only one item in carousel ).

**Comment by rlambert27** [comment]
I like the idea as well!

**Comment by MaximMartel** [comment]
I like it, im on it :)

**Comment by MaximMartel** [comment]
Ive added

 `// Stop carousel widget if only 1 panel
			if ( isCarousel && $panels.lenght < 2 ) {
				return true;
			}`

to tabs.js, now im trying to build WET so that i can test it.

**Comment by nschonni** [comment]
The role and aria probably need to change since it's not really a carousel at that point.                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: Maxim MartelSent: Monday, March 7, 2016 2:55 PMTo: wet-boew/wet-boewReply To: wet-boew/wet-boewCc: Nick SchonningSubject: Re: [wet-boew] Tabbed Interface - Carousel: 1 item in carousel: Thoughts (#7428)Ive added

// Stop carousel widget if only 1 panel
            if ( isCarousel && $panels.lenght < 2 ) {
                return true;
            }

to tabs.js, now im trying to build WET so that i can test it.

—Reply to this email directly or view it on GitHub.

**Comment by shawnthompson** [comment]
I agree. What if we put the role in using JS? Right now we put it in the source.

**Comment by nschonni** [comment]
The roles are already added through JS. You might want to convert it to figure/figcaption, but I'm not sure if all carousels are using images + caption.

**Comment by shawnthompson** [comment]
The carousel code requires the role to be added and it is in figure/figcaption.

From the [example page](http://wet-boew.github.io/v4.0-ci/unmin/demos/tabs/tabs-carousel-en.html)
``` html
<div class="wb-tabs carousel-s1">
	<ul role="tablist">
		<li class="active"><a href="#panel1">Tab 1: ...</a></li>
		<li><a href="#panel2">Tab 2: ...</a></li>
		...
	</ul>
	<div class="tabpanels">
		<div role="tabpanel" id="panel1" class="in fade">
			<figure>
				<img src="img/protect-environment.jpg" alt="" />
				<figcaption>
					<p>
						...
					</p>
				</figcaption>
			</figure>
		</div>
		<div role="tabpanel" id="panel2" class="out fade">
			<figure>
				<img src="img/banff.jpg" alt="" />
				<figcaption>
					<p>
						...
					</p>
				</figcaption>
			</figure>
		</div>
		...
	</div>
</div>
```

**Comment by nschonni** [comment]
You're right, I was looking at this https://github.com/wet-boew/wet-boew/blob/master/src/plugins/tabs/tabs.js#L367 which add the `tab` semantics. I thought this was like some of the other plug-ins where all the role and aria were fully automated just by adding the single class to the container

**Comment by shawnthompson** [comment]
I'm pretty sure we can make that default html code leaner.

**Comment by MaximMartel** [comment]
working on it 
:+1:

**Comment by MaximMartel** [comment]
I am able to stop the carousel widget, but breaking stuff while trying to figure out how to remove the roles attributes...
