### ISSUE TITLE
Chrome with WET4 Memory Leak?

### ISSUE THREAD

**Issue by Scott-D-Hodgson** [wet-boew/wet-boew#7479]
I've had a developer on my team report that he's noticed that using the WET4, with Chrome, there appears to be a memory leak.  I re-created the scenario at my workstation, using just the WET4 Working Samples online, by navigating to the following URL:

http://wet-boew.github.io/v4.0-ci/demos/index-en.html

Opening the Windows Task Manager and watching the Chrome processes the memory used slowly creeps up.  Leaving it open overnight showed that the used memory had tripled and the responsiveness of the page had diminished significantly.

It is most noticeable when typing into the text area by the search button.  On initial load, everything is fine.  Leave it open overnight and type into the same field the next morning and the responsiveness is not there.

Doesn't appear to be a problem in IE.

**Comment by Scott-D-Hodgson** [comment]
Given enough time idling and the page actually crashes Chrome.

![deadonidle](https://cloud.githubusercontent.com/assets/8443372/14317482/7f74cd02-fbd6-11e5-9fb1-fd7e0bc9e66d.png)

**Comment by LaurentGoderre** [comment]
I'm not sure it's a memory leak as much as a really excessive creation of objetcs

![profiling](https://cloud.githubusercontent.com/assets/1090826/14389683/cc30f862-fd81-11e5-8329-dec2aa4384a5.PNG)

**Comment by masterbee** [comment]
@Scott-D-Hodgson - Are you using an clean-room testing environment for the heap collection? This is what Chrome reccomends [https://developer.chrome.com/devtools/docs/clean-testing-environment] since many plugins and user account settings over time have a way of contributing to the memory leaks and not so much the page and/or web app. 

Additionally I have to thank you cause I knew that Chrome had some great profiling tools but your issue made me explore them even further. Wow to say the least of what you can see under the hood, it was really neat to see all that information about how WET reacts in realtime. 

That said, I leveraged the instructions on this page [https://developer.chrome.com/devtools/docs/javascript-memory-profiling] to help me try to replicate the issue you were experiencing. While I did not leave it overnight, I did leave it for a few hours and my JS Heap and Memory were pretty flatlined ( actually was on a slight downward slope ) during that period. I even took it as far as forcing a GC (Garbage Collection) as per Chrome recommendations to identify memory leaks correctly, and the JS Heap and Node counts dropped to 0 and rebuilt back to the last point before the GC as expected.

Keep in mind that I was leveraging an clean-room profile as recommended but wanted to share and ask to see if you can attempt your same tests with the recommended clean-room profile to see if we get that same issue?

**Comment by hsrudnicki** [comment]
@Scott-D-Hodgson / others: Does this remain still an issue? Can be this closed based on above or otherwise?

**Comment by masterbee** [comment]
closing since the caller's (creator of issue) appears to have abandoned the issue.
