### ISSUE TITLE
Input type="date" polyfill (date picker): Icon does does not display for IE12 and 13

### ISSUE THREAD

**Issue by muling** [wet-boew/wet-boew#7501]
The calendar icon is not present next to the input field, but it does display for IE11 and below.

http://wet-boew.github.io/v4.0-ci/demos/datepicker/datepicker-en.html

![datepicker-ie13](https://cloud.githubusercontent.com/assets/2365028/14540705/6731a70e-0254-11e6-84d6-5a116da3e182.png)

**Comment by nschonni** [comment]
Edge has native support for the date input http://caniuse.com/#feat=input-datetime

**Comment by muling** [comment]
It is not obvious to the user until they click the input field. Would it be possible for WET to add an non-clickable icon?

**Comment by nschonni** [comment]
FYI, this appears to be the same behaviour as the native date picker in Chrome, although Chrome looks to be setting the min year.

**Comment by LaurentGoderre** [comment]
I don't like changing native functionality too much. This should be the browsers' job to improve the usability of their control

**Comment by jonjones** [comment]
I am experiencing the same issue. Not sure if it is the same problem but I figured out that it does not display because there is a period in my id for the control. removing it makes the icon show up as intended however, my application uses the period in all its id's so this is an issue. I raised this same issue in WET3 and it was fixed then.

**Comment by LaurentGoderre** [comment]
@jonjones that would be a seperate issue. Please open a new one for this

**Comment by masterbee** [comment]
closed since not in area of concern for polyfil (changing existing native functionality).
