### ISSUE TITLE
Overlay: 

### ISSUE THREAD

**Issue by lonbraj** [wet-boew/wet-boew#7542]
I'm using the GC Intranet Theme, the overlay doesn't show up when using a link inside a list in the footer but does work if click within the search and menu. To reproduce the issue, if it's one, modify any content page from the gc intranet theme by adding the section you wish to display, i used the Centred popup (Lightbox) code, modify any links that's in the footer to open the overlay. It doesn't work in full page mode, but if you reduce the page size, it will work from the search and menus.

**Comment by hsrudnicki** [comment]
Is this still an issue? Please update the status of this again, thank you

**Comment by kpduncan** [comment]
This is because the center modal is look for the modal below the button on this [demo page](https://wet-boew.github.io/v4.0-ci/demos/overlay/overlay-en.html) I was able to get it to work by editing the html in the developer tools and moving the modal into a `<div class="row"></div>` and  have the div inside the footers container and below the nav element in the container.

**Comment by lonbraj** [comment]
Does the overlay needs to be placed in a specific tag for it to work?

**Comment by kodecount** [comment]
@lonbraj This is  a bug and is random when reproducing. Better to keep the button within the main area until overlays are overlooked at by the WET team (their is a number of issue they are looking into).

**Comment by lonbraj** [comment]
Perfect, thank you for the information.
