### ISSUE TITLE
DataTables sDom defaults have changed

### ISSUE THREAD

**Issue by GarthMartin** [wet-boew/wet-boew#7571]
I just started on a new project and we have used the latest WET (4.0.21) and there is a marked difference between the way the header elements are laid out as opposed to the version we used in our last project (4.0.14)

Is there any way to get this to display back the way it used to?  I have tried a couple sDom options, but cannot get it back the way it used to be...

Old:
![wetold](https://cloud.githubusercontent.com/assets/11050106/15870292/ca946c30-2cbd-11e6-8958-ae0203020945.PNG)

New:
![wetnew](https://cloud.githubusercontent.com/assets/11050106/15870300/ceb51cec-2cbd-11e6-8968-77885670c628.PNG)

Thanks,

**Comment by RobJohnston** [comment]
I think the change came about due to a usability problem:  [Usability: WET table filter field not noticed on right] (https://github.com/wet-boew/wet-boew/issues/7337).

**Comment by shawnthompson** [comment]
Thanks @RobJohnston for the link. Yes, @GarthMartin, the change was due to usability test done by @neoinsight and the participants not seeing the filter field on the right side of the page on large screens. We moved it to the left which made it easier to find. 

Does this answer your questions? If so, can you please close this issue? 

Thank you

**Comment by neoinsight** [comment]
@GarthMartin, we tested this new version before implementing it, and it did improve the likelihood of people finding the filter field compared to the original. Most tables are long enough that filtering is very valuable to people using it, but they just weren't noticing it when it was visually separated off to the right.
