### ISSUE TITLE
tooltips

### ISSUE THREAD

**Issue by rcatwr** [wet-boew/wet-boew#7597]
Hi I was wondering if there was a working example of a tooltip implementation. Thanks!

**Comment by shawnthompson** [comment]
@rcatwr I'm pretty sure it was removed because of the move to mobile first development. With the device that use touch screen, you couldn't use hover states to show text. I'm not sure who made the decision in WET 4 to remove it but it was it is no longer in the WET framework.

Maybe @masterbee, @pjackson28 or @thomasgohard can give more background on why it was removed.

**Comment by rcatwr** [comment]
@shawnthompson , It looks like the tooltip css is still there, so I was able to get them activated by linking to the bootstrap cdn and adding a function to initialize it. Thanks anyway!

**Comment by shawnthompson** [comment]
@rcatwr, the CSS is still there because WET pulls in the full Bootstrap CSS into it's theme.css file but we are not using any of Bootstrap's JavaScript plugins as they are not tested for the accessibility and usability needs according to TBS standards. I would recommend not using the Bootstrap CDN. 

The tooltip was removed for a reason, one I don't know of and I'm hoping someone listed above can let us know.

**Comment by rcatwr** [comment]
Ok -- thanks for the heads up! I am regularly asked by clients to install tooltips or similar features, and I was hoping this would be part of the package.

**Comment by shawnthompson** [comment]
You have to keep in mind that hover states aren't possible on most touch devices. Maybe I could suggest using a link with [an overlay](http://wet-boew.github.io/v4.0-ci/unmin/demos/overlay/overlay-en.html). I suggested using those for definitions instead of leaving to another page or using the footnotes.

**Comment by rcatwr** [comment]
Those look really great and a way better approach to what I'm doing currently. I'm often asked  to put large chunks of text and definitions into tool-tips, and this works much better -- thanks for the tip, @shawnthompson

**Comment by RubyDo** [comment]
@rcatwr @shawnthompson Open Ajax shows an example for tooltip that appears "on focus" beside the hover http://oaa-accessibility.org/example/39/ 
Mobile users would do onfocus, on WET , the tooltip would be placed underneath the form field. 
One issue - tooltip content appearing over the next of the next field, which may require css adjustment.

**Comment by shawnthompson** [comment]
@RubyDo this is ok for fields in forms but what about links? How would you focus a link on mobile device?

**Comment by RubyDo** [comment]
@shawnthompson Agree. It would be an issue for links!

**Comment by mgifford** [comment]
WET is based on Bootstrap, right?  If so we should at least have an assessment of https://getbootstrap.com/docs/4.1/components/tooltips/

If their default Tooltip isn't accessible, it would be good if there were a bug upstream to indicate this.

**Comment by thekodester** [comment]
WET is not using Bootstrap 4 as of yet.

**Comment by mgifford** [comment]
Is the plan for WET5 to upgrade to Bootstrap 4.4?

**Comment by thekodester** [comment]
Unsure, but it was update to 3.4.1 in 2019.

Related:
https://github.com/wet-boew/wet-boew/pull/8681
https://github.com/wet-boew/wet-boew/issues/7804

**Comment by thekodester** [comment]
3.4.1 did in reintroduce tooltips, but unsure if that was brought over in the update.

https://getbootstrap.com/docs/3.4/javascript/#tooltips

**Comment by EricDunsworth** [comment]
@mgifford AFAIK WET 5.0 is meant to be more of a standalone thing that's meant to be capable of being mixed and matched with other CSS/JS frameworks. That'll help avoid situations like the status quo (WET 4.0's heavy dependence on Bootstrap 3.x).

@duboisp might have more to add.

**Comment by mgifford** [comment]
Ok, but we should still have a pattern in WET 5 capable of displaying tooltips, right?

**Comment by EricDunsworth** [comment]
@thekodester FYI WET 4.0 doesn't use any of Bootstrap 3.x's JavaScript features.

@mgifford I think @duboisp would be in a better position than I to answer that :P.

**Comment by thekodester** [comment]
@EricDunsworth Thats what I thought.

###### I am just a volunteer on this GitHub project.
