### ISSUE TITLE
WET 5.0

### ISSUE THREAD

**Issue by agagnon** [wet-boew/wet-boew#7663]
I heard that you guys are already working on WET 5.0. Is that true ? If so, do you know when it will be released ?

We are working on migrating from WET 3.1 to WET 4.0, but we don't want to do all that work if WET 5.0 is out when we're done.

**Comment by masterbee** [comment]
@agagnon there is some ideas that are floating around with a bit of a re-architecture to simplify the build and also to look at leveraging more progressive concepts down the road.

As mentioned at Codefest we will be using the wet-boew-experimental repo to demo and sandbox a lot of interesting ideas. 

While there is not much there (movement wise) as of yet it maybe wise to keep an eye (watcher) on that repo since this topic and more ideas are starting surface.
