### ISSUE TITLE
Custom Font - Can we add them to the site?

### ISSUE THREAD

**Issue by crochefort** [wet-boew/wet-boew#7698]
Management want a new report to look pretty. They ask me if I can include a web font.

From the website of the compagny where they are selling those this is what we can read.

> Webfont: for your website or web application

> A webfont license allows you to embed the font into your website, so that it can be displayed on any browser. You will be serving the webfont kit for your own site and linking it in the CSS.

> Webfonts can be used across multiple websites/domains as long as the websites/domains all belong to the single License Owner, and the pageviews are not exceeded. Agencies responsible for multiple clients’ websites, for example web design agencies or hosting providers, may not share a single webfont license across multiple clients’ websites.

> Every time the webpage using the webfont kit is loaded (i.e, the webfont kit CSS which holds the @font-face rule is called) the counting system counts a single pageview for each webfont within the webfont kit.

> If the font file itself won’t be embedded in the website (for example, when the font is used in a static graphic image such as a logo) you should purchase a Desktop license instead.

So can I add a custom CSS in my page with a modification to the H2 heading like it's explained here? : https://www.html5rocks.com/en/tutorials/webfonts/quick/

Did someone try it with the WET?

Thank you for your input!

**Comment by cybersubtype** [comment]
If department is interest google had lot of open source fonts: https://fonts.google.com/.

**Comment by crochefort** [comment]
Issue with google font ... they are not working with IE11...

**Comment by crochefort** [comment]
@paul

**Comment by cybersubtype** [comment]
@crochefort The jsFiddle is working on IE 11 for me?

**Comment by pjackson28** [comment]
@crochefort Since you are referring to Government of Canada web content, the look and feel will need to comply with the [Canada.ca Content & IA Specification](http://www.tbs-sct.gc.ca/hgw-cgf/oversight-surveillance/communications/cia-sca-eng.asp) and the [Canada.ca Content Style Guide](http://www.tbs-sct.gc.ca/hgw-cgf/oversight-surveillance/communications/csc-grc-eng.asp) as required by [D.2.3 of the Directive on Management of Communications](http://www.tbs-sct.gc.ca/pol/doc-eng.aspx?id=30682#secD.2)

**Comment by masterbee** [comment]
@crochefort - as per your original question more specifically, WET doesnt forbid the use of custom fonts since it is a toolkit and as @kodecount referenced there some good solutions and easy way to do in your webpage. The not so obvious  part js policies and/or company rules may weigh into this question even though WET does not put up an explicit barriers against it.
