### ISSUE TITLE
Frequently Asked Questions

### ISSUE THREAD

**Issue by MichaelDalrymple** [wet-boew/wet-boew#7772]
Wondering if there is a proper way to code Frequently Asked Questions pages in accordance with WET, accessibility, usability, Canada.ca theme. Anyone?

**Comment by kodecount** [comment]
Please Read: http://wet-boew.github.io/wet-boew-styleguide/v4/writing/rchtctr-en.html#faq

**Comment by duboisp** [comment]
If some official guidance exist for a gc websites, it will be published in the Canada.ca content IA specification. 

Kudos @kodecount for providing the link

@MichaelDalrymple from my point of view, I recommends you to discuss further with your client in order to understand the real issue and what goal there are trying to achieve by using a faq solution. And then avoid a solution that consist in a faq or Q and A. 

Cheers

**Comment by duboisp** [comment]
@MichaelDalrymple can be this closed based on the above or otherwise?

**Comment by LaurentGoderre** [comment]
Not you too @duboisp ! :P
