### ISSUE TITLE
tab navigation issue with the toggle plugin (accordion)

### ISSUE THREAD

**Issue by marklague** [wet-boew/wet-boew#7800]
There seems to be an issue with the toggle plugin (accordion) when navigating with tabs.

When visiting a page for the first time, I'm able to navigate to the first section of an accordion menu. But when all the sections are toggled off there's no way to get back to any section.  The tabindex is being set to -1.

Our code is based on the toggle demo you offer here  [http://wet-boew.github.io/v4.0-ci/demos/toggle/toggle-en.html#accordion].

I've managed to replicate the issue with the demo page on chrome 54, firefox 50 and IE 11.

Thanks

**Comment by kodecount** [comment]
Their is two line this could possible be a issue:

Line 123: [`tab.setAttribute( "tabindex", isOpen ? "0" : "-1" );`](https://github.com/wet-boew/wet-boew/blob/master/src/plugins/toggle/toggle.js#L123)

Line 314: [`tabindex: isOn ? "0" : "-1"`](https://github.com/wet-boew/wet-boew/blob/master/src/plugins/toggle/toggle.js#L314)

The line that is being called and is causing this issue is Line 314

**Comment by kodecount** [comment]
Their is two line this could possible be a issue:

Line 123: [`tab.setAttribute( "tabindex", isOpen ? "0" : "-1" );`](https://github.com/wet-boew/wet-boew/blob/master/src/plugins/toggle/toggle.js#L123)

Line 314: [`tabindex: isOn ? "0" : "-1"`](https://github.com/wet-boew/wet-boew/blob/master/src/plugins/toggle/toggle.js#L314)

The line that is being called and is causing this issue is Line 314

@MaximMartel @LaurentGoderre @duboisp Is their a purpose to these lines?

**Comment by LaurentGoderre** [comment]
Yes! We are following the ARIA specs for tabs which says that only the visible tab is in the tab order. Once you are in a tab, you must navigate with arrows. The tab either goes to links within the visible tab or leaves the tab altogether if there are none.

**Comment by kodecount** [comment]
@LaurentGoderre Just trying to under stand this. When a tab is open the other two tabs should have a `tabindex` of `-1` so you stay in the current tab, but when you leave the tab all of them should return to `0`. If so the code isn't working. Cause when you leave the active tab all of the tabs stay at `-1` and are not useable anymore.

**Comment by kodecount** [comment]
@LaurentGoderre Just trying to under stand this. When a tab is open the other two tabs should have a `tabindex="-1"` so you stay in the current tab (then you arrows to change tabs), but when you leave the tab group all of them should return to `tabindex="0"`. If so the code isn't working. Cause when you leave/lose focus with the tab group all of the tabs stay at `tabindex="-1"` which makes it no longer usable.

**Comment by LaurentGoderre** [comment]
No, when you leave tabs nothing should happens to the tabindex. When you enter a tab, that tabs get focuable, you leave that tab, it becomes unfocusable.

**Comment by kodecount** [comment]
@LaurentGoderre Well if you close the active tab it become `tabindex="-1"` and leave/lose focus with the tab group all three well have a `tabindex="-1` and you can't use them any more.

**Comment by LaurentGoderre** [comment]
That might be a problem with the Toggle plugin inteferring with the tabs plugin

**Comment by kodecount** [comment]
Sorry I call them tabs I just mean the `<summary>` tags.

**Comment by duboisp** [comment]
Solution merged via #8414
