### ISSUE TITLE
Accessibility Input

### ISSUE THREAD

**Issue by kodecount** [wet-boew/wet-boew#7829]
The application I'm working on it has to work with Jaws so I have to code to make it work with Jaws. Their are some features we need that have to be user friendly. These are two JavaScript tools I had to create just looking for accessibility input?

Password Preview Button - https://jsfiddle.net/kpduncan/nq9xfddx/ (UPDATED)

Searchable DropDown - https://jsfiddle.net/kpduncan/d05bjwew/ (UPDATED)

I know WET has Datalist but they don't work 100% with Jaws our list well be around 100-200 forms so this is the best alternative. I've done some testing with Jaws, NVDA, [Wave (chrome tool)](http://wave.webaim.org/extension/), [aXe (chrome tool)](https://chrome.google.com/webstore/detail/axe/lhdoppojpmngadmnindnejefpokejbdd).

**Comment by rlambert27** [comment]
I'm not sure the password preview button would be accessible because it changes the input back to password within a couple of seconds. Someone with a visual disability, dyslexia or even a reading disability may not have time to switch back to the field and re-check the password before it switches back automatically. Maybe a solution is to use the button to activate you also use the button to reactivate when you are done. Maybe providing more time to review the password before it switches back.

**Comment by kodecount** [comment]
Thanks for the input. I've updated my code to look for a `keypress` or `mousedown`. On `keypress` it will focus on the input once the user leaves the input area the password is hidden again. When a `mousedown` is called it displays the password until `mouseup` is called. This well it can be seen as long as the user desires.

**Comment by kodecount** [comment]
Thanks for the input. I'm going to attach a `blur` event when the user leaves the input area it well change back.

**Comment by RobJohnston** [comment]
And note that IE already has an eye icon, so it shows double eyes, but the built-in eye works like the original.
![7829-doubleeyes](https://cloud.githubusercontent.com/assets/1347487/21718792/be77f882-d3e7-11e6-9784-960b93259eb3.png)

**Comment by kodecount** [comment]
Yes I have CSS to remove it.

**Comment by kodecount** [comment]
I probably wouldn't bother with this feature, but the application is to be used in IE 11 (chrome if desired but not all features available) since IE 11 has the password peak builtin for visual only I needed to recode it so it be used by multiple different users. Since if a non visual issues is redirect back to the login page with an error that there username or password was incorrect they would have to way to validate their password.

**Comment by duboisp** [comment]
@kodecount what is the issue are you having with Jaws when using the Datalist with longer list? 

A solution that will improve the datalist is preferable instead of creating a new plugin that do a similar task.

Are you simply facing user agent or/and AT that are not supporting the [```list``` attribute of an ```input``` element](https://www.w3.org/TR/html52/sec-forms.html#the-list-attribute)?

Quick note about the "Searchable Dropdown"
* What is the role of using cookie? Could the session storage be a better solution?

Missing information (more research needed):
* How AT should interact when the ```list``` attribute is present on an ```input``` element.
* List of browser and AT that support datalist
* Is the existing datalist implementation have a threshold? If no can we cap the list at four to seven values as suggested in the HTML5.2 spec?

**Comment by kodecount** [comment]
The searchable list isn't too important since it well only be able to select users, but the off chance it wasn't I wanted it to be accessible. The issue with Datalist is the version of Jaws (16) is not reading what is type or selected.

**Comment by kodecount** [comment]
The searchable list isn't too important since it well only be able to select users, but the off chance it wasn't I wanted it to be accessible. The issue with Datalist is the version of Jaws (16) is not reading what is selected (when scrolling the list using the arrows key (also their is no indication that a list is even available)). You can only hear what is typed.

**Comment by kodecount** [comment]
The searchable list isn't too important since it well only be able to select users, but the off chance it wasn't I wanted it to be accessible. The issue with Datalist is the version of Jaws (16) is not reading what is selected (when scrolling the list using the arrows key (also their is no indication that a list is even available)). You can only hear what is typed.

**Comment by kodecount** [comment]
Also when looking into this further another issue could be validation of the input. User could type gibberish and it could be considered valid even though no option was chosen.

**Comment by kodecount** [comment]
Also looks like a similar issue was brought up and never really concluded in a proper solution: #6567

**Comment by kodecount** [comment]
I experience the same issue on https://www.canada.ca/en.html (search at top right) with Jaws and NVDA. The screen reader is never informed that a suggestion list if offered and if by random accident I hit down arrow and hit enter I would have a total different value then before.

**Comment by duboisp** [comment]
Thanks @kodecount for explaining the issue your are experiencing. 

May be WAI-ARIA could help to better support the ```list``` attribute of an ```input``` element. Some testing and research are required before to consider to add a new equivalent plugin.

> Also when looking into this further another issue could be validation of the input. User could type gibberish and it could be considered valid even though no option was chosen.

From my understanding, by default the ```datalist``` represent a list of suggestion for choosing values on the ```input``` element. So if there a restriction (validation), that should be set directly on the input element.

**Comment by kodecount** [comment]
Yeah in my situation that isn't reliable. So I'll stick with this for now.

**Comment by kodecount** [comment]
Due to the issues with Datalist and how it really only used for recommendations I'll have to continue to use the method above, but I did make changes to use HTML5 Web Storage instead of cookies.

Password peek was updated to peek on keypress or mouse down and hide either with blur or mouseup.

**Comment by dfarough** [comment]
I have searched for and tested a couple of alternative solutions which work much better in Internet exp[lorer, Firefox and google chrome.

http://haltersweb.github.io/Accessibility/autocomplete.html

has good user instructions prompting for AT users.
good implimentation for Internet explorer, Firefvox and Google chrome.
provides touch usage instructions so appears  to be good for mobile browsers and tablets.

https://a11y.nicolas-hoffmann.net/autocomplet-list/

Also see the link for the ARIA autocomplete widget.
https://www.w3.org/TR/wai-aria-practices-1.1/#autocomplete

2.  it should be noted for screen reader users that configuration of forms mode settings may be necessary in order to make the autocomplete functionality work properly.  Using Jaws, the default option for forms mode settings is Auto which is not appropriate for this functionality.  Setting this to Semi-auto or Manual is recommended for these AutoComplete fields.

If using NVDA, make sure that the setting for "Automatic focus mode for carrot movement" in the browse mode settings under preferences is not checked.

Making these changes will allow the screen reader to present any listed options when the user presses the cursor keys.  If this setting is not adjusted, the screen reader will move to the next/previous  field or control on the page when the cursor keys are pressed. 

I will suggest to Freedom Scientific That they change their default configuration for this setting.

**Comment by kodecount** [comment]
Thanks for this @dfarough 

On another note I still think validation may be difficult. I might try auto the first suggestion and see if I can get a custom validation to work with it. As for if WET well update their Datalist feature is another debate.

**Comment by kodecount** [comment]
Testing [autocomplet-list by nicolas](https://a11y.nicolas-hoffmann.net/autocomplet-list/):

- Can be styled to look fine on WET in desktop (mobile may be a issue)
- Results are accurate
- Found generated code bit messy adds ids and class which aren't really need or have long complex names
- Not easily to validate if someone was wishing to do so (removes the datalist from the dom)

Was only able to take a quick look at [Accessibility by](http://haltersweb.github.io/Accessibility/autocomplete.html) @haltersweb.

- Results weren't accurate
- Was unable to recreate the autocomplete list
