### ISSUE TITLE
Open overlay automatically (without click)

### ISSUE THREAD

**Issue by jsguy1** [wet-boew/wet-boew#7837]
Hello,

Is there a simple way to open an overlay without having the user click on the link?  I'm specifically looking to have the top overlay open by default on the page.  I also don't want the user to be able to dismiss the overlay by using the "x" on the right-hand side.

Any help is appreciated.

**Comment by duboisp** [comment]
Yes you can but you will need to use some javascript that will be triggered only after WET is ready.

See the last example in the [Lightbox](http://wet-boew.github.io/wet-boew/demos/lightbox/lightbox-en.html)

```javascript
$( document ).one( "wb-ready.wb", function() {
	wb.doc.trigger( "open.wb-lbx", [
			[
				{
					src: "#inline_content",
					type: "inline"
				}
			]
		]);
} );
```

And in order to not have the "x", then you need to open a modal dialog where you will find a working example in the [overlay](http://wet-boew.github.io/wet-boew/demos/overlay/overlay-en.html).

Cheers

**Comment by duboisp** [comment]
@jsguy1 I should clarify that using the code spinet that I provided could make your page not conforming to WCAG level AA. That behavior is not the normal expected behavior so it can create a contextual issue. So I recommend you to perform an full assessment and test with screen reader prior to use it on production.

As an alternative, instead of showing the overlay by default on the page, it will be **highly preferable** to use an alternate design like:
* creating an intermediary page that will contain the dialog content, or
* inserting the dialog content at the top of the page.

Cheers

**Comment by jsguy1** [comment]
Hello,

Where do you see the working example where the "x" is remove from the overlay? I'm not concerned about accessibility as I am building a page in a private administration page.

**Comment by duboisp** [comment]
See the "modal" example in the [overlay](http://wet-boew.github.io/wet-boew/demos/overlay/overlay-en.html)

**Comment by jsguy1** [comment]
I saw that but the "mfp-hide" class doesn't seem to work with the overlay I am using at:
http://wet-boew.github.io/v4.0-ci/demos/archived/archived-en.html

**Comment by kodecount** [comment]
So you want a top bar overlay that is always active and can't be closed?

**Comment by LaurentGoderre** [comment]
The mfp-hide class is not used in a normal overlay, only a lightbox one i think

**Comment by kodecount** [comment]
I can see why the user is lost for starts their is four methods listed to trigger the overlays:

```javascript
$( "#overlayId" ).trigger( "open.wb-overlay" );
$( "#overlayId" ).trigger( "open.wb-overlaylbx" );
$( "#overlayId" ).trigger( "wb-init.wb-overlay" );
$( document ).trigger( 'open.wb-lbx', [ [ { src:'#overlayId', type:'inline' } ] ] );
```

**Comment by kodecount** [comment]
Either way if you want a top bar overlay that can not be closed use:

HTML:
```html
	<section id="top-bar" class="wb-overlay modal-content overlay-def wb-bar-t text-center bg-topbar-warning">
		<header><h2 class="modal-title">This information has been archived.</h2></header>
	</section>
```
CSS:
```css
.bg-topbar-warning, .bg-topbar-warning header {
	background: #fd0 !important;
	color: black;
}
```
Javascript:
```javascript
	$( "#top-bar" ).trigger( "open.wb-overlay" );
	$( ".wb-overlay" ).on( "wb-ready.wb-overlay", function( event ) {
		var button = $( this ).find( '.mfp-close' )[0];
		if ( this.id == "top-bar" && button )  {
			button.remove();
		}
	});

	window.addEventListener('keydown', function (event) {
			if (event.keyCode === 27) {
				$( "#top-bar" ).addClass( "open" ).attr( "aria-hidden", "false" );
			}
	});
```

**Comment by jsguy1** [comment]
Thanks for the reply and solution. Apologies for the late response. I ended finding an even easier way to go about it. 

I applied the following attributes to the "main" element:
```
<main class="container wb-inview" data-inview="top-bar">
```

I then used the overlay:
```
<section id="top-bar" class="wb-overlay modal-content wb-bar-t">
```

And lastly I hid the overlay's "X" button with:
```
.mfp-close {
  display: none !important;
}
```
This solved the problem. The overlay remains on the screen.
