### ISSUE TITLE
Calendar won't show the current date on load (Intranet 4.0.24)

### ISSUE THREAD

**Issue by Belange87** [wet-boew/wet-boew#7931]
Is there a way to make the current date as default?

I notice that the Internet 4.0.24 work's fine but not the Intranet Version...

Thanks

**Comment by kodecount** [comment]
This group doesn't manage your internal intranet webpage. If you talking about `<input type="date"/>` then yes the WET poly-fill doesn't set a default date (for good reason).

**Comment by kodecount** [comment]
This group doesn't manage your internal intranet webpage. If you talking about [`<input type="date"/>`](https://wet-boew.github.io/v4.0-ci/demos/datepicker/datepicker-en.html) then yes the WET poly-fill doesn't set a default date (for good reason).

Good reason being is the user can change the min and max dates of these input and the current date could be invalid due to though attributes (if they exist). Most browsers just you a placeholder of `yyyy/mm/dd` or something along that line.

But if your not talking about `<input type="date"/>` and talking about the [Calendar of Events](https://wet-boew.github.io/v4.0-ci/docs/ref/cal-events/cal-events-en.html) then it would be up-to the site manager to fix that. It also dependent on the events listed.

**Comment by Belange87** [comment]
Thanks for the answer!
