### ISSUE TITLE
Offset not showing for 8-column version

### ISSUE THREAD

**Issue by robinmckenzie** [wet-boew/wet-boew#7978]
On the page below, the offset section doesn't seem to be working - the cells are not offset in the 8-column version, although they are in the 12-column version.

http://wet-boew.github.io/wet-boew-legacy/v3.1/demos/grids/grid-base-en.html#offset

**Comment by EricDunsworth** [comment]
The offsetting in the first set of examples below the "Grid cells can be offset using ``offset-1`` to ``offset-5``:" paragraph only seems to take effect in browsers with a minimum viewport width of 1200px. The offsetting in the second set of examples takes effect in browsers with a minimum width of 768px.

It's unlikely that inconsistency will ever be fixed since [WET 3.1 is no longer supported](http://wet-boew.github.io/v4.0-ci/docs/index-en.html#wet31). WET 4.0 isn't affected since it doesn't re-use 3.1's offsetting classes. The same kind of effect can be achieved in it by [using Bootstrap's push/pull classes](http://getbootstrap.com/css/#grid-column-ordering).

**Comment by duboisp** [comment]
@robinmckenzie 

> As of September 23, 2014, version 3.1 of the Web Experience Toolkit is **no longer supported**. 

_(source: http://wet-boew.github.io/wet-boew/docs/index-en.html#wet31)_
