### ISSUE TITLE
Image carousel controls not displaying properly

### ISSUE THREAD

**Issue by bsoicher** [wet-boew/wet-boew#8032]
Trying v4.0.25 with Canada.ca theme

Image carousel controls not displaying properly on smaller screens.

Tested on Chrome 58, IE 11, Firefox 45.8.0

![screencapture-ml-fd-caf-fac-ca-en-section-ml-fd-1495830640440](https://cloud.githubusercontent.com/assets/882475/26511665/0c00edb8-4231-11e7-92c2-83f17150cb23.png)

**Comment by shawnthompson** [comment]
This is the commit that caused the problem.

https://github.com/wet-boew/wet-boew/pull/7815

cc/ @EricDunsworth

**Comment by EricDunsworth** [comment]
#7815's commit message mentioned that one of its changes prevents the space for carousel style 2's controls from appearing when printing (since the controls themselves aren't printed out).

Specifically, to achieve that I moved a few CSS properties from [src/plugins/tabs/_base.scss](https://github.com/wet-boew/wet-boew/pull/7815/files#diff-6938c7e29d33387f75688521fec5eadfL376) to [src/plugins/tabs/_screen-md-min.scss](https://github.com/wet-boew/wet-boew/pull/7815/files#diff-7a58141df1a67bcb929afa45d84bd01fR39). The former affects everything (all screen views, print, etc...), whereas the latter only affects medium screen view and up.

I believe my intent at the time was to only temporarily move the aforementioned CSS properties into [src/plugins/tabs/_screen-md-min.scss](https://github.com/wet-boew/wet-boew/pull/7815/files#diff-7a58141df1a67bcb929afa45d84bd01fR39) when I started developing my PR, with the eventual goal of moving them into a screen-only SCSS file before finalizing the PR. But it seems that I never got around to it and missed it while testing. Sorry :(.

I've opened #8036 to resolve this issue. It moves the CSS properties in question into a screen-only SCSS file and supersedes #8034.
