### ISSUE TITLE
JQuery version used in v4.0.25 contains security issues

### ISSUE THREAD

**Issue by nitinm162** [wet-boew/wet-boew#8047]
Hi,

This v4.0.25 WET Toolkit is still using an old version of JQuery (v2.1.4)
which has security vulnerabilities 
 - specifically Ajax calls which do  not specify the dataType.

So can you tell me when the WET toolkit will be updated to use the most current JQuery version?

Thanks

Nitin Mistry
Bell Canada

**Comment by LaurentGoderre** [comment]
@lucas-hay

**Comment by lucas-hay** [comment]
@LaurentGoderre, @duboisp, @nschonni do you forsee any issues with upgrading?

**Comment by LaurentGoderre** [comment]
As long as we stay in v2, probably not

**Comment by nitinm162** [comment]
Hi Guys,

I am new here, so not sure how the change cycle will happen.
Any clarification will be appreciated.

**Comment by daverdc** [comment]
In addition to Nitin's original documentation of the vulnerability we, at Bell, have researched the issue in an attempt to identify specifically what is at risk. Based on our research the specific vulnerabilities within the currently implemented versions of the jQuery libraries, within WET, are as follows:

1. **Cross-site Scripting (XSS) (Meduim) - [https://snyk.io/vuln/npm:jquery:20150627](https://snyk.io/vuln/npm:jquery:20150627)**
Affects 1.12.3 to 3.0.0-beta1 or 1.4.0 to 1.12.0
Affected versions of the package are vulnerable to Cross-site Scripting (XSS) attacks when a cross-domain ajax request is performed without the dataType option causing text/javascript responses to be executed.

2. **Cross-site Scripting (XSS) (Meduim) - [https://www.cvedetails.com/cve/CVE-2016-7103/](https://www.cvedetails.com/cve/CVE-2016-7103/)**
Affects pre 1.12.0
Cross-site scripting (XSS) vulnerability in jQuery UI before 1.12.0 might allow remote attackers to inject arbitrary web script or HTML via the closeText parameter of the dialog function.

3. **Denial of Service(DOS) (Low) - [https://snyk.io/vuln/npm:jquery:20160529](https://snyk.io/vuln/npm:jquery:20160529)**
Affects 2.1.0-beta1 to 3.0.0
Affected versions of the package are vulnerable to Denial of Service (DoS) due to removing a logic that lowercased attribute names. Any attribute getter using a mixed-cased name for boolean attributes goes into an infinite recursion, exceeding the stack call limit.

The recommendation for all issues is to upgrade to jQuery version 3.0.0 or higher.

Hope this provides more information into the issue.

Thanks

David Rene de Cotret
Bell Canada

**Comment by nschonni** [comment]
> Cross-site Scripting (XSS) (Meduim) - https://www.cvedetails.com/cve/CVE-2016-7103/

Doesn't apply since WET hasn't used jQuery UI since version 3

**Comment by nschonni** [comment]
Aside: :100: that setting up Snyk would be a good idea. Unfortutely it doesn't cover Bower dependencies where we have a good chunk of the non-development dependencies defined

**Comment by CalvinRodo** [comment]
OSSIndex has tools for scanning Bower dependencies. 
https://ossindex.net/start/bower/

**Comment by nschonni** [comment]
I'm going to look at bumping these, just need to try and review
https://github.com/jquery/jquery/compare/1.11.1...1.12.4
and
https://github.com/jquery/jquery/compare/2.1.4...2.2.4
