### ISSUE TITLE
Menu: Details: IE issue: 4.0.25 release problem

### ISSUE THREAD

**Issue by shawnthompson** [wet-boew/wet-boew#8058]
Something in the 4.025 update broke the use of `details` in the mega menu in IE (polyfil). 

For some reason it only allows the first details to expand and not the ones that come after.

This is an urgent issue because ESDC intranet and applications use details in the menu.

Here's a working example that uses WET 4.0.25
https://shawnthompson.github.io/wet-boew-menu-details/unmin/index-en.html

Here's a working example using WET 4.0.24
https://shawnthompson.github.io/wet-boew-menu-details-4.0.24/unmin/index-en.html

cc/ @duboisp, @lucas-hay @LaurentGoderre @nicolasraymond

**Comment by duboisp** [comment]
@EricDunsworth do you think this issue could be related to the changes made to the collapsible alert? #7895 and #7894

**Comment by EricDunsworth** [comment]
@duboisp Those were SCSS changes to collapsible alerts (``details`` elements that use ``alert`` classes), which have nothing to do with the mega menu. Neither of my PRs modified the polyfill's JavaScript in any way.

**Comment by shawnthompson** [comment]
Could it be because it's being ajaxed in?

**Comment by duboisp** [comment]
@shawnthompson it can be. Test it and let us know the result.

**Comment by EricDunsworth** [comment]
I've noticed that if I open up IE11, launch its developer tools, then open https://shawnthompson.github.io/wet-boew-menu-details-4.0.24/unmin/index-en.html, the Data Ajax plugin always triggers a breakpoint in IE11's debugger and generates the following console error:

* **Error:** Unable to get property 'url' of undefined or null reference
* **Origin:** https://github.com/wet-boew/wet-boew/blob/3ea753a7dac6f3b02e68f5babb29d51e32c2e8f6/src/plugins/data-ajax/data-ajax.js#L117

I don't definitely know if that's the cause of this issue, but if it is, here are some extra details that might be useful... Since WET 4.0.24's release, [3 commits have modified data-ajax.js](https://github.com/wet-boew/wet-boew/commits/3ea753a7dac6f3b02e68f5babb29d51e32c2e8f6/src/plugins/data-ajax/data-ajax.js). They originated from #7875 and #7991.

[3 commits have also been made to the menu plugin](https://github.com/wet-boew/wet-boew/commits/master/src/plugins/menu/menu.js) since WET 4.0.24 was released (via #7942 and #7944).

The details/summary polyfill's JavaScript code hasn't changed since WET 4.0.24's release.

**Comment by EricDunsworth** [comment]
@shawnthompson Btw in your example links' mega menus, the "Link" text is white inside your "Service Canada" details/summary implementations. It's because they were coded as plain text instead of link text.

The "Link" links were coded like this in your sitemenu-en.html files:
```
<li><a href="#"></a>Link</li>
```

**Comment by shawnthompson** [comment]
I did it fast but I'm not worried about those links. Can't fix it now, just ignore it.

**Comment by nschonni** [comment]
Looking at https://github.com/wet-boew/wet-boew/compare/v4.0.24...v4.0.25
The ajax ( or the Footnote changes would be my guess. Footnoot just because of the wide click handler, and the Ajax because I also get the error in IE11 that traces back to this line https://github.com/wet-boew/wet-boew/commit/2a124edac846f5db4e724b004ed42b5655a56711#diff-dd1363cc412915aee590b9328d30f8f8R119 where it loos like `url` is null
```console
Unable to get property 'url' of undefined or null reference
```
Maybe the something in the string building here is null https://github.com/wet-boew/wet-boew/pull/7983/files#diff-bbb620e471bcab99c88c69c3d2a5d27eR47, so the whole thing becomes null

**Comment by duboisp** [comment]
I was able to reproduce the error with the [menu working example](http://wet-boew.github.io/v4.0-ci/demos/menu/menu-en.html). I will look at it this week-end.

**Comment by shawnthompson** [comment]
I added the code to the source on this page and it works.

https://shawnthompson.github.io/wet-boew-menu-details/unmin/index-fr.html

The English page still uses ajax and still has the problem.
