### ISSUE TITLE
Data Ajax: data-wb-ajax: cdn menu

### ISSUE THREAD

**Issue by shawnthompson** [wet-boew/wet-boew#8241]
When using `data-wb-ajax` and the menu on _cdn.canada.ca_ the close button does not appear.

![image](https://user-images.githubusercontent.com/2575266/34503958-7703825e-efe9-11e7-8c7d-d76a29cd6e3d.png)

Working example

https://shawnthompson.github.io/gcweb-ajax-menu/content-en.html

Change made:

https://github.com/shawnthompson/gcweb-ajax-menu/commit/6a7bb4002f754cd937720b89871dec9b45c933ac

**Comment by kodecount** [comment]
Just FYI on an iPhone 6 with iOS 11.2.1 your example doesn’t work. www.canada.ca is working though

**Comment by shawnthompson** [comment]
Canada.ca isn't using the ajax menu. How is it not working on the iPhone 6? It's not supposed to work. It's missing the X to close the modal.

**Comment by duboisp** [comment]
**Background:** On content insertion, like with the data-ajax, there is no initialization of WET "sub"-feature by default. It is like that since WET 4.0.0 and in the [data-ajax documentation](http://wet-boew.github.io/wet-boew/docs/ref/data-ajax/data-ajax-en.html) there is instruction showing how you can do it.

**The issue:** The close button is added when the overlay plugin are initialized. 

**A possible solution:** Modify the overlay plugin to add the close button before to overlay being opened.

@shawnthompson feel free to submit a PR.

**Comment by shawnthompson** [comment]
@StdGit Can you look into this?

**Comment by StdGit** [comment]
Hi, I'm not sure if you are aware and if it is related to ajax or just Basic Html, but on 
https://www.canada.ca/en/services/business.html?wbdisable=true
The submenus don't appear.
![image](https://user-images.githubusercontent.com/5129874/43971000-72186122-9c9d-11e8-93af-93174d2ef5dd.png)

**Comment by StdGit** [comment]
Is it the normal behavior ?

**Comment by duboisp** [comment]
In basic HTML mode the menu, which is an ajax fragment, is not downloaded. The data-ajax plugin is disabled.

The mobile menu is only available in "standard mode".

FYI - Enabling the data-ajax in the basic html mode won't fix this issue.
