### ISSUE TITLE
Googleapis certificate issue causing jQuery errors

### ISSUE THREAD

**Issue by muling** [wet-boew/wet-boew#8337]
There is a certificate issue for the googleapis jQuery, which is causing errors in IE11 and Chrome, because jQuery is not being loaded. Changing
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.js"></script>

to

<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.js"></script>

Resolves the issue.

**Comment by muling** [comment]
In IE, my security settings are set to : 
Internet: Medium-high, Enable Protected Mode is checked
Local intranet: Medium-low, Enable Protected Mode is unchecked
Trusted sites: Medium, Enable Protected Mode is unchecked
Restricted sites: High, Enable Protected Mode is checked

**Comment by muling** [comment]
Then why does Canada.ca site have it modified?

**Comment by LaurentGoderre** [comment]
I'm not sure if they modified it or if they never updated their HTML to use HTTPS.

**Comment by muling** [comment]
They have it without the protocol.

**Comment by LaurentGoderre** [comment]
Yeah I saw. When Canada.ca launched we hadn't switched to HTTPS-first then so it's possible that they still haven't updated yet.

You should open a support request with your IT department because if you are having problems with Google certificates, you probably will have more problems than with just WET.

**Comment by Pacoup** [comment]
These certificate issues can be caused by corporate firewalls acting as proxies as well. For example, where I work, HTTPS content is proxied through a Check Point security gateway to filter viruses, prevent users from accessing file sharing sites, etc.

Unfortunately, because this effectively MITM attacks the TLS connection, this has the effect of often breaking many things.

You may wish to host jQuery locally for your own site, but if there's certificate problems with your proxy, like @LaurentGoderre said, there's probably more than just WET having problems.

See Cloudflare's [Understanding the prevalence of web traffic interception](https://blog.cloudflare.com/understanding-the-prevalence-of-web-traffic-interception/).

Do you have a screenshot of the specific error in the Chrome console?

**Comment by muling** [comment]
![image](https://user-images.githubusercontent.com/2365028/38327134-781210e2-3815-11e8-824e-0e20d3a0c383.png)

**Comment by muling** [comment]
![image](https://user-images.githubusercontent.com/2365028/38327207-b2857886-3815-11e8-8f65-c8326774ccb9.png)

**Comment by muling** [comment]
This issue only started recently and we haven't changed any settings on our browsers or the WET template code.

**Comment by LaurentGoderre** [comment]
But your IT department could have changed something on your network.

**Comment by Pacoup** [comment]
Yeah, this does look like TLS interception. Try looking at the cert details of the failed request. It will probably say something else than Google Internet Authority. There's nothing WET itself can do to mitigate this, but you can change your jQuery to a local copy as a workaround.

**Comment by muling** [comment]
![image](https://user-images.githubusercontent.com/2365028/38333060-7c2ea9a0-3825-11e8-9543-c223d901e054.png)

**Comment by muling** [comment]
https://textslashplain.com/2017/10/23/google-internet-authority-g3/

This page has some interesting information on G3

**Comment by Pacoup** [comment]
Interesting though, not the problem I thought it was :confused:
