### ISSUE TITLE
Mobile menu with IE11

### ISSUE THREAD

**Issue by bronsl** [wet-boew/wet-boew#8494]
We were in the process of upgrading a web application from WET 4.0.28.1 to 4.0.29 when we noticed that the mobile menu doesn't open in IE11 when using wet-boew.js from the 4.0.29 package.

Upon looking at the distribution templates more closely, we noticed the same problem with some of the files in the download package, including themes-dist-4.0.29-gcweb\localnav\task1\index-en.html, which is the template on which our application's markup is based.

The same issue can be seen in themes-dist-4.0.29-gcweb\content-en.html, which contrasts with themes-dist-4.0.29-gcweb\localnav\index-en.html in which the mobile menu opens fine across browsers.

Has anyone else experienced this issue?

**Comment by duboisp** [comment]
@bronsl I tested in IE11 and I am unable to reproduce your issue. Did you experienced the same issue if you only use the production file on v4.0.29? or only when you replace the binary of v4.0.28.1 build?

**Comment by DHaslip** [comment]
I've been working on this issue with @bronsl.  I can reproduce the issue by:
- downloading the Production files for the Canada.ca theme, v4.0.29 
- extracting the zip file to my local disk
- opening themes-dist-4.0.29-gcweb\localnav\task1\index-en.html with Internet Explorer 11
- re-sizing my browser so that the hamburger icon appears
- then clicking on the hamburger icon and the mobile menu is not displayed

@duboisp when you follow these steps do you get the same result?

**Comment by duboisp** [comment]
You need to access it through a web server, like http://localhost. When running the file locally some browser, like IE11, prevent to run any javascript code.

**Comment by PaulCormier** [comment]
I notice that the data-ajax-replace isn't happening on the file:// pages either. When the menu isn't replaced with AJAX the overlay code isn't initialised. This is due to the change introduced in pull request #8459 which was meant to fix issue #8241.

**Comment by duboisp** [comment]
@PaulCormier if you revert locally the changes introduced by pr #8459 it will resolve this issue?

Did you tried via a webserver without doing any changes?

**Comment by thekodester** [comment]
@duboisp is right here you need to run WET on a server for functionally especially AJAX related. If allowed in your department you can use apps like XAMPP (http://www.apachefriends.org/index.html) to create a localhost environment on your desktop for testing.

**Comment by PaulCormier** [comment]
@duboisp Reverting the change does resolve the issue. In a web server the AJAX runs and the overlay is inited.

@thekodester I have run with, and without, a web server; in relation to this issue I was noting the connection between the AJAX not happening on local pages, and the mobile menus not loading.

Upon further testing I notice that, as @bronsl observed, the Task 1 page does not initialise the overlay on the mobile menu, however the Local Navigation topic page does. I wonder if something else on the Local Navigation topic page is triggering the overlay initialisation of the mobile menu; even when using the file:// protocol, and the AJAX is not loaded.

I've opened issue #8517 to address the overlay init code only running after an AJAX call, but if we can figure out why some pages work it should resolve both issues.

**Comment by thekodester** [comment]
@PaulCormier It would be excepted that 'file://' is block as most browsers do this by default for security reasons as that would be trying to access a file direct on my system and not the servers.

**Comment by thekodester** [comment]
I found no issue with **using** AJAX and generating a mobile menu.

Example:
![untitled2](https://user-images.githubusercontent.com/23484460/48778159-79602000-eca2-11e8-891d-3d00e4959071.png)

IE:
![untitled](https://user-images.githubusercontent.com/23484460/48778171-7e24d400-eca2-11e8-9b1f-1bf52d11c763.png)

This was using wet version 29 (also tested gcweb and same no issue).

**Comment by duboisp** [comment]
@PaulCormier Is your page is fully loaded? You can look in your network tab to see if there any "pending/loading" http request

**Comment by duboisp** [comment]
@StdGit can you try to reproduce this issue in your workstation, thanks

**Comment by PaulCormier** [comment]
@duboisp Yep. Everything's fully loaded. The Google tag manager sometimes takes a little while to load, but removing it from the page doesn't affect my results.

**Comment by StdGit** [comment]
@PaulCormier @bronsl @duboisp @shawnthompson

I replicated with Internet Explorer (Kbb4466536) and Firefox Dev Edition) the following steps
•downloading the Production files for the Canada.ca theme, v4.0.29
•extracting the zip file to my local disk
•opening themes-dist-4.0.29-gcweb\localnav\task1\index-en.html with Internet Explorer 11
•re-sizing my browser so that the hamburger icon appears
•click the hamburger menu

Results:

With IE on an ***apache SERVER*** http://apache/themes-dist-4.0.29-gcweb/localnav/index-en.html
It works all the time.

With IE with ***File open*** C:\- Local\Apache\themes-dist-4.0.29-gcweb\localnav\index-en.html
I experimented the bug (The menu didn't open when I clicked the hamburger menu) 
And it worked sometimes - perhaps the cache.

On firefox it worked all the time on a server

With file open 
it worked all the time but the glyphicon wasn't displayed
span class="glyphicon-search glyphicon">

Also 
Note 1: If your browser profile in the emulation menu (F12) isn't set to Desktop. The menu hamburger didn't appear at all.

Note 2: @PaulCormier Did you try with an apache server or IIS

**Comment by PaulCormier** [comment]
@StdGit For this instance, I believe it is an apache server. In issue #8517, it's a Weblogic server.

**Comment by thekodester** [comment]
@StdGit Reason FireFox work at all with **_File open_** as you're referring to it, is it browser security doesn't block file accessing with AJAX locally. If you're to use Chrome with the file path act more like IE for security reasons.

**Comment by shawnthompson** [comment]
Can we say this issue is a non-issue because the framework needs to be ran on a web server to have it work. This is an issue we've decided a long time ago not to support file:// systems in WET.

As for #8517 we will look into fixing that to allow for non-ajax menus to work. 

Can we close this issue? Thanks for all your testing on this, you folks are awesome!

**Comment by PaulCormier** [comment]
I think the issue here is more along the lines of "why does it work on Local Navigation topic page, but not on the Task 1 page?" I think It's related to whether or not the AJAX event is loading in the menus, and the solution to #8517 presumably will answer why it works sometimes, but not others.

Without more input from @bronsl though, it's hard to say where this issue should lead.

**Comment by bronsl** [comment]
@PaulCormier  Yes, for IE11, the mobile menu only worked in pages similar to the local navigation page.  

I think you're on the right track regarding #8517.  We had integrated it into a web application (running on a server) with no ajaxed-in content, and it was in this scenario that the mobile menu did not work.  We noticed that if you remove the ajaxStop method, the menu will open.

**Comment by bronsl** [comment]
Probable duplicate of #8517, which is now closed.
