### ISSUE TITLE
No mobile menu on non-AJAX menu

### ISSUE THREAD

**Issue by PaulCormier** [wet-boew/wet-boew#8517]
I'm using 4.0.29 with a non-AJAX menu. The "wb-init.wb-overlay" event isn't being called on the mobile menu because there's no AJAX happening to trigger the function passed to ajaxStop in:
https://github.com/wet-boew/wet-boew/blob/9e85c8b2099ae1de5b4d1c0b331a0a5df4ed6fb7/src/plugins/menu/menu.js#L322-L332

**Comment by thekodester** [comment]
I can confirm that since version 4.0.29 that if you hard code the menu and **do not use** AJAX then mobile menu fails.

**Comment by shawnthompson** [comment]
Canada.ca hard codes their menu but they are only using v4.0.28.1. 

https://www.canada.ca/en.html

**Comment by Pacoup** [comment]
The commit which appears to be break this is https://github.com/wet-boew/wet-boew/commit/8de48593fac3e24307dda4e79e10d7fc5dfdde08.

We are also using a hard coded menu where I work but we're still on v4.0.28.1.

Not super nice, but maybe the code could be moved to a function and that function could be called twice, once normally (like before), and once on ajaxStop. More of a workaround though. Not sure how this could be fixed otherwise without breaking https://github.com/wet-boew/wet-boew/issues/8241.

**Comment by StdGit** [comment]
I will have a look at it. Probably this is a side effect of the fix for the ajax menu.

**Comment by StdGit** [comment]
Hi some update on this bug

I was able to run a non-ajax menu with wet 4.0.29 and the fix for the ajax menu

![menu sans ajax](https://user-images.githubusercontent.com/5129874/48959718-45505d80-ef35-11e8-825a-1937eb0cb5e3.JPG)

In [https://wet-boew.github.io/wet-boew/demos/menu/menu-en.html](url)
Section menu-include-en.html
The first div is `<div class="pnl-strt container visible-md visible-lg nvbar">
`

I believe it should be 
`<div class="pnl-strt container visible-md visible-lg nvbar wb-menu" data-trgt="mb-pnl" >`
  
    <h2>Topics menu</h2>
    <div class="row">
        <ul class="list-inline menu">
            <li><a href="https://www.canada.ca/en/services/jobs.html">29Jobs</a></li>
            <li><a href="https://www.canada.ca/en/services/immigration-citizenship.html">Immigration</a></li>
            <li><a href="https://travel.gc.ca/">Travel</a></li>
            <li><a href="https://www.canada.ca/en/services/business.html">Business</a></li>
            <li><a href="https://www.canada.ca/en/services/benefits.html">Benefits</a></li>
            <li><a href="https://www.canada.ca/en/services/health.html">Health</a></li>
            <li><a href="https://www.canada.ca/en/services/taxes.html">Taxes</a></li>
            <li><a href="https://www.canada.ca/en/services.html">More services</a></li>
        </ul>
    </div>

`</div>`

With `wb-menu" data-trgt="mb-pnl" ` the event is triggered
Make sure also that jquery is loaded.

For task1 it break

But if we add the fix proposed by @Pacoup it will work.
I will do it next week

![menu sans ajax_task1](https://user-images.githubusercontent.com/5129874/48960177-a7f72880-ef38-11e8-8a9f-d20f1c90c13b.JPG)

**Comment by StdGit** [comment]
@neilmispelaar
The fix https://github.com/wet-boew/wet-boew/pull/8524 for this issue could break if the version of jquery change. The fix use an internal variable 
https://github.com/StdGit/wet-boew/blob/9d020c45ac78ecb91c06f7844bba9cf4ea15629f/src/plugins/menu/menu.js#L322
that isn't exposed in jquery API 
https://stackoverflow.com/questions/3148225/jquery-active-function
Use of jquery.ajax.active could probably fix the issue once jquery is updated

**Comment by duboisp** [comment]
@StdGit have you look if that property is still available in jQuery 3?

Neil has started the work on the migration of jQuery 3, but it was moved on other priority in his department. So currently the jQuery 3 migration project is stale.

If it is a special behaviour that you want to ensure it is kept, then @StdGit please submit a PR that will update the documentation of hte Menu plugin. You can documents the behaviours you are expecting here:
* https://github.com/wet-boew/wet-boew/blob/master/site/pages/docs/ref/menu/menu-en.hbs
* https://github.com/wet-boew/wet-boew/blob/master/site/pages/docs/ref/menu/menu-fr.hbs

Consider the design pattern for mobile menu has changed (major) for gcweb since the release of GCWeb v5.
