### ISSUE TITLE
Feeds: Widget not working

### ISSUE THREAD

**Issue by CaroGagnon** [wet-boew/wet-boew#8530]
The feeds widget seems to have failed.

**Comment by duboisp** [comment]
Thanks for reporting the issue. I just find out the yahoo API that we were using has been retired. https://developer.yahoo.com/yql/

Some research would be required to find a few alternative API services.

The next version of wet-boew include an update to the feed plugin that take advantage of COORS. May be it would worth to have that as the default to read the feed instead of using an external API.

**Comment by michael-milette** [comment]
Good morning Pierre,

Bonne année !

- Will this fix it for the WET 4 theme as well?
- What is the estimated release date?

This issue is affecting many departments such as but not limited to:

https://www.canada.ca/en/employment-social-development.html
https://www.canada.ca/en/revenue-agency.html
https://www.canada.ca/en/food-inspection-agency.html
https://www.canada.ca/en/canadian-heritage.html
https://www.canada.ca/en/department-national-defence.html
https://www.canada.ca/en/public-health.html
https://www.canada.ca/en/shared-services.html
https://cfc-swc.gc.ca/index-en.html
https://www.international.gc.ca/gac-amc/index.aspx?lang=eng
http://www.agr.gc.ca/eng/home/?id=1395690825741
http://www.dfo-mpo.gc.ca/media/media-room-salle-des-medias-eng.html
https://www.nrcan.gc.ca/home

Best regards,

Michael Milette

**Comment by Bgolden67** [comment]
@michael-milette 
this is probably affecting almost all IP pages on canada.ca as that feed is part of the IP Page template.
I have 3 sites as well it's affecting.

**Comment by michael-milette** [comment]
If anyone is interested and has access to PHP on their site, I recently published a solution which reads the XML atom feed and converts it into a list of HTML list items (<li>...</li>). You need only find a way to call it from your web page (it is not JavaScript).

See https://github.com/michael-milette/atom-newsfeed . Documentation is currently included in the source code.

Working example:
    https://cfc-swc.gc.ca/news-nouvelles/index-en.html

Hope it helps! Let me know if you have any questions.

Best regards,

Michael Milette

**Comment by duboisp** [comment]
> I have tried using the CORS enabled pulling as in the example

It will be included in the next version version of WET (4.0.30).

**Comment by michael-milette** [comment]
Hi @duboisp ,

1) Will that be fixed for the "Government of Canada Web Usability theme" as well?

2) When do you foresee that WET (4.0.30) will be released?

Best regards,

Michael

**Comment by thekodester** [comment]
@michael-milette The theme "Government of Canada Web Usability theme" was abandoned see https://github.com/wet-boew/wet-boew/issues/8366.

**Comment by michael-milette** [comment]
Does this mean that we can now use the Canada.ca theme with our own menus? For example:
https://www.statcan.gc.ca/eng/start

**Comment by Bgolden67** [comment]
@michael-milette I think you need to check the Canada.ca Information Architecture and style guide. I could be wrong but i believe that is not allowed, but if it is, this would be good to know.

**Comment by duboisp** [comment]
FYI - We are currently working on a solution for the Feed. We are going to provide some instruction on how to apply a patch for older version of wet-boew, including the "Government of Canada Web Usability" theme.

**Comment by CaroGagnon** [comment]
Thank you, @duboisp.

**Comment by duboisp** [comment]
FYI - The patch that I am working on for the older wet-boew will allow existing wet-boew implantations to read the news feeds from Canada.ca. Some content change will be required in order to use that work-around.

PR #8534 would make the feed plugin read the xml feed directly instead of going through the Yahoo API to get the JSON version of it. That fix is planned to be included in the next release (v4.0.30) scheduled for the end of the month.

**Comment by Bgolden67** [comment]
@duboisp will the fix itself be made available before the release or do we have to wait to update a full release

**Comment by CaroGagnon** [comment]
Thank you. This issue has been resolved: https://github.com/wet-boew/wet-boew/releases/tag/patch-v4.0.21-to-v4.0.29
