### ISSUE TITLE
WET4 Calendar (weekends)

### ISSUE THREAD

**Issue by zomby22** [wet-boew/wet-boew#8750]
Hi
Looking for a way to exclude weekends for the WET4 Calendar. So if you have an event that starts Monday and ends Friday next week, the calendar would highlight only the business days, excluding weekends.

Also, a possibility to combined events by column (so events for every Wednesday instead from this start date to this end date, only Wednesday date would be highlighted.

**Comment by juleskuehn** [comment]
Hi zomby,

These features aren't supported but it is possible to achieve the effect you want, at least for the first question (to exclude weekends for multi-day events spanning weekends). What I'm proposing is a **bad solution**, because it will apply this change to all events. The markup format to create the calendar does not support indicating whether a date span includes weekends or not, so we'll just have to make a blanket override that removes event links from weekend dates. (Another approach is to remove the weekend columns themselves).

The JavaScript code below, when loaded after WET, will remove the event links for all weekend dates:
```javascript
(function(){
	$( ".wb-calevt" ).on( "wb-updated.wb-calevt", function( event ) {
		unwrapWeekendLinks();
	});

	$( ".wb-calevt" ).on( "wb-ready.wb-calevt", function( event ) {
		unwrapWeekendLinks();
	});

	var unwrapWeekendLinks = function() {
		$('.wb-clndr table tr').each(function(){
			var cells = $(this).find('th, td');
			$(cells[6]).find('a time').unwrap();
			$(cells[0]).find('a time').unwrap();
		});
	}
})();
```

As for the second question (repeating event every Wednesday), I can't think of any way to do this, except again, globally which wouldn't make any sense. Interesting feature requests!

**Comment by zomby22** [comment]
thanks this works. It does remove the element (background color) however the hover text still exist.
![22](https://user-images.githubusercontent.com/20478259/71683081-87b2b380-2d5f-11ea-95ab-f852df97d2b6.jpg)

**Comment by juleskuehn** [comment]
```javascript
// Remove all weekend events from the calendar
(function(){
    $( ".wb-calevt" ).on( "wb-updated.wb-calevt", function( event ) {
        unwrapWeekendLinks();
    });

    $( ".wb-calevt" ).on( "wb-ready.wb-calevt", function( event ) {
        unwrapWeekendLinks();
    });

    var unwrapWeekendLinks = function() {
        $('.wb-clndr table tr').each(function(){
            var cells = $(this).find('th, td');
            $(cells[6]).find('a time').unwrap();
            $(cells[6]).find('ul').remove();
            $(cells[0]).find('a time').unwrap();
            $(cells[0]).find('ul').remove();
        });
    }
})();
```

**Comment by zomby22** [comment]
thanks so much.
for the "Wednesday only"  - I could always include an option in the database
if Wednesday option true then
cell 0 to 6 excluding 3
end if

**Comment by juleskuehn** [comment]
If you want to add more custom repeats (like the Wednesday only) you need some way of communicating to the JavaScript (through the DOM) that the events only repeat on a certain day, e.g.
```html
<h4><a href="https://www.canada.gc.ca" data-wbcal-repeat="weekday">Every weekday</a></h4>
```
or
```html
<h4><a href="https://www.canada.gc.ca" data-wbcal-repeat="wednesday">Every wednesday</a></h4>
```
Then in the JavaScript, check for those attributes and make the changes to the calendar accordingly.

With the two features (weekday only repeats and specific day repeats) it is definitely reaching a level of complexity where you should really modify the plugin code, rather than hack away at what the plugin has done.

**Comment by zomby22** [comment]
ok, one last thing. say I needed to remove the weekend columns, what I need to do to accomplish this?

**Comment by juleskuehn** [comment]
I've included some comments in the code. I hope you can make necessary modifications from here.
```javascript
// Remove all weekends from calendar
(function(){
    // Runs on initial page load
    $( ".wb-calevt" ).on( "wb-updated.wb-calevt", function( event ) {
        removeWeekends();
    });

    // Runs when the calendar is updated (e.g. when a month is changed)
    $( ".wb-calevt" ).on( "wb-ready.wb-calevt", function( event ) {
        removeWeekends();
    });

    // Removes the weekend cells from all calendars
    var removeWeekends = function() {
        // Get every table row which is in a calendar
	var rows = $('.wb-clndr table tr');
        // For each table row:
        rows.each(function(){
            var cells = $(this).find('th, td');
            // Check if the weekend cells have already been removed
	    if (cells.length !== 7) return;
            // If not, remove the first and last cells (Sunday and Saturday)
            $(cells[0]).remove();
	    $(cells[6]).remove();
        });
    }
})();
```

**Comment by zomby22** [comment]
thanks for all your help.
