### ISSUE TITLE
Validation errors with details - accessibility

### ISSUE THREAD

**Issue by marieeved** [wet-boew/wet-boew#8762]
HI,

I use the CMS Teamsite for my website in ESDC. Pages with details element always generated a validation error (before I can publlish it). but since a few week, I learned that Teamsite will not allow that I publish pages with validation errors (team of developpers for Teamsite will change parameters for accessibility new restrictions).

Since I use the details element just like in the examples of WET. The details element should not be used anymore??? 
![validation errors](https://user-images.githubusercontent.com/13418868/68960291-e61ad700-079d-11ea-805c-1c4412266442.jpg)

anyone aware of this?
Thanks

**Comment by thekodester** [comment]
The message is just telling you "details" are not apart of IE it not actually a validation issue, but more of just a information message. WET uses a Polyfill to produce details/summaries.

https://caniuse.com/#search=details

**Comment by thekodester** [comment]
I recommend talking to your team about how it not really a validation issue and how WET uses a polyfills when not supported by the browser.

###### I am just a volunteer on this GitHub project.

**Comment by EricDunsworth** [comment]
The publishing workflow in that Teamsite implementation uses a super outdated version of the [HTML validator](https://validator.w3.org/nu/). Teamsite's copy of the validator probably hasn't been updated in several years.

Years ago, only one major browser rendering engine (Webkit - used by Safari and Chrome at the time) natively supported the ``<details>`` element. So the HTML validator showed a warning when it encountered ``<details>``. It wasn't a problem in WET though since it includes a ``<details>`` polyfill. The validator's warning was removed a few years ago after native support was added to Gecko (used by Firefox).

@marieeved I'd recommend these:
1. Try validating your code on the [W3C's NU HTML validator](https://validator.w3.org/nu/) (it's more up-to-date than what Teamsite is using)
2.  Send an NSD ticket to get the copy of the validator updated in ESDC's Teamsite implementation.
3. Maybe consider sending another NSD ticket to suggest enhancing Teamsite's publishing workflow to make a distinction between errors and warnings.

**PS:**
ESDC's Teamsite publishing workflow doesn't seem to make a distinction between warnings and errors. Both the details and section lacks heading messages in your screenshot are technically warnings. But Teamsite is treating both as if they were errors.

FWIW I'd personally try to avoid warnings as much as possible. But on occasion there are some warnings that can't be worked around.

**Comment by EricDunsworth** [comment]
I forgot to mention this in my previous comment, but I believe it's possible to get through the validation step in ESDC's Teamsite publishing workflow even when it shows issues. There should be a button somewhere that lets you approve with errors.

I can't comment on the "**Shortly Validation with errors will not be allowed**" message. If that were to suddenly happen without corresponding updates/enhancements to ESDC's Teamsite validator, it'd probably become impossible to publish any pages that contain ``<details>`` elements...

**Comment by grifare** [comment]
Teamsite, for no reason whatsoever, has no authority to decide what cannot be published. If they set policies that validate-out pages, which is probably a breach of contract, at least they first must update their validator.

However, I think this is less of a technical issue than a managerial issue.  There should be a way of allowing anything any client wants to publish.

I would consult with the law department and remove this issue from the accessibility topic.

**Comment by duboisp** [comment]
@grifare The situation here seem to be related to how ESDC IT department has configured Teamsite.

@marieeved has @EricDunsworth mentioned, the best solution would be for your to submit a request to your IT service desk (NSD ticket).

**Comment by EricDunsworth** [comment]
Closing this since it has nothing to do with WET and since the discussion seems to have wrapped up.
