### ISSUE TITLE
Reuseable components libraries

### ISSUE THREAD

**Issue by alexgagnon** [wet-boew/wet-boew#8904]
Hi there,

We support several applications using WET and the canada.ca theme in our branch, using various technologies like Struts, Thymeleaf, .NET, Angular, and even static markup. There's a lot of duplication of hardcoded HTML that comes with this, and it can be cumbersome when a new version of the theme is released to update it all (for example, getting all the class names right.)

I've read through a couple issues on here about integrating WET/themes with React/Angular/Vue/<insert framework>. I notice that the demo site is actually produced using Handlebars. I also know there's the CDTS system as well, however these include only top level components like headers and footers. Is there any appetite for creating a component library to support the widgets you've defined in the styleguide (as in, alerts, datatables, etc.)? For example, one place to start might even be publishing a more reusable version of the Handlebars components.

**Comment by thekodester** [comment]
This is just my two cents, but I don't think there a simple way for WET to create component libraries, especially with things like datatables cause there too many factors (filters or no filters, json or no json, sorting or no sorting, searching or no searching, and so on).

I also think this is more of a issue on how your department is coding. You even mention "a lot of duplication of hardcoded HTML" it sounds like you need to create better ways to generate pages.

I have WET demo site created using PHP, and I have common html code libraries that are reused for every page. My main site (uses bootstrap) is python and does a the same thing.

My point is it sounds like internally you need to create better templating as this is more commonly done on the backend (PHP, Python, Java, etc) and WET is frontend.

###### I am just a volunteer on this GitHub project.

**Comment by alexgagnon** [comment]
That's basically my point. Sounds like you've produced *local* templates for the sites you work on. How will you share that with other applications you're going to build? What if you need to share it with another team? The widgets in the styleguide are universal to anyone implementing the theme. What 'authority', so to speak, would the components that my team/branch/directorate/department create? It would seem more effective that if this were to be pursued, they were at least owned/lead by the team that produces the styleguide we're trying to meet (with contributions from other departments, hopefully!)

Example to clarify. This component from the the wet-boew repo (https://github.com/wet-boew/GCWeb/blob/master/site/includes/alert.hbs):
```
<section class="alert alert-info">
	<h2 class="h3">{{{i18n "institution-alert-title"}}}</h2>
	<p>{{#is page.language "en"}}Our current <a href="#">[insert institution / organization name] website</a> will remain available until the move to Canada.ca is complete.{{else}}Le <a href="#">site Web actuel du / de / de la / de l’[ajouter le nom de l’institution / l'organization]</a> restera accessible jusqu’à ce que le transfert vers Canada.ca soit terminé.{{/is}}</p>
</section>
```

Might be modified to something like:
```
<section class='alert{{#if type}} alert-{{type}}{{/if}}>
  {{{body}}}
</section>
```

Which would allow us to use it as so:
```
{{#> alert type='info' body='<div>Hello!</div>'}}{{/alert}}
```

Publishing these to npm should (barring breaking changes) make it easier to update dependencies over time, and increase consistency across those who implement the theme.

I'm not suggesting one language/framework over another, just seeing if there's appetite.

And I disagree that components don't work with WET. Templating using Handlebars/PHP/Jinja/Thymeleaf/whatever, and server-side rendered frameworks definitely produce enough markup to have the WET scripts execute correctly on first render. And even with client side ones it's doable too, but managing the triggers on re-render is admittedly a bit more work.

**Comment by thekodester** [comment]
As for the code you are referencing is how GitHub renders webpages is not how Canada.ca is producing content.

As for these questions:

**How will you share that with other applications you're going to build?/What if you need to share it with another team?**

I personally own and operate five website sites with little to no maintenance because I reuse my library across each site. Four of my sites are bootstrap with custom css/js to change how each looks and functions. The core html, css, and javascript is shared across all four sites.

In a government department it would be as simple as having an internal library where code is shared or even a private GitHub repo where code is shared for that department to use. On top of having a shared library there should be a group that reviews all applications to make sure they are using this shared code.

I actually worked at Veterans Affairs Canada for a time long ago and they did this. It made applications made even with different languages simple to update as they shared code libraries (like login interfaces for example).

**The widgets in the styleguide are universal to anyone implementing the theme. What 'authority', so to speak, would the components that my team/branch/directorate/department create?**

That is up to your department. WET is not meant to be the end all be all. It is a step stoning and guide on how your site should function, but not necessarily how it should look.

Reason I disagree with this it takes away from the purpose of WET. Look at my demo site (thekodester.ca/wet/) for WET it looks nothing like any of the default themes.

**Comment by alexgagnon** [comment]
> In a government department it would be as simple as having an internal library where code is shared or even a private GitHub repo where code is shared for that department to use. On top of having a shared library there should be a group that reviews all applications to make sure they are using this shared code.

I'm seeing if there's interest in having this as a communal repo centrally in this organization, rather than each department doing this.

**Comment by thekodester** [comment]
I get that and respect that, but it probably not gonna happen unless multiple departments commitment to maintaining a repo.

WET has actually abandoned many repos due to amount of work to maintain and budgeting.

You can read about that here https://github.com/wet-boew/wet-boew/issues/8366.

###### I am just a volunteer on this GitHub project.

**Comment by seanpoulter-foci** [comment]
> I'm seeing if there's interest in having this as a communal repo centrally in this organization, rather than each department doing this.

Yes @alexgagnon, there is interest. I've found WET-BOEW doing initial research to build a proof of concept. I'm hoping to find all the components in a collaborative design tool library (like Figma), and docs for how to use the components from the [most popular front-end frameworks](https://2022.stateofjs.com/en-US/libraries/front-end-frameworks/) like React, Angular, Vue, or Svelte.

I was hoping to find a themeable front-end component library built with Web Components, and wrappers for popular frameworks. Web Components have matured:

* In 2018 Google put the Polymer project in maintenance mode in favour of Web Components. 
* Also in 2018 SalesForce introduced their Web Component library ([blog](https://developer.salesforce.com/blogs/2018/12/introducing-lightning-web-components)).
* In 2021 GitHub shared their experience with Web Components ([blog](https://github.blog/2021-05-04-how-we-use-web-components-at-github/))

Web Components reduce the cost of maintaining other repos since the Web Components encapsulate the style and behaviour behind the public API. This removes the need to update every place a component is used. It simplifies the use in PHP, React, etc.
