### ISSUE TITLE
"TypeError: undefined is not an object..." with Table Validator

### ISSUE THREAD

**Issue by thekodester** [wet-boew/wet-boew#8906]
Full Error:
TypeError: undefined is not an object (evaluating 'a.row.length')

Steps:
Go to https://wet-boew.github.io/v4.0-ci/demos/tablevalidator/tablevalidator-en.html
Enter `<table></table>`
Check console

**Comment by GormFrank** [comment]
@thekodester The table validator hasn't changed in years, so it has always been like that. Not that it isn't a problem, however like the author of the Table validator @duboisp mentioned, this validator is based on the premise that you have followed the [12 table techniques](https://wet-boew.github.io/wet-boew-legacy/v3.1/demos/tableparser/index-en.html), which would give you at least a little bit of content in your table for sure, and making it worthy of being validated. In other words, you need to have at least to columns of content in your table in order to not have console errors, which any table should have. Does that make sense?

**Comment by thekodester** [comment]
For certain!
