### ISSUE TITLE
Multimedia Player - Video: Only title used to generate label for form element

### ISSUE THREAD

**Issue by szet0018** [wet-boew/wet-boew#8939]
Multimedia Player - The label for the Volume control
https://wet-boew.github.io/v4.0-ci/demos/multimedia/multimedia-en.html

`<input type="range" class="volume" aria-controls="wb-auto-2-md" aria-labelledby="wb-auto-2-md" title="Volume" min="0" max="100" value="100" step="5">`

The title attribute is only supposed to provide extra or fallback information, not essential information.
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/title

Suggested Solution
Add an visually hidden label element "Volume"

**Comment by EricDunsworth** [comment]
Another way could be to add ``aria-label`` attributes to supplement the ``title`` attributes.

FWIW I'm not a big fan of ``title`` attributes in general and personally never use them.

But for something like the multimedia player... the tooltips they produce could potentially come in handy for some users. Like when someone using a mouse hovers over one of the media player's controls and gets a tooltip describing its function. Although that wouldn't work for sighted users that navigate via keyboard or other means. But it's better than nothing.

Ideally it'd be better to use a dedicated tooltips plugin to do that kind of thing since it'd work in more scenarios (like showing up when an interactive element receives keyboard focus). FWIW Bootstrap 4.x has a [tooltips plugin](https://getbootstrap.com/docs/4.1/components/tooltips/) that appears to be accessible and use a progressive enhancement approach, but WET is still stuck on Bootstrap 3.x to this day. So I don't think that'd be a viable option until WET 5.0.

**Comment by EricDunsworth** [comment]
Whoops, didn't realize most of the media player's controls were already using visually-hidden text.

I'll send over a PR to add an ``aria-label`` attribute to the volume slider. IMO it'd be a better bet than a visually-hidden label in this case since its label isn't meant to be shown on-screen.

**Comment by EricDunsworth** [comment]
Ended up not doing with ``aria-label`` nor a standard label for #8947.

The volume slider's ``aria-labelledby`` attribute (which causes the video's title to be announced) superseded my ``aria-label`` attribute. Then I tried another test with a standalone label and reached the same outcome. Then I found that ``aria-describedby`` seemed to work best and based the PR on that.
