### ISSUE TITLE
how can we have struts2 and WET4 form validation working together?

### ISSUE THREAD

**Issue by mingjiongliao** [wet-boew/wet-boew#9012]
WET4 form validation plugin only have example of ASP.NET. I am wondering how other framework like java, php or others, anyone successfully make it work?

**Comment by mingjiongliao** [comment]
#8627

**Comment by thekodester** [comment]
As I explained before in https://github.com/wet-boew/wet-boew/issues/8275#issuecomment-364144455

If you generator the following html:
```
<section id="errors-validation-example" class="alert alert-danger" tabindex="-1">
<h2>The form could not be submitted because 8 errors were found.</h2>
<ul><li><a href="#title1"><span class="prefix">Error&nbsp;1: </span>Title - This field is required.</a></li></ul>
</section>
```

It well clear the existing error. The only thing that really matters is this HTML and ID:
`<section id="errors-validation-example" class="alert alert-danger" tabindex="-1"></section>`

If where looking at the demo page https://wet-boew.github.io/v4.0-ci/demos/formvalid/formvalid-en.html

The ID is auto generated to match the form ID so the id needs to be `errors-FORMID`.

**Comment by mingjiongliao** [comment]
I find this file called form.ftl in the template for the html part you were referring.
<div class="<#t/>
<#if parameters.validate!false>
wb-frmvld<#rt/>
<#else>
wb-frm<#rt/>
</#if>
">
<#if parameters.labelposition?? && parameters.labelposition = "left">
${tag.addParameter('cssClass', 'form-horizontal ${parameters.cssClass!}') }<#rt/>
</#if>
	<#include "/${parameters.templateDir}/${parameters.expandTheme}/form-common.ftl" />
<#if parameters.onreset?has_content>
 onreset="${parameters.onreset?html}"<#rt/>
</#if>
<#if !parameters.validate!false>
 novalidate<#rt/>
</#if>
>


<#if fieldErrors?? && !fieldErrors.isEmpty()>
<#assign eKeys = fieldErrors.keySet()><#t/>
<#list eKeys as eKey><#t/>
<#if (tag.getValidators(eKey))?has_content>
	<section tabindex="-1" class="alert alert-danger" id="errors-${parameters.id?html}">
		<h2 class="h3" ><#rt/>
			<@s.text name="form.error.summary.title">
				<@s.param value="fieldErrors.size()" />
			</@s.text>
		</h2>
		<div class="hidden-xs">
			<@s.fielderror class="error" theme="simple"/>
		</div>
	</section><#t/>
<#break>
</#if>
</#list>
</#if>

**Comment by thekodester** [comment]
I don't understand your comment, maybe a demo is easier to understand.

Please see https://github.com/thekodester/struts2-wet-form-validation/blob/main/WebContent/register.jsp

**Comment by thekodester** [comment]
Here is a bit of a break down for you.

### WET Validation:
```
<div class="wb-frmvld">
```

### Struts Form:
```
<s:form id="validation-example" action="register" theme="simple">
```

Required form attributes:
- `id=""`
  - can be any value
- ` theme="simple"`
  - this needs to be simple other wise struts creates the html using tables

### Struts Validation:
```
<s:if test="hasFieldErrors()">
<section id="errors-validation-example" class="alert alert-danger" tabindex="-1">
<h2>The form could not be submitted because errors <s:property value="fieldErrors.size()" /> were found.</h2>
<s:fielderror/>
</section>
</s:if>
```

`hasFieldErrors()` checks if error was called (this is produced by `addFieldError` in Register.java)
`fieldErrors.size()` checks how many error were called (this is produced by `addFieldError` in Register.java)
`<s:fielderror/>` generators a list of all errors produced by  `addFieldError` in Register.java

### Struts Inputs:
```
<div class="form-group">
<s:label for="personBean.lastName" value="Last Name" />
<s:textfield cssClass="form-control" id="personBean.lastName" name="personBean.lastName" />
</div>
```

Since where using SIMPLE theme we need to match WET html format.

**Comment by thekodester** [comment]
Here is a bit of a break down for you.

### WET Validation:
```
<div class="wb-frmvld">
```

### Struts Form:
```
<s:form id="validation-example" action="register" theme="simple">
```

Required form attributes:
- `id=""`
  - can be any value
- ` theme="simple"`
  - this needs to be simple other wise struts creates the html using tables

### Struts Validation:
```
<s:if test="hasFieldErrors()">
<section id="errors-validation-example" class="alert alert-danger" tabindex="-1">
<h2>The form could not be submitted because errors <s:property value="fieldErrors.size()" /> were found.</h2>
<s:fielderror/>
</section>
</s:if>
```

`hasFieldErrors()` checks if error was called (this is produced by `addFieldError` in Register.java)
`fieldErrors.size()` checks how many error were called (this is produced by `addFieldError` in Register.java)
`<s:fielderror/>` generators a list of all errors produced by  `addFieldError` in Register.java

Required form attributes:
- `id=""`
  - must be errors-FORM_ID

### Struts Inputs:
```
<div class="form-group">
<s:label for="personBean.lastName" value="Last Name" />
<s:textfield cssClass="form-control" id="personBean.lastName" name="personBean.lastName" />
</div>
```

Since where using SIMPLE theme we need to match WET html format.

**Comment by mingjiongliao** [comment]
@thekodester 
Great, Thank you!

**Comment by mingjiongliao** [comment]
The only issue we have now is that all our form validation is set up by XML files, which can not be customized to wet template.
https://struts.apache.org/getting-started/form-validation-using-xml.html#:~:text=Struts%202%20provides%20several%20different,the%20Struts%202%20requiredstring%20validator.

**Comment by thekodester** [comment]
The method of validation does not change the approach. The approach demonstrate changes the JSP file. You can still modify the JSP.

**Comment by mingjiongliao** [comment]
![image](https://user-images.githubusercontent.com/22457102/104042908-0e874100-51a9-11eb-9d16-0635b22fb65b.png)
this is our current feature. there is no link to the field. 
![image](https://user-images.githubusercontent.com/22457102/104043044-3b3b5880-51a9-11eb-80a2-e57773ebe620.png)

**Comment by RobJohnston** [comment]
Unless things have changed, server-side validation doesn't have to be an exact match.  See:

https://github.com/wet-boew/wet-boew/issues/2852#issuecomment-23274386
https://github.com/wet-boew/wet-boew/issues/2852#issuecomment-23277128

**Comment by mingjiongliao** [comment]
the only issue of this is the accessibility. for example, link the error message at the top to the field. display the error order(e.g. Error1: First name - This field is required).

**Comment by thekodester** [comment]
You should be able to modify how they are being display JSP pages are quite powerful

Are you able to provide any of your current XML and JSP code?
