### ISSUE TITLE
[BUG] Multimedia player (YouTube) - conflict with Doaction plugin

### ISSUE THREAD

**Issue by Christopher-O** [wet-boew/wet-boew#9123]
## Required information

**Describe the bug**
When running a doaction plugin with the multimedia plugin importing a YouTube video, the doaction plugin does not work.  It seems the script for the YouTube video is conflicting or not at a ready state.

**To Reproduce**
I have provided an example to show that it does not work with the YouTube video render
http://test.canada.ca/cra/bugs/video-yt-render.html 
(When pressing the button the doaction should addClass "bg-info" to the text).

When adding a 1 to the class wb-mltmd to the element that has the youtube video in the following example (thus making the youtube video not render), the doaction works as expected
http://test.canada.ca/cra/bugs/video-yt-norender.html

**Expected behavior**
The YouTube video and doaction should work independently on the page.  I have provided an example where I have added a wb.ready element `wb.ready($(eventTarget), componentName)` to the inpage multimedia player script, changed the component class name so there is no conflicts and now both the YouTube video player and the doaction function as normal
http://test.canada.ca/cra/bugs/video-yt-render-fix.html  

**Who shall do the work?**
I would like Principle Publisher or someone to review if my fix is the correct course of action, or if there is another way to resolve the conflicts

**Comment by EricDunsworth** [comment]
Good catch :)! I also ran across this bug a few weeks ago and was trying to troubleshoot it recently to no avail.

@dubbs @GormFrank Thoughts?

**Comment by Christopher-O** [comment]
I just tested my "fix" and realized that it's not the correct solution, as it makes wb.ready "undefined" rather than true or false, which is probably why it just renders both scripts.  So it will need a more stable fix.

**Comment by Christopher-O** [comment]
A somewhat related (depending on the issue with whatever script is causing the issue), but when using multiple source files in a video element, one from youtube and one hosted locally, in case the user is blocked from YouTube (e.g. a government worker), the alternative file does not play, so a local file cannot be used as a fallback if YouTube is blocked.  I don't know if the mp4 files were not intended to be a fallback to YouTube or not...but it would be a nice way to support people who have blocked access, but still utilizing the more optimal streaming of YouTube's servers.

**Comment by EricDunsworth** [comment]
@Christopher-O Might be a better bet to create a separate issue for that since it's unrelated to this issue's bug.

But I'll chime in any case :).

My take on setting a video's sources to a mix of YouTube and real video formats is that it'd make sense to support that scenario since YT was implemented as a "fake" source type.

The multimedia player's YT support probably wasn't originally implemented with that in mind though. The goal behind it was probably to allow implementers to reference YT videos **instead** of self-hosting video files. Makes things much snappier from a publishing standpoint.

I'm not so thrilled about how blocked YT videos currently look like giant empty spaces in WET pages. I might send a PR at some point to try addressing that (like hiding the empty space before a video loads or launch an empty player with an error message). But what you're proposing could tie into that to allow self-hosted versions of the video to be used as fallbacks.

**Comment by Christopher-O** [comment]
@EricDunsworth no worries, thanks for the information. I feel that fixing the solution above may have the unintended consequences of fixing the other issue.  I'm more concerned with the issue I initially raised since we can use doaction for other fallbacks but not if the YouTube video implementation renders doaction inoperable.

**Comment by EricDunsworth** [comment]
@Christopher-O @GormFrank @Ricokola @polmih Should this issue be closed?

#9400 was merged a few weeks ago and seems to have fixed this clash.

I tried a few quick tests just now just to be 110% sure. Created a one-off GCWeb test page with a YouTube video and a WIP page feedback widget. All of my widget interactions worked.

The only quirk I noticed was that in networks that block YouTube, the YT player takes several seconds to fail and enter a ready state. Any actions that are triggered before the player becomes ready get delayed in the meantime. Queued actions kick in once the player shows an error message ("Video encountered loading issues").

**Comment by Christopher-O** [comment]
@EricDunsworth yes, the issue has been resolved.   Thanks for the reminder.
