### ISSUE TITLE
"required" label seems  redundant Form validation: 

### ISSUE THREAD

**Issue by StacyBleeks** [wet-boew/wet-boew#9132]
All form field working examples announce "required" twice for screen readers. Is this necessary? IMO hearing "required" twice is diconfusing and slightly distracts from the content. 
It is, of course, important to know if a form field is "required" but does it need to be offered twice for each "required" form field?

**Comment by StacyBleeks** [comment]
@duboisp  @thekodester  Can you take a look at this issue? For more background and insight here is a previous ticket that was closed, but I don't think it should have been closed... i am the one who agreed it could be closed, in the original ticket, but I was wrong) Here is the original ticket. https://github.com/wet-boew/wet-boew/issues/7002
I believe we can now safely say that the "required" label is redundantt. if you look through the comment thread, the thought was that the double label was making the form field future proof. That was back in 2016. Now we are in the future and the issue remains.

**Comment by StacyBleeks** [comment]
@dfarough  @dorina1  since you were part of the original discussion for this issue, do you agree that the issue remains? The issue is, that for screen readers, the "required" label is marked up so that it is announced twice in one form field for all screen readers (even with verbosity levels set to low).

**Comment by dfarough** [comment]
I agree.  Removing the required from the fields will make this much less verbose.
I also agree that including the asterisk in the field labels will allow users to know immediately that the field is necessary.
If speech is stopped at this point however the validation information will be missed.  Not a big problem in my view.
Perhaps in the documentation for this example some of the choices made could be explained.
Especially if the Asterisk is added to the label text rather than relying on the CSS   feature to do this.
Give people choices and recommendations for implementation.

**Comment by thekodester** [comment]
There been discussion for years about remove or making the required in the label hidden.

See https://github.com/wet-boew/wet-boew/issues/8091#issuecomment-584376763.

**Comment by StacyBleeks** [comment]
@thekodester  thanks for sharing #8091 (comment). 
That particular issue is similar, but it seems to point to the "required" state of the form element being "too early". So, while the proposed solution for it claimes to resolve the issue in Firefox, Would you have time to offer an example that I could test across multiple browsers/devices/ screen readers?
Ideally the required state of a form element will only be announced once by screen readers. It's not a huge issue, of course, but the redundant announcement "required required" seems unnecessary and potentially causes confusion for people who hear the required label announced twice. The repeated "required" label is distracting from the content and also makes these form fields seem really really required. Know what I mean?

**Comment by EricDunsworth** [comment]
I'll try sending a PR to roll out what I tried in https://github.com/wet-boew/wet-boew/issues/8091#issuecomment-584376763 in the coming days.

I'm thinking of hardcoding ``aria-hidden`` onto all instances of ``<strong class="required">(required)</strong>`` and modifying the form validation plugin to automatically add ``aria-hidden`` to pre-existing forms via JavaScript (based on whether or not a given label/legend/etc is tied to a one or more fields that are programmatically-identified as required).

That way, the repetition will be eliminated without degrading semantics.

**Comment by StacyBleeks** [comment]
@EricDunsworth  this sounds good, thanks! I'm looking forward to testing your prototype.

**Comment by StacyBleeks** [comment]
@EricDunsworth  good news! .  I have a couple more people interested in testing your prototype, when it's ready. 😃

**Comment by EricDunsworth** [comment]
I can't promise anything, but I'll try to send a pull request for it at some point tomorrow (famous last words :P).

@GormFrank I might need to bug you about posting working examples of that PR on Universal Labs or something.

**Comment by EricDunsworth** [comment]
No PR just yet :(. Still prototyping atm.

I want to try detecting if required text is actually tied to semantically-required fields as a prerequisite to inserting ``aria-hidden="true"`` attributes (as opposed to adding them to all required text across-the-board). That's somewhat trickier since I need to determine relationships between required fields/labels. Plus there are several ways of trying labels to fields that'll need to be taken into consideration.
