### ISSUE TITLE
Footnotes: CSS

### ISSUE THREAD

**Issue by jayellebe** [wet-boew/wet-boew#9170]
If I only wanted the CSS styles to implement the footnote functionality, where might I find them? So far, I have:

.fn-lnk {
    line-height: 1.15;
    margin-left: 5px;
}
	
.fn-lnk, .wb-fnote .fn-rtn a {
	background-color: #eee;
 	border: 1px solid #ccc;
 	display: inline-block;
 	padding: 1px 10px 2px;
 	white-space: nowrap;
}
	
.wb-fnote dt,.wb-inv,.wb-invisible,.wb-show-onfocus,.wb-sl {
	clip:rect(1px,1px,1px,1px);
	height:1px;
	margin:0;
	overflow:hidden;
	position:absolute;
	width:1px
}

.wb-fnote p:first-child {
    margin-top: .11em;
    padding-top: .375em;
}
.wb-fnote p {
    margin: 0 0 0 3.875em;
    padding: 0 .375em .375em;
}

**Comment by duboisp** [comment]
You will find all the information, including style formatted in SCSS, in this folder: https://github.com/wet-boew/wet-boew/tree/master/src/plugins/footnotes

Those SCSS file might require to use variable defined in bootstrap 3 or/and defined here in wet-boew: https://github.com/wet-boew/wet-boew/blob/master/src/_variables.scss

Note the JS used by the footnote plugin improve the navigability and ensure it met the accessibility WCAG.

\cc @EricDunsworth

**Comment by EricDunsworth** [comment]
Just in case it comes in handy, here's the [footnotes plugin's documentation](https://wet-boew.github.io/v4.0-ci/docs/ref/footnotes/footnotes-en.html).

> Note the JS used by the footnote plugin improve the navigability and ensure it met the accessibility WCAG.

In practice the footnotes plugin is responsible for the following extra features:
* Manages the return link in multi-referenced footnotes (check the documentation for more info)
* Adds a [``tabindex="-1"`` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex) to ``dd`` elements. That causes a border highlight effect to appear when the user activates a footnote reference link or clicks/taps any footnote.
* Uses WET's focus event when clicking navigating between footnotes. That prevents footnote link navigation from cluttering the user's browser history (i.e. clicking the back button in a web browser will go back the previous page instead of the last footnote) and hides footnote IDs from the current page's URL.

**Comment by jayellebe** [comment]
Thank you both for the information. Would you happen to have a code sample for folks who want to implement this elegant functionality in html and css only? I wasn't sure what css style made the fn ref number and fn ref text align side by side. I got everything else to work. I appreciate the help and prompt responses.

**Comment by EricDunsworth** [comment]
@jayellebe Here's a [gist of all of the footnotes plugin's generated CSS](https://gist.github.com/EricDunsworth/c19c2046102d8f43e9a19b0dcee07ea5). I excluded IE8 selectors that browser is ancient history.

Hope this helps :)!
