### ISSUE TITLE
[OTHER] Unsure if  script rendering stripping out attributes is a bug or intentional.

### ISSUE THREAD

**Issue by Christopher-O** [wet-boew/wet-boew#9243]
I don't really know if this is a bug, or intentional so I'll call this "other" for now.  But with the newer versions of GCWeb (and maybe WET4), when doing some things like rendering a video or setting up a fieldflow with header content that has a link using target="_blank" that when the script renders, it seems to strip that attribute/value out.  It seem anything that is not href/class/id is removed.  I don't know if this is intentional or not, but it is very odd and provides more limited options in terms of flexibility when displaying and interacting with content.  

If it is intentional, please explain why.  If it's not intentional, I can set up a bug request with a simple example.  Thanks!

**Comment by duboisp** [comment]
@Christopher-O it depends how that HTML is added into your page. If it is manipulated by jQuery, like by using the data-ajax plugin to insert the HTML, then it get sanitized by the [DOMPurify ](https://github.com/cure53/DOMPurify) library. It is working like this since [v4.0.44](https://github.com/wet-boew/wet-boew/releases/tag/v4.0.44.5).

We did this to improve the security and prevent XSS. 

Our testing showed that all plugins still work as expected. 

Sometime there is some alternative. If you want, you can show us your use case during one of the[ weekly Tuesday code sprint](https://github.com/wet-boew/wet-boew/wiki/WET-BOEW-Code-sprint) or you can submit your question to our service desk.

**Comment by Christopher-O** [comment]
@duboisp  Thank you for your assistance on the matter.  Will look forward to any future updates as needed to the script, namely allowing the target blank with the proper noopener noreferrer rel values if possible in a future update!!

**Comment by DBlaisAsc** [comment]
Did you find a way to open on new tab?  I got same issue as you.

**Comment by Christopher-O** [comment]
Currently it strips out target="_blank" due to security concerns with cross-site security issues.  I suggested to @duboisp that if the script could add in rel="noopener noreferrer" if the user adds target="_blank" for added security, that would be awesome.  As of right now, my workaround is writing a small bit of code that adds in target="_blank" after the rest of the script loads.

**Comment by DBlaisAsc** [comment]
Thanks.   I also solved by adding `rel="noopener noreferrer"` and putting back `target="_blank"` with jquery at document.ready().

**Comment by Christopher-O** [comment]
@duboisp  any update with this?  With DOMPurify being updated regularly is there any other work arounds or fixes that can be done, other than making the page in AEM a freestyle page (which we are trying to avoid whenever possible)?
