### ISSUE TITLE
[BUG] Share widget - Subject in "to" field

### ISSUE THREAD

**Issue by colleenhickey** [wet-boew/wet-boew#9257]
When using the "Email" button in the Share widget, &subject is inserted into the "to" field.  

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to canada.ca
2. Scroll to bottom
2. Click on 'Share this page'
3. Click on 'Email'
4. See 'To' field in email (&subject=Home - Canada.ca)

**Expected behaviour**
'To' should be empty.
Subject field should have 'Home - Canada.ca'

## Additional information (optional)

**Desktop**
 - Chrome/Edge/Firefox, MS Outlook

**Comment by crochefort** [comment]
@duboisp step to replicate:
Go to this page : https://wet-boew.github.io/wet-boew/demos/share/share-en.html 
Click on the first Share this page .
And this is how the email is being filled.
![image](https://user-images.githubusercontent.com/4562025/152783983-905d1e6c-f2a3-41eb-b3b4-c3cec7da5442.png)

Looks like the issue is here : 
https://github.com/wet-boew/wet-boew/blob/master/src/plugins/share/share.js#L143 

The line should be change from : 
`url: "mailto:?to=&subject={t}&body={u}%0A{d}",`

to
`url: "mailto:tosomeone@example.com?subject={t}&body={u}%0A{d}",`

Might be easier is you want to do the PR or I can try!

**Comment by kodz1** [comment]
There is on issue on MacOS 12.1 with Mail 15.0 with Safari 15.2, Microsoft Edge 98.0.1108.43, or Firefox 96.0.3.

Also there is no need to set a default email with mailto. It works without. If wanna add a feature where someone can set the to option you're welcome too, but that is not the issue, might be a issue with outlook mail or version of browser you are using. I can test outlook mail in a bit on windows.

###### I am just a volunteer on this GitHub project.

**Comment by kodz1** [comment]
Can confirm the issue is how outlook mail handles the url.

###### I am just a volunteer on this GitHub project.

**Comment by kodz1** [comment]
The code `url: "mailto:?to=&subject={t}&body={u}%0A{d}",` could be changed to `url: "mailto:?subject={t}&body={u}%0A{d}",` simply omitting `to=&` should work.

It be a tad more work, but you could also have multiple options of
`url: "mailto:?to=&subject={t}&body={u}%0A{d}",` 
`url: "mailto:?to={e}&subject={t}&body={u}%0A{d}",` 

`{e}` this being the email added to data-wb-share array.

**Comment by nancy-hebert** [comment]
Hi

i was wondering if anyone worked on this.
I am volunteering to make a PR for it 

Are you ok with me using the following release : release-v4.0.28.1?

**Comment by pat-norris** [comment]
I have created a pull request with the fix described by @kodz1. Available here: https://github.com/wet-boew/wet-boew/pull/9584
