### ISSUE TITLE
[BUG] JS error on page with slick slider

### ISSUE THREAD

**Issue by smulvih2** [wet-boew/wet-boew#9470]
## Required information

**Describe the bug**
After Drupal WxT updated wet-boew/wet-boew from version v4.0.43.1 to v4.0.50.1, any page with a slick slider on it throws a JS error:

_Uncaught TypeError: i18nText is undefined - [wet-boew.js:14311:3]_

This bug seems to have bee introduced in version v4.0.46 - [https://github.com/wet-boew/wet-boew-cdn/compare/v4.0.45.1...v4.0.46#diff-442b0513b07334a26e75806d5132339a8c89f563d22b84b0b9a0ae34b5c5cc16R13507](https://github.com/wet-boew/wet-boew-cdn/compare/v4.0.45.1...v4.0.46#diff-442b0513b07334a26e75806d5132339a8c89f563d22b84b0b9a0ae34b5c5cc16R13507)

The JS code seems to be related to DataTables sorting, although this issue happens on pages without any tables.

Here is the markup of my slick slider for reference:

```
<div id="slick-views-alerts-block-block-1-1-slider" data-slick="{&quot;adaptiveHeight&quot;:true,&quot;autoplay&quot;:true,&quot;arrows&quot;:false,&quot;dots&quot;:true,&quot;draggable&quot;:false,&quot;fade&quot;:true,&quot;lazyLoad&quot;:&quot;blazy&quot;}" class="slick__slider slick-initialized slick-slider slick-dotted">
  <div class="slick-list" style="height: 181.167px;"><div class="slick-track" style="opacity: 1; width: 1292px;"><div class="slick__slide slide slide--0 slide--text slick-slide slick-current slick-active" data-slick-index="0" aria-hidden="false" style="width: 646px; position: relative; left: 0px; top: 0px; z-index: 999; opacity: 1;">
    <div class="slide__content">
       <div class="slide__caption">
         <h2 class="slide__title">Test</h2>
          <div class="slide__description">
            <div class="views-field views-field-body"><div class="field-content">
              <p>Test content</p>
            </div>
          </div>
        </div>
     </div>         
  </div>
</div>
<div class="slick__slide slide slide--1 slide--text slick-slide" data-slick-index="1" aria-hidden="true" style="width: 646px; position: relative; left: -646px; top: 0px; z-index: 998; opacity: 0;">
  <div class="slide__content">
    <div class="slide__caption">
      <h2 class="slide__title">Test 2</h2>
      <div class="slide__description">
        <div class="views-field views-field-body"><div class="field-content">
          <p>This is alert 2 body...</p>
        </div>
      </div>
    </div>
  </div>
 </div>  </div></div></div>  
<ul class="slick-dots" style=""><li class="slick-active"><button type="button">1</button></li><li><button type="button">2</button></li></ul></div>
```

## Additional information (optional)

**Version of WET-BOEW/GCWeb you are using**
v4.0.46+

**Desktop/Smartphone (please complete the following information)**
 - OS or Device: Ubuntu
 - Browser Firefox

Drupal.org ticket - [https://www.drupal.org/project/wxt/issues/3294585](https://www.drupal.org/project/wxt/issues/3294585)

**Comment by duboisp** [comment]
Thanks @smulvih2 for reporting the issue

Since the version 4.0.46, we applied some jQuery security fix which that since any jQuery DOM manipulation are subject to be sanitized with DOMPurify. That said, so when WET is used with third party plugin or custom JS code, there is a risk it generate an error depending of the jQuery DOM manipulation technique that was used by that third party plugin or custom JS code. Such issue caused by third party code are out of scope of our API which means the jQuery security fix we applied are considered to be a patch change.

Based on the code sample you provided in the Drupal ticket, it seems the slick slider plugin are triggering somehow the jQuery event "init.dt" which it do conflict with a similar event used by our datatable plugin.

A possible solution can be to strength the function executed by the event "init.dt" of our datatable plugin to ensure it get trigger only in the datatable context. I remarked there is no selector specified for that event listener.

**Propose code change:** 
[Line 214 in the table.js](https://github.com/wet-boew/wet-boew/blob/master/src/plugins/tables/tables.js#L214): 
```js
$document.on( "init.dt", function( event ) {
```
Get it replaced by: 
```js
$document.on( "init.dt", selector, function( event ) {
```

Test: Ensure the datatable work as expected and still apply the fix (ordering + aria-label)

---

For reference, here the comment you did in the Drupal ticket

> [smulvih2](https://www.drupal.org/u/smulvih2)
Location Canada 🍁
CreditAttribution: smulvih2 at [Cinder Systems Corp.](https://www.drupal.org/cinder-systems-corp), [Health Canada - HPFB](https://www.drupal.org/health-canada-hpfb) commented 6 months ago
> 
> Error happens on the line below next to "<<<<<<<<<<<<"
> 
> ```
> // Identify that initialization has completed
> $document.on( "init.dt", function( event ) {
>	var $elm = $( event.target ),
>		settings = $.extend( true, {}, defaults, window[ componentName ], wb.getData( $elm, componentName ) );
>
>	// Handle sorting/ordering
>	var ordering = ( settings && settings.ordering === false ) ? false : true;
>	if ( ordering ) {
>		$elm.find( "th" ).each( function() {
>			var $th = $( this ),
>				label = ( $th.attr( "aria-sort" ) === "ascending" ) ? i18nText.aria.sortDescending : i18nText.aria.sortAscending;
>
>			$th.html( "<button type='button' aria-controls='" + $th.attr( "aria-controls" ) +  "' title='" + $th.text().replace( /'/g, "&#39;" ) + label + "'>" + $th.html() + "<span class='sorting-cnt'><span class='sorting-icons' aria-hidden='true'></span></span></button>" );
>			$th.removeAttr( "aria-label tabindex aria-controls" );
>		} );
>		$elm.attr( "aria-label", i18nText.tblFilterInstruction );<<<<<<<<<<<<<<<<
>	}
>	wb.ready( $( event.target ), componentName );
> ```

**Comment by duboisp** [comment]
@smulvih2 Note that my propose fix might don't fully resolve your issue to get the "slick slider" plugin working and the reported issue from the datatable don't seem related to the jQuery security we applied in v4.0.46.

**Comment by duboisp** [comment]
@smulvih2 sorry, that are not related to the jQueryfix, sorry, I just looked up at the [release note of v4.0.46](https://github.com/wet-boew/wet-boew/releases/tag/v4.0.46) and we  did applied an accessibility improvement for the datatable.

However, the datatable scope was missing long time before that addition. So this propose fix might fix your issue. If you can submit a PR to wet-boew it will speed us the process to have it fixed. We create weekly release of wet-boew which happen after the [technical PR review](https://github.com/wet-boew/wet-boew/wiki/WET-Office-hours,-Heures-de-service-de-la-BOEW) each Monday. 

Again, here the change required to wet-boew which should fix your issue:

**Propose code change:** 
[Line 214 in the table.js](https://github.com/wet-boew/wet-boew/blob/master/src/plugins/tables/tables.js#L214): 
```js
$document.on( "init.dt", function( event ) {
```
Get it replaced by: 
```js
$document.on( "init.dt", selector, function( event ) {
```

Test: Ensure the datatable work as expected and still apply the fix (ordering + aria-label)
