### ISSUE TITLE
[BUG] Twitter's spinning icon still shows

### ISSUE THREAD

**Issue by ionut-ottawa** [wet-boew/wet-boew#9503]
The spinning icon which should show getting feeds from Twitter is doubled and only one is removed after the feeds are received. 
It is present even in the demo
https://wet-boew.github.io/wet-boew/demos/twitter/twitter-en.html
Thank you,
Ionut

**Comment by prosperva** [comment]
[Update] There have been recent updates to Embedded Twitter Timelines and supported parameters.	

For more information on what has changed visit: https://twittercommunity.com/t/embedded-timelines-update-parameters-support/177112

Please submit feedback or report any bugs: https://twittercommunity.com/c/publisher/websites/

**Comment by prosperva** [comment]
Is your code accessible anywhere?

**Comment by ionut-ottawa** [comment]
No, it's not since I've hided the spinning thing via CSS but the code is almost identical (just different screen_name) with the one from the link I've posted when I created the issue.

**Comment by prosperva** [comment]
This is the CSS that is causing the spinner:

```
.geomap-progress:before, .wb-enable .wb-twitter .twitter-timeline:before, .wb-mltmd.video.waiting .display:before, .wb-mltmd.video:not(.playing):not(.waiting) .display:before {
    background: rgba(0,0,0,.7);  /*THIS ADDS THE SPINNER BOX*/
    border-radius: 10px;
}
```
and this is the content that produces the white spinner inside the box described above

```
.geomap-progress:after, .wb-enable .wb-twitter .twitter-timeline:after, .wb-mltmd.video.waiting .display:after {
    -webkit-animation-duration: .5s;
    animation-duration: .5s;
    -webkit-animation-iteration-count: infinite;
    animation-iteration-count: infinite;
    -webkit-animation-name: spin;
    animation-name: spin;
    -webkit-animation-timing-function: linear;
    animation-timing-function: linear;
    color: #fff;
    content: "\e031";
    font-family: "Glyphicons Halflings";
    font-size: 3.5em;
    height: 1em;
    line-height: 1.03;
    width: 1em;
    z-index: 2;
}
```

Two ways to solve it are either looking into the WET jQuery and disabling it or removing the CSS above. I just tried it in the Developer Console and the spinner disappeared. This is probably a bug.

Another thing I tried to confirm my findings is using https://publish.twitter.com/ which creates a timeline for you without WET code and the timeline showed up without the spinner: https://publish.twitter.com/?query=https%3A%2F%2Ftwitter.com%2FWebExpToolkit&widget=Timeline

**Comment by EricDunsworth** [comment]
I haven't tried prepping a PR for this yet, but modifying the loading overlay's SCSS selectors to target ``a.twitter-timeline`` (instead of ``.twitter-timeline``) might be enough to do the trick.

When WET is in JS mode (which adds a ``wb.-enable`` class to the ``html`` element), the Twitter plugin renders in the following sequence for me in Firefox:
1. The hardcoded Twitter link's overlay immediately appears (due to its ``twitter-timeline`` class).
2. A container ``div`` for the Twitter timeline (which also uses a ``twitter-timeline`` class) gets injected just before the hardcoded link... resulting in two loading overlays appearing one-on-top of the other.
3. The hardcoded Twitter link and its loading overlay subsequently get removed after the container ``div`` gets filled-in with a timeline.
4. The container div's loading overlay stays in place forever since due to its ``twitter-timeline`` class never getting removed.

**Comment by EricDunsworth** [comment]
FWIW I didn't end up liking my last comment's workaround and came up with something more elaborate... will try to send over a PR for it early next week :).
