### ISSUE TITLE
Datatables - column with sorting disabled generates invalid aria-controls value of undefined

### ISSUE THREAD

**Issue by GarthMartin** [wet-boew/wet-boew#9564]
Our WCAG tester identified an issue with a table that has had sorting disabled via columnDefs, where the aria-controls value is "undefined" instead of the table name.

My columnDefs parameter is :

```"columnDefs" : [{ "targets" : [7], "orderable": false }]```

which generates this HTML:

```<button type="button" aria-controls="undefined" title="Actions: activate for ascending sort">Actions<span class="sorting-cnt"><span class="sorting-icons" aria-hidden="true"></span></span></button>```

I tried adding a ariaTitle to the columnDefs as well but it does not do anything differently.

Any way to get around this issue?

**Comment by wewhite** [comment]
Since you have disabled sorting on that column, the control for sorting is disabled, hence undefined.
'aria-controls="undefined"' is a valid value.

Undefined Value: The "undefined" value, when allowed on a state or property, is an explicit indication that the state or property is not set. The value is used on states and properties that support tokens, and the "undefined" value is a string that is one of the allowed tokens. It is also used on some states and properties that accept true/false values, when "undefined" has a different meaning than "false".

**Comment by GarthMartin** [comment]
Unfortunately the w3c validator thinks otherwise:
![image](https://user-images.githubusercontent.com/11050106/231610388-c82cb536-b562-44d2-ab31-ccc40365155e.png)

Any thoughts on how to work around this?

**Comment by wewhite** [comment]
I have a feeling this is a DataTables issue.
As a work around, you can set the table header for the column `<th data-orderable="false">TableColumnTitle</th>`.
WET completely removes the attribute aria-controls this way.

**Comment by GarthMartin** [comment]
@wewhite I had thought it was datatables as well, but I posted there before posting here and the owner said that they do not inject any ```<button> ``` elements in the header.  I will try the explicit orderable on the ```<th>``` and see what I get.  Thanks.

**Comment by GarthMartin** [comment]
Unfortunately the data-orderable does not seem to work either.  

As a workaround I decided to remove the attribute with javascript:

```$("th.sorting_disabled > button").removeAttr("aria-controls");```

**Comment by wewhite** [comment]
> Unfortunately the data-orderable does not seem to work either.

Fixed since v4.0.56.1
