### ISSUE TITLE
[BUG] Most requested - List of urls not in the proper order

### ISSUE THREAD

**Issue by KarineChamp** [wet-boew/wet-boew#9833]
Hello,

the Most requested code sample is not listing the list of urls in the proper order, which creates unwanted spaces:

https://wet-boew.github.io/GCWeb/components/gc-most-requested/gc-most-requested-en.html

![image](https://github.com/user-attachments/assets/a87edf7e-3b8f-4aa3-9359-23b8bde10029)

It looks like the list should be ordered from up to down, and not from left to right.

thanks.

Karine

**Comment by mercury64** [comment]
And on a mobile, it would be out of order.
Shrink the width of your page.

**Comment by mercury64** [comment]
It is top down, look at the source code.
<section class="gc-most-requested">
	<div class="container">
		<h2>Most requested</h2>
		<ul>
			<li><a href="#">[Top task hyperlink 1]</a></li>
			<li><a href="#">[Top task hyperlink 2]</a></li>
			<li><a href="#">[Top task hyperlink 3]</a></li>
			<li><a href="#">[Top task hyperlink 4]</a></li>
			<li><a href="#">[Top task hyperlink with a very long task name that spans over two lines 5]</a></li>
			<li><a href="#">[Top task hyperlink with a very long task name that spans over two lines 6]</a></li>
		</ul>
	</div>
</section>

Unwanted spaces are due to the fact that the styling (flex?box?) is making the long text it fit into 3 columns(wrap)?
View on a smaller screen, it appears correctly.

This is not a WET-BOEW bug. If anything this maybe a bug with GCWeb styling, but I doubt it.
If you need to, override the styling to suite your requirements.

**Comment by mercury64** [comment]
Here is a good one, apparently my example is a Bad Implementation:
https://wet-boew.github.io/GCWeb/components/gc-most-requested/gc-most-requested-bad-en.html
